import type { MainWordExampleText } from "./main-word-example-pairs/types";

export type MainWordLegacyExample = MainWordExampleText & {
  sortOrder: number;
};

// Captured from the published main catalog on 2026-08-24. The complete sets
// guard the two-example migration from overwriting later editorial changes.
export const MAIN_WORD_LEGACY_EXAMPLE_SETS: Array<{
  id: string;
  examples: MainWordLegacyExample[];
}> = [
  { id: "fridge", examples: [{"sortOrder":0,"en":"Put the milk in the fridge.","ja":"牛乳を冷蔵庫に入れてください。","zh":"把牛奶放進冰箱。"},{"sortOrder":1,"en":"The fridge is full of food.","ja":"冷蔵庫は食べ物でいっぱいです。","zh":"冰箱裡裝滿了食物。"},{"sortOrder":2,"en":"Can you check the fridge for eggs?","ja":"冷蔵庫に卵があるか見てくれますか？","zh":"你能看看冰箱裡有沒有蛋嗎？"}] },
  { id: "microwave", examples: [{"sortOrder":0,"en":"Heat the soup in the microwave.","ja":"スープを電子レンジで温めてください。","zh":"把湯放進微波爐加熱。"},{"sortOrder":1,"en":"Don't put metal in the microwave.","ja":"電子レンジに金属を入れないでください。","zh":"不要把金屬放進微波爐。"},{"sortOrder":2,"en":"The microwave beeps when it's done.","ja":"電子レンジは終わるとピーと鳴ります。","zh":"微波爐完成時會發出嗶聲。"}] },
  { id: "oven", examples: [{"sortOrder":0,"en":"Preheat the oven to 180 degrees.","ja":"オーブンを180度に予熱してください。","zh":"預熱烤箱到 180 度。"},{"sortOrder":1,"en":"The cake is still in the oven.","ja":"ケーキはまだオーブンの中にあります。","zh":"蛋糕還在烤箱裡。"},{"sortOrder":2,"en":"Be careful, the oven is hot.","ja":"気をつけて、オーブンは熱いです。","zh":"小心，烤箱很燙。"}] },
  { id: "stove", examples: [{"sortOrder":0,"en":"She is cooking on the stove.","ja":"彼女はコンロで料理しています。","zh":"她正在爐子上煮東西。"},{"sortOrder":1,"en":"Turn off the stove when you finish.","ja":"終わったらコンロを消してください。","zh":"煮完後請關掉爐子。"},{"sortOrder":2,"en":"Our stove uses gas.","ja":"私たちのコンロはガス式です。","zh":"我們的爐子是用瓦斯的。"}] },
  { id: "sink", examples: [{"sortOrder":0,"en":"The dishes are in the sink.","ja":"食器はシンクの中にあります。","zh":"碗盤在水槽裡。"},{"sortOrder":1,"en":"Don't pour oil into the sink.","ja":"シンクに油を流さないでください。","zh":"不要把油倒進水槽。"},{"sortOrder":2,"en":"She washed her hands at the sink.","ja":"彼女はシンクで手を洗いました。","zh":"她在水槽邊洗手。"}] },
  { id: "faucet", examples: [{"sortOrder":0,"en":"Turn off the faucet to save water.","ja":"水を節約するために蛇口を閉めてください。","zh":"關掉水龍頭以節省用水。"},{"sortOrder":1,"en":"The faucet is leaking.","ja":"蛇口から水が漏れています。","zh":"水龍頭在漏水。"},{"sortOrder":2,"en":"Cold water comes out of this faucet.","ja":"この蛇口からは冷水が出ます。","zh":"這個水龍頭流出來的是冷水。"}] },
  { id: "pan", examples: [{"sortOrder":0,"en":"Heat the oil in a pan.","ja":"フライパンで油を温めます。","zh":"把油在平底鍋裡加熱。"},{"sortOrder":1,"en":"She fried the eggs in a pan.","ja":"彼女はフライパンで卵を焼きました。","zh":"她用平底鍋煎蛋。"},{"sortOrder":2,"en":"This pan is non-stick.","ja":"このフライパンはくっつかないタイプです。","zh":"這個平底鍋是不沾鍋。"}] },
  { id: "pot", examples: [{"sortOrder":0,"en":"Boil water in the pot.","ja":"鍋でお湯を沸かします。","zh":"用鍋子煮開水。"},{"sortOrder":1,"en":"She cooked a big pot of soup.","ja":"彼女は大鍋でスープを作りました。","zh":"她煮了一大鍋湯。"},{"sortOrder":2,"en":"Cover the pot with a lid.","ja":"鍋に蓋をしてください。","zh":"把鍋蓋蓋上。"}] },
  { id: "cutting-board", examples: [{"sortOrder":0,"en":"Chop the onions on the cutting board.","ja":"まな板の上で玉ねぎを切ります。","zh":"在砧板上切洋蔥。"},{"sortOrder":1,"en":"Use a clean cutting board for meat.","ja":"肉を切るときは清潔なまな板を使います。","zh":"切肉要用乾淨的砧板。"},{"sortOrder":2,"en":"The cutting board is made of wood.","ja":"このまな板は木製です。","zh":"這個砧板是木製的。"}] },
  { id: "knife", examples: [{"sortOrder":0,"en":"Be careful with the knife.","ja":"ナイフを使う時は気をつけて。","zh":"用刀子要小心。"},{"sortOrder":1,"en":"This knife is very sharp.","ja":"このナイフはとても鋭いです。","zh":"這把刀非常鋒利。"},{"sortOrder":2,"en":"She cut the bread with a knife.","ja":"彼女はナイフでパンを切りました。","zh":"她用刀切麵包。"}] },
  { id: "bowl", examples: [{"sortOrder":0,"en":"I'd like a bowl of rice.","ja":"ご飯を一杯ください。","zh":"我想要一碗飯。"},{"sortOrder":1,"en":"Put the salad in the bowl.","ja":"サラダをボウルに入れてください。","zh":"把沙拉放進碗裡。"},{"sortOrder":2,"en":"The bowl is full of fruit.","ja":"ボウルには果物がいっぱい入っています。","zh":"碗裡裝滿了水果。"}] },
  { id: "plate", examples: [{"sortOrder":0,"en":"Please pass me a plate.","ja":"お皿を取ってください。","zh":"請遞給我一個盤子。"},{"sortOrder":1,"en":"He finished everything on his plate.","ja":"彼はお皿の上のものを全部食べ終えました。","zh":"他把盤子裡的東西都吃完了。"},{"sortOrder":2,"en":"The plate is hot.","ja":"お皿が熱いです。","zh":"盤子很燙。"}] },
  { id: "chopsticks", examples: [{"sortOrder":0,"en":"Can you use chopsticks?","ja":"箸を使えますか？","zh":"你會用筷子嗎？"},{"sortOrder":1,"en":"He picked up the noodles with chopsticks.","ja":"彼は箸で麺をつまみました。","zh":"他用筷子夾起麵條。"},{"sortOrder":2,"en":"I need a pair of chopsticks.","ja":"箸が一膳必要です。","zh":"我需要一雙筷子。"}] },
  { id: "spoon", examples: [{"sortOrder":0,"en":"Stir the coffee with a spoon.","ja":"スプーンでコーヒーをかき混ぜます。","zh":"用湯匙攪拌咖啡。"},{"sortOrder":1,"en":"Add a spoon of sugar.","ja":"砂糖を一さじ加えてください。","zh":"加一匙糖。"},{"sortOrder":2,"en":"The baby is learning to use a spoon.","ja":"赤ちゃんはスプーンの使い方を覚えています。","zh":"寶寶正在學用湯匙。"}] },
  { id: "mug", examples: [{"sortOrder":0,"en":"I drink coffee from a big mug.","ja":"私は大きなマグカップでコーヒーを飲みます。","zh":"我用大馬克杯喝咖啡。"},{"sortOrder":1,"en":"This mug has my name on it.","ja":"このマグカップには私の名前が書いてあります。","zh":"這個馬克杯上有我的名字。"},{"sortOrder":2,"en":"Pour the tea into the mug.","ja":"マグカップにお茶を注いでください。","zh":"把茶倒進馬克杯。"}] },
  { id: "toothbrush", examples: [{"sortOrder":0,"en":"I need a new toothbrush.","ja":"新しい歯ブラシが必要です。","zh":"我需要一支新牙刷。"},{"sortOrder":1,"en":"Brush your teeth with a toothbrush.","ja":"歯ブラシで歯を磨きます。","zh":"用牙刷刷牙。"},{"sortOrder":2,"en":"Her toothbrush is pink.","ja":"彼女の歯ブラシはピンクです。","zh":"她的牙刷是粉紅色的。"}] },
  { id: "toothpaste", examples: [{"sortOrder":0,"en":"Put toothpaste on your toothbrush.","ja":"歯ブラシに歯磨き粉をつけてください。","zh":"把牙膏擠在牙刷上。"},{"sortOrder":1,"en":"We're running out of toothpaste.","ja":"歯磨き粉がもうすぐなくなります。","zh":"牙膏快用完了。"},{"sortOrder":2,"en":"This toothpaste tastes like mint.","ja":"この歯磨き粉はミント味です。","zh":"這牙膏是薄荷口味。"}] },
  { id: "towel", examples: [{"sortOrder":0,"en":"Dry your hands with the towel.","ja":"タオルで手を拭いてください。","zh":"用毛巾擦乾手。"},{"sortOrder":1,"en":"The towels are in the closet.","ja":"タオルはクローゼットにあります。","zh":"毛巾在櫃子裡。"},{"sortOrder":2,"en":"She wrapped a towel around her hair.","ja":"彼女はタオルを髪に巻きました。","zh":"她用毛巾包住頭髮。"}] },
  { id: "soap", examples: [{"sortOrder":0,"en":"Wash your hands with soap.","ja":"石けんで手を洗ってください。","zh":"用肥皂洗手。"},{"sortOrder":1,"en":"This soap smells like lemon.","ja":"この石けんはレモンの香りがします。","zh":"這塊肥皂有檸檬味。"},{"sortOrder":2,"en":"I need a new bar of soap.","ja":"新しい石けんが必要です。","zh":"我需要一塊新的肥皂。"}] },
  { id: "shampoo", examples: [{"sortOrder":0,"en":"I use this shampoo every day.","ja":"私はこのシャンプーを毎日使っています。","zh":"我每天都用這款洗髮精。"},{"sortOrder":1,"en":"We need to buy more shampoo.","ja":"シャンプーをもっと買う必要があります。","zh":"我們得買更多洗髮精。"},{"sortOrder":2,"en":"This shampoo is good for dry hair.","ja":"このシャンプーは乾燥した髪に良いです。","zh":"這款洗髮精適合乾性頭髮。"}] },
  { id: "shower", examples: [{"sortOrder":0,"en":"I take a shower every morning.","ja":"私は毎朝シャワーを浴びます。","zh":"我每天早上洗澡。"},{"sortOrder":1,"en":"The shower is broken.","ja":"シャワーが壊れています。","zh":"蓮蓬頭壞了。"},{"sortOrder":2,"en":"He sings in the shower.","ja":"彼はシャワーを浴びながら歌います。","zh":"他洗澡時會唱歌。"}] },
  { id: "mirror", examples: [{"sortOrder":0,"en":"She looked at herself in the mirror.","ja":"彼女は鏡で自分を見ました。","zh":"她在鏡子裡看著自己。"},{"sortOrder":1,"en":"The mirror is fogged up.","ja":"鏡が曇りました。","zh":"鏡子起霧了。"},{"sortOrder":2,"en":"There's a big mirror on the wall.","ja":"壁に大きな鏡があります。","zh":"牆上有一面大鏡子。"}] },
  { id: "toilet", examples: [{"sortOrder":0,"en":"Please flush the toilet.","ja":"トイレを流してください。","zh":"請沖馬桶。"},{"sortOrder":1,"en":"The toilet is clogged.","ja":"トイレが詰まりました。","zh":"馬桶塞住了。"},{"sortOrder":2,"en":"Where's the toilet?","ja":"トイレはどこですか？","zh":"廁所在哪裡？"}] },
  { id: "comb", examples: [{"sortOrder":0,"en":"Use a comb to fix your hair.","ja":"くしで髪を整えます。","zh":"用梳子整理頭髮。"},{"sortOrder":1,"en":"I lost my comb.","ja":"くしをなくしました。","zh":"我的梳子不見了。"},{"sortOrder":2,"en":"This comb is plastic.","ja":"このくしはプラスチック製です。","zh":"這把梳子是塑膠的。"}] },
  { id: "hair-dryer", examples: [{"sortOrder":0,"en":"She dried her hair with a hair dryer.","ja":"彼女はドライヤーで髪を乾かしました。","zh":"她用吹風機把頭髮吹乾。"},{"sortOrder":1,"en":"The hair dryer is loud.","ja":"ドライヤーの音が大きいです。","zh":"吹風機聲音很大。"},{"sortOrder":2,"en":"Do you have a hair dryer?","ja":"ドライヤーを持っていますか？","zh":"你有吹風機嗎？"}] },
  { id: "bed", examples: [{"sortOrder":0,"en":"I go to bed at 11 p.m.","ja":"私は夜11時に寝ます。","zh":"我晚上 11 點睡覺。"},{"sortOrder":1,"en":"Please make your bed.","ja":"ベッドを整えてください。","zh":"請整理你的床。"},{"sortOrder":2,"en":"The cat is sleeping on the bed.","ja":"猫がベッドの上で寝ています。","zh":"貓在床上睡覺。"}] },
  { id: "pillow", examples: [{"sortOrder":0,"en":"This pillow is too soft.","ja":"この枕は柔らかすぎます。","zh":"這個枕頭太軟了。"},{"sortOrder":1,"en":"She put her head on the pillow.","ja":"彼女は枕に頭を乗せました。","zh":"她把頭靠在枕頭上。"},{"sortOrder":2,"en":"I need a new pillow.","ja":"新しい枕が必要です。","zh":"我需要一個新枕頭。"}] },
  { id: "blanket", examples: [{"sortOrder":0,"en":"It's cold; grab a blanket.","ja":"寒いので、毛布を取ってください。","zh":"好冷，拿條毯子吧。"},{"sortOrder":1,"en":"He hid under the blanket.","ja":"彼は毛布の下に隠れました。","zh":"他躲在毯子下面。"},{"sortOrder":2,"en":"This blanket is very warm.","ja":"この毛布はとても暖かいです。","zh":"這條毯子很暖。"}] },
  { id: "closet", examples: [{"sortOrder":0,"en":"Hang the coat in the closet.","ja":"コートをクローゼットに掛けてください。","zh":"把外套掛到衣櫃裡。"},{"sortOrder":1,"en":"Her closet is full of dresses.","ja":"彼女のクローゼットはドレスでいっぱいです。","zh":"她的衣櫃裡塞滿了洋裝。"},{"sortOrder":2,"en":"Close the closet door.","ja":"クローゼットのドアを閉めてください。","zh":"把衣櫃門關上。"}] },
  { id: "lamp", examples: [{"sortOrder":0,"en":"Turn on the lamp.","ja":"ランプをつけてください。","zh":"把檯燈打開。"},{"sortOrder":1,"en":"She reads under a lamp.","ja":"彼女はランプの下で本を読みます。","zh":"她在檯燈下看書。"},{"sortOrder":2,"en":"The lamp is broken.","ja":"ランプが壊れています。","zh":"檯燈壞了。"}] },
  { id: "alarm-clock", examples: [{"sortOrder":0,"en":"I set the alarm clock for 7 a.m.","ja":"目覚まし時計を朝7時にセットしました。","zh":"我把鬧鐘設成早上 7 點。"},{"sortOrder":1,"en":"The alarm clock woke me up.","ja":"目覚まし時計に起こされました。","zh":"鬧鐘把我吵醒了。"},{"sortOrder":2,"en":"Where is my alarm clock?","ja":"私の目覚まし時計はどこ？","zh":"我的鬧鐘在哪？"}] },
  { id: "curtain", examples: [{"sortOrder":0,"en":"Please open the curtains.","ja":"カーテンを開けてください。","zh":"請把窗簾拉開。"},{"sortOrder":1,"en":"The curtains are blue.","ja":"カーテンは青いです。","zh":"窗簾是藍色的。"},{"sortOrder":2,"en":"Close the curtains at night.","ja":"夜はカーテンを閉めてください。","zh":"晚上把窗簾拉上。"}] },
  { id: "wardrobe", examples: [{"sortOrder":0,"en":"She opened her wardrobe.","ja":"彼女はワードローブを開けました。","zh":"她打開了衣櫥。"},{"sortOrder":1,"en":"There is a mirror on the wardrobe.","ja":"ワードローブの上に鏡があります。","zh":"衣櫥上有面鏡子。"},{"sortOrder":2,"en":"His wardrobe is mostly black.","ja":"彼の服はほとんど黒です。","zh":"他的衣服大多是黑色的。"}] },
  { id: "sofa", examples: [{"sortOrder":0,"en":"Let's sit on the sofa.","ja":"ソファに座りましょう。","zh":"我們坐在沙發上吧。"},{"sortOrder":1,"en":"The cat is on the sofa.","ja":"猫がソファにいます。","zh":"貓在沙發上。"},{"sortOrder":2,"en":"Our sofa is too small.","ja":"私たちのソファは小さすぎます。","zh":"我們的沙發太小。"}] },
  { id: "tv", examples: [{"sortOrder":0,"en":"We watch TV every night.","ja":"私たちは毎晩テレビを見ます。","zh":"我們每天晚上看電視。"},{"sortOrder":1,"en":"Turn off the TV, please.","ja":"テレビを消してください。","zh":"請把電視關掉。"},{"sortOrder":2,"en":"The TV is too loud.","ja":"テレビの音が大きすぎます。","zh":"電視太大聲了。"}] },
  { id: "remote", examples: [{"sortOrder":0,"en":"Where is the remote?","ja":"リモコンはどこですか？","zh":"遙控器在哪裡？"},{"sortOrder":1,"en":"Pass me the remote.","ja":"リモコンを取ってください。","zh":"把遙控器遞給我。"},{"sortOrder":2,"en":"The remote needs new batteries.","ja":"リモコンの電池を交換する必要があります。","zh":"遙控器要換新電池。"}] },
  { id: "coffee-table", examples: [{"sortOrder":0,"en":"Put the magazine on the coffee table.","ja":"雑誌をコーヒーテーブルに置いてください。","zh":"把雜誌放在茶几上。"},{"sortOrder":1,"en":"There's a vase on the coffee table.","ja":"コーヒーテーブルに花瓶があります。","zh":"茶几上有個花瓶。"},{"sortOrder":2,"en":"Don't put your feet on the coffee table.","ja":"コーヒーテーブルに足を乗せないでください。","zh":"不要把腳放在茶几上。"}] },
  { id: "rug", examples: [{"sortOrder":0,"en":"There's a rug under the table.","ja":"テーブルの下にラグがあります。","zh":"桌子底下有塊地毯。"},{"sortOrder":1,"en":"The dog is sleeping on the rug.","ja":"犬がラグの上で寝ています。","zh":"狗在地毯上睡覺。"},{"sortOrder":2,"en":"This rug is handmade.","ja":"このラグは手作りです。","zh":"這塊地毯是手工的。"}] },
  { id: "clock", examples: [{"sortOrder":0,"en":"The clock says it's three.","ja":"時計は3時を指しています。","zh":"時鐘顯示三點。"},{"sortOrder":1,"en":"There's a clock on the wall.","ja":"壁に時計があります。","zh":"牆上有個時鐘。"},{"sortOrder":2,"en":"The clock is fast.","ja":"時計が進んでいます。","zh":"時鐘快了。"}] },
  { id: "picture-frame", examples: [{"sortOrder":0,"en":"She put the photo in a picture frame.","ja":"彼女は写真を写真フレームに入れました。","zh":"她把照片放進相框。"},{"sortOrder":1,"en":"The picture frame is wooden.","ja":"写真フレームは木製です。","zh":"相框是木製的。"},{"sortOrder":2,"en":"There are many picture frames on the shelf.","ja":"棚にたくさんの写真フレームがあります。","zh":"架子上有很多相框。"}] },
  { id: "desk", examples: [{"sortOrder":0,"en":"I put my laptop on the desk.","ja":"ノートパソコンをデスクに置きます。","zh":"我把筆電放在辦公桌上。"},{"sortOrder":1,"en":"Clean your desk before leaving.","ja":"退室前にデスクを片付けてください。","zh":"離開前清理你的書桌。"},{"sortOrder":2,"en":"Her desk is by the window.","ja":"彼女のデスクは窓の近くにあります。","zh":"她的書桌靠近窗戶。"}] },
  { id: "laptop", examples: [{"sortOrder":0,"en":"I work on my laptop.","ja":"私はノートパソコンで仕事をします。","zh":"我用筆電工作。"},{"sortOrder":1,"en":"The laptop is out of battery.","ja":"ノートパソコンの電池が切れました。","zh":"筆電沒電了。"},{"sortOrder":2,"en":"Close your laptop, please.","ja":"ノートパソコンを閉じてください。","zh":"請把筆電合上。"}] },
  { id: "keyboard", examples: [{"sortOrder":0,"en":"I type fast on this keyboard.","ja":"私はこのキーボードで速くタイピングできます。","zh":"我在這鍵盤上打字很快。"},{"sortOrder":1,"en":"The keyboard is wireless.","ja":"このキーボードはワイヤレスです。","zh":"這個鍵盤是無線的。"},{"sortOrder":2,"en":"Don't spill water on the keyboard.","ja":"キーボードに水をこぼさないでください。","zh":"別把水灑在鍵盤上。"}] },
  { id: "mouse", examples: [{"sortOrder":0,"en":"Click here with the mouse.","ja":"ここをマウスでクリックしてください。","zh":"用滑鼠點這裡。"},{"sortOrder":1,"en":"My mouse stopped working.","ja":"私のマウスが動かなくなりました。","zh":"我的滑鼠不能用了。"},{"sortOrder":2,"en":"This is a wireless mouse.","ja":"これはワイヤレスマウスです。","zh":"這是個無線滑鼠。"}] },
  { id: "monitor", examples: [{"sortOrder":0,"en":"I have two monitors at my desk.","ja":"私はデスクに二台のモニターを置いています。","zh":"我桌上有兩台螢幕。"},{"sortOrder":1,"en":"Turn off the monitor when you leave.","ja":"退室時にモニターを消してください。","zh":"離開時請把螢幕關掉。"},{"sortOrder":2,"en":"The monitor is too bright.","ja":"モニターが明るすぎます。","zh":"螢幕太亮了。"}] },
  { id: "notebook", examples: [{"sortOrder":0,"en":"Write your notes in the notebook.","ja":"メモはノートに書いてください。","zh":"把筆記寫在筆記本上。"},{"sortOrder":1,"en":"I lost my notebook.","ja":"私のノートをなくしました。","zh":"我的筆記本不見了。"},{"sortOrder":2,"en":"She has a small notebook in her bag.","ja":"彼女はカバンに小さなノートを入れています。","zh":"她包包裡有本小筆記本。"}] },
  { id: "pen", examples: [{"sortOrder":0,"en":"Can I borrow your pen?","ja":"ペンを貸してもらえますか？","zh":"可以借你的筆嗎？"},{"sortOrder":1,"en":"The pen ran out of ink.","ja":"ペンのインクが切れました。","zh":"筆沒墨水了。"},{"sortOrder":2,"en":"Sign here with a pen.","ja":"ペンでここにサインしてください。","zh":"用筆在這裡簽名。"}] },
  { id: "stapler", examples: [{"sortOrder":0,"en":"Where is the stapler?","ja":"ホチキスはどこですか？","zh":"釘書機在哪裡？"},{"sortOrder":1,"en":"The stapler is out of staples.","ja":"ホチキスの針がなくなりました。","zh":"釘書機沒釘針了。"},{"sortOrder":2,"en":"She stapled the papers together.","ja":"彼女は書類をホチキスでとじました。","zh":"她把紙釘在一起。"}] },
  { id: "printer", examples: [{"sortOrder":0,"en":"The printer is out of paper.","ja":"プリンターの紙が切れています。","zh":"印表機沒紙了。"},{"sortOrder":1,"en":"Please send it to the printer.","ja":"プリンターに送ってください。","zh":"請把它送到印表機。"},{"sortOrder":2,"en":"Our printer is broken.","ja":"私たちのプリンターは壊れています。","zh":"我們的印表機壞了。"}] },
  { id: "traffic-light", examples: [{"sortOrder":0,"en":"Stop at the traffic light.","ja":"信号機で止まってください。","zh":"在紅綠燈前停下。"},{"sortOrder":1,"en":"The traffic light is green now.","ja":"信号機は今、青です。","zh":"紅綠燈現在是綠燈。"},{"sortOrder":2,"en":"Wait for the traffic light to change.","ja":"信号機が変わるのを待ってください。","zh":"等紅綠燈變號。"}] },
  { id: "crosswalk", examples: [{"sortOrder":0,"en":"Use the crosswalk to cross the road.","ja":"横断歩道を渡ってください。","zh":"走斑馬線過馬路。"},{"sortOrder":1,"en":"There is a crosswalk ahead.","ja":"前方に横断歩道があります。","zh":"前方有斑馬線。"},{"sortOrder":2,"en":"Cars must stop at the crosswalk.","ja":"車は横断歩道で止まらなければなりません。","zh":"車子必須在斑馬線前停車。"}] },
  { id: "sidewalk", examples: [{"sortOrder":0,"en":"Walk on the sidewalk.","ja":"歩道を歩いてください。","zh":"走在人行道上。"},{"sortOrder":1,"en":"The sidewalk is crowded.","ja":"歩道は混雑しています。","zh":"人行道很擁擠。"},{"sortOrder":2,"en":"Don't ride your bike on the sidewalk.","ja":"歩道で自転車に乗らないでください。","zh":"不要在人行道上騎腳踏車。"}] },
  { id: "street-sign", examples: [{"sortOrder":0,"en":"Follow the directions on the street sign.","ja":"案内標識に従って進んでください。","zh":"請依照路標上的指示前進。"},{"sortOrder":1,"en":"The street sign points to the station.","ja":"案内標識は駅の方向を示しています。","zh":"路標指向車站的方向。"},{"sortOrder":2,"en":"There's a street sign at the intersection.","ja":"交差点に案内標識があります。","zh":"路口設有路標。"}] },
  { id: "bench", examples: [{"sortOrder":0,"en":"Let's sit on the bench.","ja":"ベンチに座りましょう。","zh":"我們坐長椅吧。"},{"sortOrder":1,"en":"An old man sat on the bench.","ja":"おじいさんがベンチに座っていました。","zh":"一位老先生坐在長椅上。"},{"sortOrder":2,"en":"The bench is wet.","ja":"ベンチが濡れています。","zh":"長椅是濕的。"}] },
  { id: "streetlight", examples: [{"sortOrder":0,"en":"The streetlights turned on.","ja":"街灯が点きました。","zh":"路燈亮起來了。"},{"sortOrder":1,"en":"Park under the streetlight.","ja":"街灯の下に車を停めます。","zh":"把車停在路燈下。"},{"sortOrder":2,"en":"One streetlight is broken.","ja":"街灯が一つ壊れています。","zh":"有一盞路燈壞了。"}] },
  { id: "trash-can", examples: [{"sortOrder":0,"en":"Throw it in the trash can.","ja":"ゴミ箱に捨ててください。","zh":"把它丟進垃圾桶。"},{"sortOrder":1,"en":"The trash can is full.","ja":"ゴミ箱がいっぱいです。","zh":"垃圾桶滿了。"},{"sortOrder":2,"en":"Where's the nearest trash can?","ja":"一番近いゴミ箱はどこですか？","zh":"最近的垃圾桶在哪？"}] },
  { id: "mailbox", examples: [{"sortOrder":0,"en":"Drop the letter in the mailbox.","ja":"手紙を郵便ポストに入れてください。","zh":"把信投進郵筒。"},{"sortOrder":1,"en":"The mailbox is red.","ja":"郵便ポストは赤いです。","zh":"郵筒是紅色的。"},{"sortOrder":2,"en":"The mailbox is on the corner.","ja":"郵便ポストは街角にあります。","zh":"郵筒在街角。"}] },
  { id: "shopping-cart", examples: [{"sortOrder":0,"en":"Push the shopping cart slowly.","ja":"ショッピングカートはゆっくり押してください。","zh":"慢慢推購物車。"},{"sortOrder":1,"en":"The shopping cart is full.","ja":"ショッピングカートがいっぱいです。","zh":"購物車裝滿了。"},{"sortOrder":2,"en":"Where can I find a shopping cart?","ja":"ショッピングカートはどこにありますか？","zh":"我可以在哪裡找到購物車？"}] },
  { id: "basket", examples: [{"sortOrder":0,"en":"Use a basket if you only buy a little.","ja":"少しだけ買うときは買い物かごを使いましょう。","zh":"東西不多就用購物籃。"},{"sortOrder":1,"en":"Put the apples in the basket.","ja":"りんごを買い物かごに入れてください。","zh":"把蘋果放進籃子。"},{"sortOrder":2,"en":"The basket is heavy.","ja":"かごが重いです。","zh":"籃子很重。"}] },
  { id: "cashier", examples: [{"sortOrder":0,"en":"The cashier scanned my groceries.","ja":"レジ係が商品をスキャンしました。","zh":"收銀員掃描了我買的商品。"},{"sortOrder":1,"en":"The cashier was friendly.","ja":"レジの店員は親切でした。","zh":"收銀員很親切。"},{"sortOrder":2,"en":"The cashier gave me the receipt.","ja":"レジに長い列ができています。","zh":"收銀員把收據交給我。"}] },
  { id: "receipt", examples: [{"sortOrder":0,"en":"Keep your receipt, please.","ja":"レシートを保管してください。","zh":"請保留收據。"},{"sortOrder":1,"en":"I lost the receipt.","ja":"レシートを失くしました。","zh":"我把收據弄丟了。"},{"sortOrder":2,"en":"Show your receipt at the exit.","ja":"出口でレシートを提示してください。","zh":"在出口出示收據。"}] },
  { id: "aisle", examples: [{"sortOrder":0,"en":"The bread is in aisle three.","ja":"パンは3番通路にあります。","zh":"麵包在第三排走道。"},{"sortOrder":1,"en":"Walk down the aisle.","ja":"通路を歩いてください。","zh":"沿著走道往前走。"},{"sortOrder":2,"en":"Which aisle has snacks?","ja":"お菓子はどの通路にありますか？","zh":"哪一排走道有零食？"}] },
  { id: "shelf", examples: [{"sortOrder":0,"en":"The cereal is on the top shelf.","ja":"シリアルは一番上の棚にあります。","zh":"麥片在最上層架子。"},{"sortOrder":1,"en":"The shelf is empty.","ja":"棚は空です。","zh":"架子是空的。"},{"sortOrder":2,"en":"Put it back on the shelf.","ja":"棚に戻してください。","zh":"把它放回架子上。"}] },
  { id: "bag", examples: [{"sortOrder":0,"en":"Paper or plastic bag?","ja":"紙袋ですか、ビニール袋ですか？","zh":"要紙袋還是塑膠袋？"},{"sortOrder":1,"en":"Bring your own bag.","ja":"マイバッグを持参してください。","zh":"請自備購物袋。"},{"sortOrder":2,"en":"The bag is too heavy.","ja":"袋が重すぎます。","zh":"袋子太重了。"}] },
  { id: "price-tag", examples: [{"sortOrder":0,"en":"Check the price tag.","ja":"値札を確認してください。","zh":"看一下價格標籤。"},{"sortOrder":1,"en":"There's no price tag on this.","ja":"これには値札が付いていません。","zh":"這個沒有貼價格標籤。"},{"sortOrder":2,"en":"The price tag says $5.","ja":"値札には5ドルと書いてあります。","zh":"價格標籤寫著 5 美元。"}] },
  { id: "car", examples: [{"sortOrder":0,"en":"I drive a car to work.","ja":"私は車で会社に行きます。","zh":"我開車上班。"},{"sortOrder":1,"en":"Park the car over there.","ja":"あちらに車を停めてください。","zh":"把車停在那邊。"},{"sortOrder":2,"en":"Whose car is this?","ja":"これは誰の車ですか？","zh":"這是誰的車？"}] },
  { id: "bus", examples: [{"sortOrder":0,"en":"I take the bus to school.","ja":"私はバスで学校に行きます。","zh":"我搭公車上學。"},{"sortOrder":1,"en":"Don't miss the bus.","ja":"バスに乗り遅れないでください。","zh":"別錯過公車。"},{"sortOrder":2,"en":"The bus is late.","ja":"バスが遅れています。","zh":"公車誤點了。"}] },
  { id: "bicycle", examples: [{"sortOrder":0,"en":"He rides his bicycle every day.","ja":"彼は毎日自転車に乗っています。","zh":"他每天騎腳踏車。"},{"sortOrder":1,"en":"I learned to ride a bicycle at six.","ja":"私は6歳で自転車に乗れるようになりました。","zh":"我六歲學會騎腳踏車。"},{"sortOrder":2,"en":"Where is my bicycle?","ja":"私の自転車はどこですか？","zh":"我的腳踏車在哪？"}] },
  { id: "motorcycle", examples: [{"sortOrder":0,"en":"He rides a motorcycle to work.","ja":"彼はバイクで会社に行きます。","zh":"他騎機車上班。"},{"sortOrder":1,"en":"Always wear a helmet on a motorcycle.","ja":"バイクに乗る時は必ずヘルメットをかぶってください。","zh":"騎機車一定要戴安全帽。"},{"sortOrder":2,"en":"Her motorcycle is red.","ja":"彼女のバイクは赤いです。","zh":"她的機車是紅色的。"}] },
  { id: "train", examples: [{"sortOrder":0,"en":"We took the train to Taipei.","ja":"私たちは電車で台北に行きました。","zh":"我們搭火車去台北。"},{"sortOrder":1,"en":"The train is leaving.","ja":"電車が発車します。","zh":"火車要開了。"},{"sortOrder":2,"en":"I missed the last train.","ja":"最終電車に乗り遅れました。","zh":"我錯過了最後一班火車。"}] },
  { id: "airplane", examples: [{"sortOrder":0,"en":"We flew on an airplane.","ja":"私たちは飛行機に乗りました。","zh":"我們搭飛機。"},{"sortOrder":1,"en":"The airplane is taking off.","ja":"飛行機が離陸しています。","zh":"飛機要起飛了。"},{"sortOrder":2,"en":"I'm afraid of airplanes.","ja":"私は飛行機が怖いです。","zh":"我怕坐飛機。"}] },
  { id: "boat", examples: [{"sortOrder":0,"en":"We took a boat across the lake.","ja":"私たちはボートで湖を渡りました。","zh":"我們搭船渡湖。"},{"sortOrder":1,"en":"The boat is small.","ja":"ボートは小さいです。","zh":"船很小。"},{"sortOrder":2,"en":"There's a fishing boat.","ja":"漁船があります。","zh":"有一艘漁船。"}] },
  { id: "taxi", examples: [{"sortOrder":0,"en":"Let's take a taxi.","ja":"タクシーに乗りましょう。","zh":"我們搭計程車吧。"},{"sortOrder":1,"en":"I called a taxi.","ja":"タクシーを呼びました。","zh":"我叫了計程車。"},{"sortOrder":2,"en":"The taxi is waiting outside.","ja":"タクシーが外で待っています。","zh":"計程車在外面等。"}] },
  { id: "subway", examples: [{"sortOrder":0,"en":"I take the subway every day.","ja":"私は毎日地下鉄に乗ります。","zh":"我每天搭地鐵。"},{"sortOrder":1,"en":"The subway is crowded.","ja":"地下鉄が混んでいます。","zh":"地鐵很擠。"},{"sortOrder":2,"en":"Where is the subway station?","ja":"地下鉄の駅はどこですか？","zh":"地鐵站在哪？"}] },
  { id: "salt", examples: [{"sortOrder":0,"en":"Pass me the salt, please.","ja":"塩を取ってください。","zh":"請把鹽遞給我。"},{"sortOrder":1,"en":"This soup needs more salt.","ja":"このスープにはもう少し塩が必要です。","zh":"這碗湯需要多一點鹽。"},{"sortOrder":2,"en":"Add a pinch of salt to the batter.","ja":"生地に塩を一つまみ加えてください。","zh":"在麵糊裡加一小撮鹽。"}] },
  { id: "sugar", examples: [{"sortOrder":0,"en":"Do you take sugar in your coffee?","ja":"コーヒーに砂糖は入れますか？","zh":"你的咖啡要加糖嗎？"},{"sortOrder":1,"en":"Add a spoon of sugar.","ja":"砂糖を一杯加えてください。","zh":"加一匙糖。"},{"sortOrder":2,"en":"I'm trying to eat less sugar.","ja":"砂糖の摂取を減らそうとしています。","zh":"我正在減少吃糖。"}] },
  { id: "pepper", examples: [{"sortOrder":0,"en":"This dish needs more pepper.","ja":"この料理にはもう少し胡椒が必要です。","zh":"這道菜需要多一點胡椒。"},{"sortOrder":1,"en":"Add salt and pepper to taste.","ja":"塩と胡椒で味を調えてください。","zh":"加鹽和胡椒調味。"},{"sortOrder":2,"en":"He sneezed because of the pepper.","ja":"彼は胡椒のせいでくしゃみをしました。","zh":"他因為胡椒而打了個噴嚏。"}] },
  { id: "black-pepper", examples: [{"sortOrder":0,"en":"Grind some black pepper on top.","ja":"上から黒胡椒を挽いてください。","zh":"在上面磨點黑胡椒。"},{"sortOrder":1,"en":"I prefer black pepper to white pepper.","ja":"白胡椒より黒胡椒のほうが好きです。","zh":"我喜歡黑胡椒勝過白胡椒。"},{"sortOrder":2,"en":"Black pepper goes well with steak.","ja":"黒胡椒はステーキとよく合います。","zh":"黑胡椒和牛排很搭。"}] },
  { id: "white-pepper", examples: [{"sortOrder":0,"en":"White pepper is common in Chinese soups.","ja":"白胡椒は中華スープによく使われます。","zh":"白胡椒在中式湯品裡很常見。"},{"sortOrder":1,"en":"Use white pepper for a milder taste.","ja":"味をまろやかにしたい時は白胡椒を使います。","zh":"想要味道溫和一點就用白胡椒。"},{"sortOrder":2,"en":"Sprinkle white pepper over the noodles.","ja":"麺の上に白胡椒をふりかけます。","zh":"在麵上撒點白胡椒。"}] },
  { id: "soy-sauce", examples: [{"sortOrder":0,"en":"Do you want soy sauce with that?","ja":"醤油は要りますか？","zh":"你要加醬油嗎？"},{"sortOrder":1,"en":"Dip the dumplings in soy sauce.","ja":"餃子を醤油につけてください。","zh":"把餃子沾醬油。"},{"sortOrder":2,"en":"Add a tablespoon of soy sauce.","ja":"醤油を大さじ一杯加えてください。","zh":"加一湯匙醬油。"}] },
  { id: "vinegar", examples: [{"sortOrder":0,"en":"Add a splash of vinegar.","ja":"酢を少し加えてください。","zh":"加一點醋。"},{"sortOrder":1,"en":"Vinegar is used in salad dressing.","ja":"酢はサラダドレッシングによく使われます。","zh":"醋常用在沙拉醬裡。"},{"sortOrder":2,"en":"This sauce is too sour from the vinegar.","ja":"このソースは酢のせいで酸っぱすぎます。","zh":"這醬汁因為醋太酸了。"}] },
  { id: "rice-vinegar", examples: [{"sortOrder":0,"en":"Use rice vinegar for sushi rice.","ja":"寿司飯には米酢を使います。","zh":"做壽司飯要用米醋。"},{"sortOrder":1,"en":"Rice vinegar is milder than grain vinegar.","ja":"米酢は穀物酢よりまろやかです。","zh":"米醋比穀物醋溫和。"},{"sortOrder":2,"en":"Add rice vinegar to the dipping sauce.","ja":"つけだれに米酢を加えます。","zh":"在沾醬裡加米醋。"}] },
  { id: "chili-sauce", examples: [{"sortOrder":0,"en":"I like chili sauce on everything.","ja":"何でもチリソースをかけるのが好きです。","zh":"我什麼東西都愛加辣椒醬。"},{"sortOrder":1,"en":"Sriracha is a popular chili sauce.","ja":"シラチャーは人気のあるチリソースです。","zh":"Sriracha 是很受歡迎的辣椒醬。"},{"sortOrder":2,"en":"This chili sauce is too spicy for me.","ja":"このチリソースは私には辛すぎます。","zh":"這辣椒醬對我來說太辣了。"}] },
  { id: "chili-powder", examples: [{"sortOrder":0,"en":"Add a teaspoon of chili powder.","ja":"チリパウダーを小さじ一杯加えます。","zh":"加一茶匙辣椒粉。"},{"sortOrder":1,"en":"Chili powder makes the dish spicy.","ja":"チリパウダーで料理が辛くなります。","zh":"辣椒粉讓菜變辣。"},{"sortOrder":2,"en":"Sprinkle chili powder over the chicken.","ja":"鶏肉にチリパウダーをふりかけます。","zh":"在雞肉上撒辣椒粉。"}] },
  { id: "chili-flakes", examples: [{"sortOrder":0,"en":"Sprinkle chili flakes on your pizza.","ja":"ピザにクラッシュドチリをふりかけてください。","zh":"在你的披薩上撒辣椒片。"},{"sortOrder":1,"en":"Add chili flakes for extra heat.","ja":"もっと辛くしたい時はクラッシュドチリを加えます。","zh":"想要更辣就加辣椒片。"},{"sortOrder":2,"en":"He keeps chili flakes on the table.","ja":"彼はテーブルにクラッシュドチリを置いています。","zh":"他在桌上放著辣椒片。"}] },
  { id: "mustard", examples: [{"sortOrder":0,"en":"Would you like mustard on your hotdog?","ja":"ホットドッグにマスタードをかけますか？","zh":"熱狗要加芥末嗎？"},{"sortOrder":1,"en":"Spread some mustard on the sandwich.","ja":"サンドイッチにマスタードを少し塗ります。","zh":"在三明治上抹點芥末。"},{"sortOrder":2,"en":"I don't like the taste of mustard.","ja":"マスタードの味が好きではありません。","zh":"我不喜歡芥末的味道。"}] },
  { id: "ketchup", examples: [{"sortOrder":0,"en":"Can I have ketchup with the fries?","ja":"フライドポテトにケチャップをもらえますか？","zh":"薯條可以給我番茄醬嗎？"},{"sortOrder":1,"en":"He puts ketchup on everything.","ja":"彼は何にでもケチャップをかけます。","zh":"他什麼東西都加番茄醬。"},{"sortOrder":2,"en":"The ketchup bottle is almost empty.","ja":"ケチャップの瓶がほとんど空です。","zh":"番茄醬快用完了。"}] },
  { id: "mayonnaise", examples: [{"sortOrder":0,"en":"Spread mayo on the bread.","ja":"パンにマヨネーズを塗ります。","zh":"在麵包上抹美乃滋。"},{"sortOrder":1,"en":"Add mayonnaise to the salad.","ja":"サラダにマヨネーズを加えます。","zh":"在沙拉裡加美乃滋。"},{"sortOrder":2,"en":"I prefer mustard over mayonnaise.","ja":"マヨネーズよりマスタードが好きです。","zh":"我比較喜歡芥末，不愛美乃滋。"}] },
  { id: "oyster-sauce", examples: [{"sortOrder":0,"en":"Add oyster sauce to the stir-fry.","ja":"炒め物にオイスターソースを加えます。","zh":"在炒菜裡加蠔油。"},{"sortOrder":1,"en":"Oyster sauce makes the dish savory.","ja":"オイスターソースで料理が旨味を増します。","zh":"蠔油讓菜餚更鮮甜。"},{"sortOrder":2,"en":"A drizzle of oyster sauce is enough.","ja":"オイスターソースは少しかけるだけで十分です。","zh":"淋一點蠔油就夠了。"}] },
  { id: "fish-sauce", examples: [{"sortOrder":0,"en":"Fish sauce is essential in Thai cooking.","ja":"ナンプラーはタイ料理に欠かせません。","zh":"魚露在泰式料理裡很重要。"},{"sortOrder":1,"en":"Just a few drops of fish sauce is enough.","ja":"ナンプラーは数滴で十分です。","zh":"只要幾滴魚露就夠了。"},{"sortOrder":2,"en":"The smell of fish sauce is strong.","ja":"ナンプラーの匂いはとても強いです。","zh":"魚露的味道很重。"}] },
  { id: "sesame-oil", examples: [{"sortOrder":0,"en":"Drizzle some sesame oil on top.","ja":"上からごま油を少し垂らしてください。","zh":"在上面淋點麻油。"},{"sortOrder":1,"en":"Sesame oil has a strong fragrance.","ja":"ごま油は香りが強いです。","zh":"麻油香氣濃郁。"},{"sortOrder":2,"en":"Use sesame oil for the dipping sauce.","ja":"つけだれにごま油を使います。","zh":"沾醬用麻油。"}] },
  { id: "olive-oil", examples: [{"sortOrder":0,"en":"Cook with olive oil.","ja":"オリーブオイルで料理します。","zh":"用橄欖油料理。"},{"sortOrder":1,"en":"Extra virgin olive oil is the best.","ja":"エクストラバージンオリーブオイルが一番です。","zh":"特級初榨橄欖油是最好的。"},{"sortOrder":2,"en":"Drizzle olive oil over the salad.","ja":"サラダにオリーブオイルをかけます。","zh":"在沙拉上淋橄欖油。"}] },
  { id: "cooking-wine", examples: [{"sortOrder":0,"en":"Add cooking wine to remove the smell.","ja":"臭み消しに料理酒を加えます。","zh":"加料酒去腥。"},{"sortOrder":1,"en":"Use cooking wine, not drinking wine.","ja":"飲む酒ではなく料理酒を使ってください。","zh":"用料酒，不是飲用的酒。"},{"sortOrder":2,"en":"A splash of cooking wine improves the flavor.","ja":"料理酒を少し加えると風味が増します。","zh":"加一點料酒能提升風味。"}] },
  { id: "msg", examples: [{"sortOrder":0,"en":"Some restaurants don't use MSG.","ja":"うま味調味料を使わないレストランもあります。","zh":"有些餐廳不用味精。"},{"sortOrder":1,"en":"MSG enhances the umami flavor.","ja":"うま味調味料はうま味を引き立てます。","zh":"味精能提升鮮味。"},{"sortOrder":2,"en":"She is sensitive to MSG.","ja":"彼女はうま味調味料に敏感です。","zh":"她對味精敏感。"}] },
  { id: "garlic-powder", examples: [{"sortOrder":0,"en":"Sprinkle garlic powder on the meat.","ja":"肉にガーリックパウダーをふりかけます。","zh":"在肉上撒點蒜粉。"},{"sortOrder":1,"en":"Garlic powder is easier than fresh garlic.","ja":"ガーリックパウダーは生のニンニクより手軽です。","zh":"蒜粉比新鮮大蒜方便。"},{"sortOrder":2,"en":"Add a teaspoon of garlic powder.","ja":"ガーリックパウダーを小さじ一杯加えます。","zh":"加一茶匙蒜粉。"}] },
  { id: "onion-powder", examples: [{"sortOrder":0,"en":"Add a pinch of onion powder.","ja":"オニオンパウダーを少し加えます。","zh":"加一點洋蔥粉。"},{"sortOrder":1,"en":"Onion powder is great in dry rubs.","ja":"オニオンパウダーはドライラブによく合います。","zh":"洋蔥粉很適合做乾醃料。"},{"sortOrder":2,"en":"I'm out of onion powder.","ja":"オニオンパウダーを切らしました。","zh":"我的洋蔥粉用完了。"}] },
  { id: "curry-powder", examples: [{"sortOrder":0,"en":"Stir in two spoons of curry powder.","ja":"大さじ二杯のカレー粉を混ぜ入れます。","zh":"拌入兩匙咖哩粉。"},{"sortOrder":1,"en":"Curry powder gives the dish its yellow color.","ja":"カレー粉で料理が黄色くなります。","zh":"咖哩粉讓菜變成黃色。"},{"sortOrder":2,"en":"Indian curry powder is more aromatic.","ja":"インドのカレー粉はもっと香り高いです。","zh":"印度咖哩粉香氣更濃。"}] },
  { id: "five-spice-powder", examples: [{"sortOrder":0,"en":"Five-spice powder is common in Chinese cooking.","ja":"五香粉は中華料理によく使われます。","zh":"五香粉在中式料理裡很常用。"},{"sortOrder":1,"en":"Use a little five-spice powder for flavor.","ja":"風味付けに五香粉を少し使います。","zh":"用一點五香粉提味。"},{"sortOrder":2,"en":"Five-spice powder includes star anise and cinnamon.","ja":"五香粉には八角やシナモンが含まれます。","zh":"五香粉裡有八角和肉桂。"}] },
  { id: "cinnamon", examples: [{"sortOrder":0,"en":"Sprinkle cinnamon on the latte.","ja":"ラテにシナモンをふりかけます。","zh":"在拿鐵上撒肉桂粉。"},{"sortOrder":1,"en":"Cinnamon goes well with apples.","ja":"シナモンはりんごとよく合います。","zh":"肉桂和蘋果很搭。"},{"sortOrder":2,"en":"Add a cinnamon stick to the tea.","ja":"紅茶にシナモンスティックを入れます。","zh":"在茶裡加一根肉桂棒。"}] },
  { id: "cumin", examples: [{"sortOrder":0,"en":"Cumin adds a warm, earthy flavor.","ja":"クミンは温かくて土のような風味を加えます。","zh":"孜然帶來溫暖、土香的風味。"},{"sortOrder":1,"en":"Cumin is essential in chili and curry.","ja":"クミンはチリ料理やカレーには欠かせません。","zh":"孜然在辣椒料理和咖哩裡不可少。"},{"sortOrder":2,"en":"Toast the cumin seeds before grinding.","ja":"クミンシードは挽く前にから煎りします。","zh":"把孜然籽烤過再磨。"}] },
  { id: "cilantro", examples: [{"sortOrder":0,"en":"Garnish with fresh cilantro.","ja":"新鮮なパクチーで飾りつけてください。","zh":"用新鮮香菜裝飾。"},{"sortOrder":1,"en":"Some people hate the taste of cilantro.","ja":"パクチーの味が嫌いな人もいます。","zh":"有些人討厭香菜的味道。"},{"sortOrder":2,"en":"Chop the cilantro finely.","ja":"パクチーを細かく刻んでください。","zh":"把香菜切細。"}] },
  { id: "basil", examples: [{"sortOrder":0,"en":"Top the pizza with fresh basil.","ja":"ピザに新鮮なバジルをのせます。","zh":"披薩上放新鮮羅勒。"},{"sortOrder":1,"en":"Basil is the main herb in pesto.","ja":"バジルはバジルペーストの主役のハーブです。","zh":"羅勒是青醬的主要香草。"},{"sortOrder":2,"en":"Thai basil has a sharper flavor.","ja":"タイバジルはより刺激的な風味があります。","zh":"泰式羅勒（九層塔）味道更強烈。"}] },
  { id: "rosemary", examples: [{"sortOrder":0,"en":"Rosemary goes great with roasted chicken.","ja":"ローズマリーはローストチキンとよく合います。","zh":"迷迭香配烤雞很棒。"},{"sortOrder":1,"en":"Add a sprig of rosemary.","ja":"ローズマリーの小枝を一本加えます。","zh":"加一小枝迷迭香。"},{"sortOrder":2,"en":"Rosemary smells very fragrant.","ja":"ローズマリーはとてもいい香りがします。","zh":"迷迭香聞起來很香。"}] },
  { id: "thyme", examples: [{"sortOrder":0,"en":"Thyme is good for soups and stews.","ja":"タイムはスープや煮込みによく合います。","zh":"百里香適合做湯和燉菜。"},{"sortOrder":1,"en":"Add fresh thyme leaves.","ja":"新鮮なタイムの葉を加えます。","zh":"加新鮮百里香葉。"},{"sortOrder":2,"en":"Dried thyme works in a pinch.","ja":"新鮮なものがない時は乾燥タイムでも代用できます。","zh":"臨時找不到新鮮的，乾百里香也可以。"}] },
  { id: "bay-leaf", examples: [{"sortOrder":0,"en":"Remove the bay leaf before serving.","ja":"盛り付ける前にローリエを取り除いてください。","zh":"上菜前把月桂葉拿出來。"},{"sortOrder":1,"en":"Bay leaves add depth to the broth.","ja":"ローリエはスープに深みを加えます。","zh":"月桂葉讓湯底更有層次。"},{"sortOrder":2,"en":"Drop a bay leaf into the pot.","ja":"鍋にローリエを一枚入れてください。","zh":"在鍋裡丟一片月桂葉。"}] },
  { id: "electric-cooker", examples: [{"sortOrder":0,"en":"I make stew in the slow cooker.","ja":"スロークッカーでシチューを作ります。","zh":"我用慢燉鍋煮燉菜。"}] },
  { id: "rice-cooker", examples: [{"sortOrder":0,"en":"I use the rice cooker in the kitchen.","ja":"私はキッチンで炊飯器を使います。","zh":"我在廚房使用電飯鍋。"}] },
  { id: "freezer", examples: [{"sortOrder":0,"en":"I use the freezer in the kitchen.","ja":"私はキッチンで冷凍庫を使います。","zh":"我在廚房使用冷凍庫。"}] },
  { id: "range-hood", examples: [{"sortOrder":0,"en":"I use the range hood in the kitchen.","ja":"私はキッチンでレンジフードを使います。","zh":"我在廚房使用抽油煙機。"}] },
  { id: "dishwasher", examples: [{"sortOrder":0,"en":"I use the dishwasher in the kitchen.","ja":"私はキッチンで食洗機を使います。","zh":"我在廚房使用洗碗機。"}] },
  { id: "kitchen-knife", examples: [{"sortOrder":0,"en":"I use the kitchen knife in the kitchen.","ja":"私はキッチンで包丁を使います。","zh":"我在廚房使用菜刀。"}] },
  { id: "peeler", examples: [{"sortOrder":0,"en":"I use the peeler in the kitchen.","ja":"私はキッチンでピーラーを使います。","zh":"我在廚房使用削皮器。"}] },
  { id: "grater", examples: [{"sortOrder":0,"en":"I use the grater in the kitchen.","ja":"私はキッチンでおろし器を使います。","zh":"我在廚房使用刨絲器。"}] },
  { id: "can-opener", examples: [{"sortOrder":0,"en":"I use the can opener in the kitchen.","ja":"私はキッチンで缶切りを使います。","zh":"我在廚房使用開罐器。"}] },
  { id: "scissors", examples: [{"sortOrder":0,"en":"I use the scissors in the kitchen.","ja":"私はキッチンではさみを使います。","zh":"我在廚房使用剪刀。"}] },
  { id: "spatula", examples: [{"sortOrder":0,"en":"I use the spatula in the kitchen.","ja":"私はキッチンでフライ返しを使います。","zh":"我在廚房使用鍋鏟。"}] },
  { id: "ladle", examples: [{"sortOrder":0,"en":"I use the ladle in the kitchen.","ja":"私はキッチンでお玉を使います。","zh":"我在廚房使用湯勺。"}] },
  { id: "tongs", examples: [{"sortOrder":0,"en":"I use the tongs in the kitchen.","ja":"私はキッチンでトングを使います。","zh":"我在廚房使用夾子。"}] },
  { id: "whisk", examples: [{"sortOrder":0,"en":"I use the whisk in the kitchen.","ja":"私はキッチンで泡立て器を使います。","zh":"我在廚房使用打蛋器。"}] },
  { id: "measuring-cup", examples: [{"sortOrder":0,"en":"I use the measuring cup in the kitchen.","ja":"私はキッチンで計量カップを使います。","zh":"我在廚房使用量杯。"}] },
  { id: "measuring-spoon", examples: [{"sortOrder":0,"en":"I use the measuring spoon in the kitchen.","ja":"私はキッチンで計量スプーンを使います。","zh":"我在廚房使用量匙。"}] },
  { id: "strainer", examples: [{"sortOrder":0,"en":"I use the strainer in the kitchen.","ja":"私はキッチンでザルを使います。","zh":"我在廚房使用濾網。"}] },
  { id: "slotted-spoon", examples: [{"sortOrder":0,"en":"I use the slotted spoon in the kitchen.","ja":"私はキッチンで穴あきお玉を使います。","zh":"我在廚房使用漏勺。"}] },
  { id: "glass", examples: [{"sortOrder":0,"en":"I use the glass in the kitchen.","ja":"私はキッチンでコップを使います。","zh":"我在廚房使用玻璃杯。"}] },
  { id: "fork", examples: [{"sortOrder":0,"en":"I use the fork in the kitchen.","ja":"私はキッチンでフォークを使います。","zh":"我在廚房使用叉子。"}] },
  { id: "table-knife", examples: [{"sortOrder":0,"en":"I use the table knife in the kitchen.","ja":"私はキッチンでテーブルナイフを使います。","zh":"我在廚房使用餐刀。"}] },
  { id: "wok", examples: [{"sortOrder":0,"en":"I use the wok in the kitchen.","ja":"私はキッチンで中華鍋を使います。","zh":"我在廚房使用炒鍋。"}] },
  { id: "lid", examples: [{"sortOrder":0,"en":"I use the lid in the kitchen.","ja":"私はキッチンで蓋を使います。","zh":"我在廚房使用鍋蓋。"}] },
  { id: "steamer-basket", examples: [{"sortOrder":0,"en":"I use the steamer basket in the kitchen.","ja":"私はキッチンで蒸し器を使います。","zh":"我在廚房使用蒸籠。"}] },
  { id: "teapot", examples: [{"sortOrder":0,"en":"I use the teapot in the kitchen.","ja":"私はキッチンでティーポットを使います。","zh":"我在廚房使用茶壺。"}] },
  { id: "kettle", examples: [{"sortOrder":0,"en":"I use the kettle in the kitchen.","ja":"私はキッチンでやかんを使います。","zh":"我在廚房使用水壺。"}] },
  { id: "coffee-maker", examples: [{"sortOrder":0,"en":"I use the coffee maker in the kitchen.","ja":"私はキッチンでコーヒーメーカーを使います。","zh":"我在廚房使用咖啡機。"}] },
  { id: "toaster", examples: [{"sortOrder":0,"en":"I use the toaster in the kitchen.","ja":"私はキッチンでトースターを使います。","zh":"我在廚房使用烤麵包機。"}] },
  { id: "blender", examples: [{"sortOrder":0,"en":"I use the blender in the kitchen.","ja":"私はキッチンでブレンダーを使います。","zh":"我在廚房使用果汁機。"}] },
  { id: "food-processor", examples: [{"sortOrder":0,"en":"I use the food processor in the kitchen.","ja":"私はキッチンでフードプロセッサーを使います。","zh":"我在廚房使用食物調理機。"}] },
  { id: "air-fryer", examples: [{"sortOrder":0,"en":"I use the air fryer in the kitchen.","ja":"私はキッチンでエアフライヤーを使います。","zh":"我在廚房使用氣炸鍋。"}] },
  { id: "dish-soap", examples: [{"sortOrder":0,"en":"I use the dish soap in the kitchen.","ja":"私はキッチンで食器用洗剤を使います。","zh":"我在廚房使用洗碗精。"}] },
  { id: "sponge", examples: [{"sortOrder":0,"en":"I use the sponge in the kitchen.","ja":"私はキッチンでスポンジを使います。","zh":"我在廚房使用海綿。"}] },
  { id: "cloth", examples: [{"sortOrder":0,"en":"I use the cloth in the kitchen.","ja":"私はキッチンでふきんを使います。","zh":"我在廚房使用抹布。"}] },
  { id: "paper-towel", examples: [{"sortOrder":0,"en":"I use the paper towel in the kitchen.","ja":"私はキッチンでキッチンペーパーを使います。","zh":"我在廚房使用廚房紙巾。"}] },
  { id: "trash-bag", examples: [{"sortOrder":0,"en":"I use the trash bag in the kitchen.","ja":"私はキッチンでゴミ袋を使います。","zh":"我在廚房使用垃圾袋。"}] },
  { id: "plastic-wrap", examples: [{"sortOrder":0,"en":"I use the plastic wrap in the kitchen.","ja":"私はキッチンでラップを使います。","zh":"我在廚房使用保鮮膜。"}] },
  { id: "aluminum-foil", examples: [{"sortOrder":0,"en":"I use the aluminum foil in the kitchen.","ja":"私はキッチンでアルミホイルを使います。","zh":"我在廚房使用鋁箔紙。"}] },
  { id: "food-container", examples: [{"sortOrder":0,"en":"I use the food container in the kitchen.","ja":"私はキッチンで保存容器を使います。","zh":"我在廚房使用保鮮盒。"}] },
  { id: "seasoning-jar", examples: [{"sortOrder":0,"en":"I use the seasoning jar in the kitchen.","ja":"私はキッチンで調味料入れを使います。","zh":"我在廚房使用調味罐。"}] },
  { id: "toilet-seat", examples: [{"sortOrder":0,"en":"The toilet seat is in the bathroom.","ja":"便座はバスルームにあります。","zh":"馬桶座圈在浴室裡。"}] },
  { id: "toilet-tank", examples: [{"sortOrder":0,"en":"The toilet tank is in the bathroom.","ja":"トイレタンクはバスルームにあります。","zh":"馬桶水箱在浴室裡。"}] },
  { id: "toilet-paper", examples: [{"sortOrder":0,"en":"The toilet paper is in the bathroom.","ja":"トイレットペーパーはバスルームにあります。","zh":"衛生紙在浴室裡。"}] },
  { id: "tissue", examples: [{"sortOrder":0,"en":"The tissue is in the bathroom.","ja":"ティッシュはバスルームにあります。","zh":"面紙在浴室裡。"}] },
  { id: "washbasin", examples: [{"sortOrder":0,"en":"The washbasin is in the bathroom.","ja":"洗面台はバスルームにあります。","zh":"洗手台在浴室裡。"}] },
  { id: "drain", examples: [{"sortOrder":0,"en":"The drain is in the bathroom.","ja":"排水口はバスルームにあります。","zh":"排水孔在浴室裡。"}] },
  { id: "bathroom-cabinet", examples: [{"sortOrder":0,"en":"The bathroom cabinet is in the bathroom.","ja":"洗面所の収納棚はバスルームにあります。","zh":"浴櫃在浴室裡。"}] },
  { id: "towel-rack", examples: [{"sortOrder":0,"en":"The towel rack is in the bathroom.","ja":"タオル掛けはバスルームにあります。","zh":"毛巾架在浴室裡。"}] },
  { id: "hook", examples: [{"sortOrder":0,"en":"The hook is in the bathroom.","ja":"フックはバスルームにあります。","zh":"掛鉤在浴室裡。"}] },
  { id: "bathtub", examples: [{"sortOrder":0,"en":"The bathtub is in the bathroom.","ja":"バスタブはバスルームにあります。","zh":"浴缸在浴室裡。"}] },
  { id: "shower-room", examples: [{"sortOrder":0,"en":"The shower room is in the bathroom.","ja":"シャワールームはバスルームにあります。","zh":"淋浴間在浴室裡。"}] },
  { id: "shower-head", examples: [{"sortOrder":0,"en":"The shower head is in the bathroom.","ja":"シャワーヘッドはバスルームにあります。","zh":"蓮蓬頭在浴室裡。"}] },
  { id: "shower-curtain", examples: [{"sortOrder":0,"en":"The shower curtain is in the bathroom.","ja":"シャワーカーテンはバスルームにあります。","zh":"浴簾在浴室裡。"}] },
  { id: "shower-curtain-rod", examples: [{"sortOrder":0,"en":"The shower curtain rod is in the bathroom.","ja":"シャワーカーテンポールはバスルームにあります。","zh":"浴簾桿在浴室裡。"}] },
  { id: "bathroom-door", examples: [{"sortOrder":0,"en":"The bathroom door is in the bathroom.","ja":"浴室のドアはバスルームにあります。","zh":"浴室門在浴室裡。"}] },
  { id: "bath-mat", examples: [{"sortOrder":0,"en":"The bath mat is in the bathroom.","ja":"バスマットはバスルームにあります。","zh":"地墊在浴室裡。"}] },
  { id: "non-slip-mat", examples: [{"sortOrder":0,"en":"The non-slip mat is in the bathroom.","ja":"滑り止めマットはバスルームにあります。","zh":"防滑墊在浴室裡。"}] },
  { id: "bath-towel", examples: [{"sortOrder":0,"en":"The bath towel is in the bathroom.","ja":"バスタオルはバスルームにあります。","zh":"浴巾在浴室裡。"}] },
  { id: "hand-towel", examples: [{"sortOrder":0,"en":"The hand towel is in the bathroom.","ja":"ハンドタオルはバスルームにあります。","zh":"手巾在浴室裡。"}] },
  { id: "dental-floss", examples: [{"sortOrder":0,"en":"The dental floss is in the bathroom.","ja":"デンタルフロスはバスルームにあります。","zh":"牙線在浴室裡。"}] },
  { id: "mouthwash", examples: [{"sortOrder":0,"en":"The mouthwash is in the bathroom.","ja":"マウスウォッシュはバスルームにあります。","zh":"漱口水在浴室裡。"}] },
  { id: "facial-cleanser", examples: [{"sortOrder":0,"en":"The facial cleanser is in the bathroom.","ja":"洗顔料はバスルームにあります。","zh":"洗面乳在浴室裡。"}] },
  { id: "body-wash", examples: [{"sortOrder":0,"en":"The body wash is in the bathroom.","ja":"ボディソープはバスルームにあります。","zh":"沐浴乳在浴室裡。"}] },
  { id: "conditioner", examples: [{"sortOrder":0,"en":"The conditioner is in the bathroom.","ja":"コンディショナーはバスルームにあります。","zh":"潤髮乳在浴室裡。"}] },
  { id: "hair-conditioner", examples: [{"sortOrder":0,"en":"The hair conditioner is in the bathroom.","ja":"ヘアコンディショナーはバスルームにあります。","zh":"護髮素在浴室裡。"}] },
  { id: "razor", examples: [{"sortOrder":0,"en":"The razor is in the bathroom.","ja":"カミソリはバスルームにあります。","zh":"刮鬍刀在浴室裡。"}] },
  { id: "shaving-cream", examples: [{"sortOrder":0,"en":"The shaving cream is in the bathroom.","ja":"シェービングクリームはバスルームにあります。","zh":"刮鬍泡在浴室裡。"}] },
  { id: "hairbrush", examples: [{"sortOrder":0,"en":"The hairbrush is in the bathroom.","ja":"ヘアブラシはバスルームにあります。","zh":"髮刷在浴室裡。"}] },
  { id: "cotton-swab", examples: [{"sortOrder":0,"en":"The cotton swab is in the bathroom.","ja":"綿棒はバスルームにあります。","zh":"棉花棒在浴室裡。"}] },
  { id: "cotton-pad", examples: [{"sortOrder":0,"en":"The cotton pad is in the bathroom.","ja":"化粧用コットンはバスルームにあります。","zh":"化妝棉在浴室裡。"}] },
  { id: "cotton-ball", examples: [{"sortOrder":0,"en":"The cotton ball is in the bathroom.","ja":"コットンボールはバスルームにあります。","zh":"棉球在浴室裡。"}] },
  { id: "nail-clipper", examples: [{"sortOrder":0,"en":"The nail clipper is in the bathroom.","ja":"爪切りはバスルームにあります。","zh":"指甲剪在浴室裡。"}] },
  { id: "laundry-basket", examples: [{"sortOrder":0,"en":"The laundry basket is in the bathroom.","ja":"ランドリーバスケットはバスルームにあります。","zh":"洗衣籃在浴室裡。"}] },
  { id: "hamper", examples: [{"sortOrder":0,"en":"The hamper is in the bathroom.","ja":"洗濯かごはバスルームにあります。","zh":"髒衣籃在浴室裡。"}] },
  { id: "cleaning-brush", examples: [{"sortOrder":0,"en":"The cleaning brush is in the bathroom.","ja":"掃除ブラシはバスルームにあります。","zh":"清潔刷在浴室裡。"}] },
  { id: "toilet-brush", examples: [{"sortOrder":0,"en":"The toilet brush is in the bathroom.","ja":"トイレブラシはバスルームにあります。","zh":"馬桶刷在浴室裡。"}] },
  { id: "cleaner", examples: [{"sortOrder":0,"en":"The cleaner is in the bathroom.","ja":"洗剤はバスルームにあります。","zh":"清潔劑在浴室裡。"}] },
  { id: "disinfectant", examples: [{"sortOrder":0,"en":"The disinfectant is in the bathroom.","ja":"消毒液はバスルームにあります。","zh":"消毒液在浴室裡。"}] },
  { id: "mold-remover", examples: [{"sortOrder":0,"en":"The mold remover is in the bathroom.","ja":"カビ取り剤はバスルームにあります。","zh":"除霉劑在浴室裡。"}] },
  { id: "bathroom-cleaner", examples: [{"sortOrder":0,"en":"The bathroom cleaner is in the bathroom.","ja":"浴室用洗剤はバスルームにあります。","zh":"浴室清潔劑在浴室裡。"}] },
  { id: "bucket", examples: [{"sortOrder":0,"en":"The bucket is in the bathroom.","ja":"バケツはバスルームにあります。","zh":"水桶在浴室裡。"}] },
  { id: "wash-basin", examples: [{"sortOrder":0,"en":"The wash basin is in the bathroom.","ja":"洗面器はバスルームにあります。","zh":"臉盆在浴室裡。"}] },
  { id: "gloves", examples: [{"sortOrder":0,"en":"The gloves is in the bathroom.","ja":"手袋はバスルームにあります。","zh":"手套在浴室裡。"}] },
  { id: "hand-soap", examples: [{"sortOrder":0,"en":"The hand soap is in the bathroom.","ja":"ハンドソープはバスルームにあります。","zh":"洗手乳在浴室裡。"}] },
  { id: "lotion", examples: [{"sortOrder":0,"en":"The lotion is in the bathroom.","ja":"ボディローションはバスルームにあります。","zh":"乳液在浴室裡。"}] },
  { id: "moisturizer", examples: [{"sortOrder":0,"en":"The moisturizer is in the bathroom.","ja":"保湿クリームはバスルームにあります。","zh":"保濕乳在浴室裡。"}] },
  { id: "cosmetics", examples: [{"sortOrder":0,"en":"The cosmetics is in the bathroom.","ja":"化粧品はバスルームにあります。","zh":"化妝品在浴室裡。"}] },
  { id: "cleansing-oil", examples: [{"sortOrder":0,"en":"The cleansing oil is in the bathroom.","ja":"クレンジングオイルはバスルームにあります。","zh":"卸妝油在浴室裡。"}] },
  { id: "micellar-water", examples: [{"sortOrder":0,"en":"The micellar water is in the bathroom.","ja":"クレンジングウォーターはバスルームにあります。","zh":"卸妝水在浴室裡。"}] },
  { id: "perfume", examples: [{"sortOrder":0,"en":"The perfume is in the bathroom.","ja":"香水はバスルームにあります。","zh":"香水在浴室裡。"}] },
  { id: "deodorant", examples: [{"sortOrder":0,"en":"The deodorant is in the bathroom.","ja":"デオドラントはバスルームにあります。","zh":"體香劑在浴室裡。"}] },
  { id: "scale", examples: [{"sortOrder":0,"en":"The scale is in the bathroom.","ja":"体重計はバスルームにあります。","zh":"體重計在浴室裡。"}] },
  { id: "bathrobe", examples: [{"sortOrder":0,"en":"The bathrobe is in the bathroom.","ja":"バスローブはバスルームにあります。","zh":"浴袍在浴室裡。"}] },
  { id: "slippers", examples: [{"sortOrder":0,"en":"The slippers is in the bathroom.","ja":"スリッパはバスルームにあります。","zh":"拖鞋在浴室裡。"}] },
  { id: "ventilation-fan", examples: [{"sortOrder":0,"en":"The ventilation fan is in the bathroom.","ja":"換気扇はバスルームにあります。","zh":"排風扇在浴室裡。"}] },
  { id: "water-heater", examples: [{"sortOrder":0,"en":"The water heater is in the bathroom.","ja":"給湯器はバスルームにあります。","zh":"熱水器在浴室裡。"}] },
  { id: "sanitary-pad", examples: [{"sortOrder":0,"en":"The sanitary pad is in the bathroom.","ja":"生理用ナプキンはバスルームにあります。","zh":"衛生棉在浴室裡。"}] },
  { id: "tampon", examples: [{"sortOrder":0,"en":"The tampon is in the bathroom.","ja":"タンポンはバスルームにあります。","zh":"衛生棉條在浴室裡。"}] },
  { id: "squeegee", examples: [{"sortOrder":0,"en":"The squeegee is in the bathroom.","ja":"スクイージーはバスルームにあります。","zh":"刮水器在浴室裡。"}] },
  { id: "bath-salts", examples: [{"sortOrder":0,"en":"The bath salts is in the bathroom.","ja":"バスソルトはバスルームにあります。","zh":"浴鹽在浴室裡。"}] },
  { id: "bath-sponge", examples: [{"sortOrder":0,"en":"The bath sponge is in the bathroom.","ja":"バススポンジはバスルームにあります。","zh":"洗澡海綿在浴室裡。"}] },
  { id: "mattress", examples: [{"sortOrder":0,"en":"The mattress is in the bedroom.","ja":"マットレスは寝室にあります。","zh":"床墊在臥室裡。"}] },
  { id: "pillowcase", examples: [{"sortOrder":0,"en":"The pillowcase is in the bedroom.","ja":"枕カバーは寝室にあります。","zh":"枕套在臥室裡。"}] },
  { id: "quilt", examples: [{"sortOrder":0,"en":"The quilt is in the bedroom.","ja":"掛け布団は寝室にあります。","zh":"棉被在臥室裡。"}] },
  { id: "bed-sheet", examples: [{"sortOrder":0,"en":"The bed sheet is in the bedroom.","ja":"シーツは寝室にあります。","zh":"床單在臥室裡。"}] },
  { id: "bedspread", examples: [{"sortOrder":0,"en":"The bedspread is in the bedroom.","ja":"ベッドカバーは寝室にあります。","zh":"床罩在臥室裡。"}] },
  { id: "headboard", examples: [{"sortOrder":0,"en":"The headboard is in the bedroom.","ja":"ヘッドボードは寝室にあります。","zh":"床頭板在臥室裡。"}] },
  { id: "nightstand", examples: [{"sortOrder":0,"en":"The nightstand is in the bedroom.","ja":"ベッドサイドテーブルは寝室にあります。","zh":"床頭櫃在臥室裡。"}] },
  { id: "hanger", examples: [{"sortOrder":0,"en":"The hanger is in the bedroom.","ja":"ハンガーは寝室にあります。","zh":"衣架在臥室裡。"}] },
  { id: "drawer", examples: [{"sortOrder":0,"en":"The drawer is in the bedroom.","ja":"引き出しは寝室にあります。","zh":"抽屜在臥室裡。"}] },
  { id: "vanity-table", examples: [{"sortOrder":0,"en":"The vanity table is in the bedroom.","ja":"ドレッサーは寝室にあります。","zh":"梳妝台在臥室裡。"}] },
  { id: "chair", examples: [{"sortOrder":0,"en":"The chair is in the bedroom.","ja":"椅子は寝室にあります。","zh":"椅子在臥室裡。"}] },
  { id: "desk-lamp", examples: [{"sortOrder":0,"en":"The desk lamp is in the bedroom.","ja":"デスクランプは寝室にあります。","zh":"檯燈在臥室裡。"}] },
  { id: "bedside-lamp", examples: [{"sortOrder":0,"en":"The bedside lamp is in the bedroom.","ja":"ベッドサイドランプは寝室にあります。","zh":"床頭燈在臥室裡。"}] },
  { id: "blinds", examples: [{"sortOrder":0,"en":"The blinds is in the bedroom.","ja":"ブラインドは寝室にあります。","zh":"百葉窗在臥室裡。"}] },
  { id: "pajamas", examples: [{"sortOrder":0,"en":"The pajamas is in the bedroom.","ja":"パジャマは寝室にあります。","zh":"睡衣在臥室裡。"}] },
  { id: "robe", examples: [{"sortOrder":0,"en":"The robe is in the bedroom.","ja":"ローブは寝室にあります。","zh":"睡袍在臥室裡。"}] },
  { id: "storage-box", examples: [{"sortOrder":0,"en":"The storage box is in the bedroom.","ja":"収納ボックスは寝室にあります。","zh":"收納盒在臥室裡。"}] },
  { id: "bookshelf", examples: [{"sortOrder":0,"en":"The bookshelf is in the bedroom.","ja":"本棚は寝室にあります。","zh":"書架在臥室裡。"}] },
  { id: "air-conditioner", examples: [{"sortOrder":0,"en":"The air conditioner is in the bedroom.","ja":"エアコンは寝室にあります。","zh":"空調在臥室裡。"}] },
  { id: "fan", examples: [{"sortOrder":0,"en":"The fan is in the bedroom.","ja":"扇風機は寝室にあります。","zh":"電風扇在臥室裡。"}] },
  { id: "heater", examples: [{"sortOrder":0,"en":"The heater is in the bedroom.","ja":"ヒーターは寝室にあります。","zh":"暖氣在臥室裡。"}] },
  { id: "humidifier", examples: [{"sortOrder":0,"en":"The humidifier is in the bedroom.","ja":"加湿器は寝室にあります。","zh":"加濕器在臥室裡。"}] },
  { id: "air-purifier", examples: [{"sortOrder":0,"en":"The air purifier is in the bedroom.","ja":"空気清浄機は寝室にあります。","zh":"空氣清淨機在臥室裡。"}] },
  { id: "door", examples: [{"sortOrder":0,"en":"The door is in the bedroom.","ja":"ドアは寝室にあります。","zh":"門在臥室裡。"}] },
  { id: "window", examples: [{"sortOrder":0,"en":"The window is in the bedroom.","ja":"窓は寝室にあります。","zh":"窗戶在臥室裡。"}] },
  { id: "clothes", examples: [{"sortOrder":0,"en":"The clothes is in the bedroom.","ja":"服は寝室にあります。","zh":"衣服在臥室裡。"}] },
  { id: "photo-frame", examples: [{"sortOrder":0,"en":"The photo frame is in the bedroom.","ja":"写真立ては寝室にあります。","zh":"相框在臥室裡。"}] },
  { id: "armchair", examples: [{"sortOrder":0,"en":"This armchair is comfortable for reading.","ja":"このアームチェアは読書をするときに座りやすいです。","zh":"這張扶手椅很適合坐著看書。"}] },
  { id: "tv-stand", examples: [{"sortOrder":0,"en":"The game console is on the shelf in the TV stand.","ja":"ゲーム機はテレビ台の棚に置いてあります。","zh":"遊戲機放在電視櫃的層架上。"}] },
  { id: "cushion", examples: [{"sortOrder":0,"en":"Put a cushion on the sofa.","ja":"ソファにクッションを置いてください。","zh":"請在沙發上放一個抱枕。"}] },
  { id: "floor-lamp", examples: [{"sortOrder":0,"en":"I turn on the floor lamp when I read.","ja":"本を読むときはフロアランプをつけます。","zh":"看書時我會打開落地燈。"}] },
  { id: "table-lamp", examples: [{"sortOrder":0,"en":"Turn off the table lamp before going to bed.","ja":"寝る前にテーブルランプを消してください。","zh":"睡前請關掉檯燈。"}] },
  { id: "ceiling-light", examples: [{"sortOrder":0,"en":"Please turn on the ceiling light.","ja":"シーリングライトをつけてください。","zh":"請打開吸頂燈。"}] },
  { id: "display-cabinet", examples: [{"sortOrder":0,"en":"The cups are displayed in the display cabinet.","ja":"飾り棚にカップを並べています。","zh":"杯子陳列在展示櫃裡。"}] },
  { id: "wall-art", examples: [{"sortOrder":0,"en":"We hung new wall art above the sofa.","ja":"ソファの上に新しい壁飾りを掛けました。","zh":"我們在沙發上方掛了新的牆面藝術。"}] },
  { id: "vase", examples: [{"sortOrder":0,"en":"Put these flowers in the vase.","ja":"この花を花瓶に生けてください。","zh":"請把這些花插進花瓶裡。"}] },
  { id: "potted-plant", examples: [{"sortOrder":0,"en":"Water the potted plant by the window.","ja":"窓辺の鉢植えに水をやってください。","zh":"請幫窗邊的盆栽澆水。"}] },
  { id: "dehumidifier", examples: [{"sortOrder":0,"en":"I turn on the dehumidifier on humid days.","ja":"湿気の多い日は除湿機をつけます。","zh":"潮濕的日子我會開除濕機。"}] },
  { id: "power-outlet", examples: [{"sortOrder":0,"en":"Plug the lamp into this power outlet.","ja":"このコンセントにランプのプラグを差してください。","zh":"請把燈的插頭插進這個插座。"}] },
  { id: "extension-cord", examples: [{"sortOrder":0,"en":"The cord does not reach, so use this extension cord.","ja":"コードが届かないので、この延長コードを使ってください。","zh":"電線不夠長，請用這條延長線。"}] },
  { id: "charger", examples: [{"sortOrder":0,"en":"I left my phone charger by the sofa.","ja":"スマートフォンの充電器をソファのそばに置きました。","zh":"我把手機充電器放在沙發旁。"}] },
  { id: "speaker", examples: [{"sortOrder":0,"en":"Connect your phone to the speaker.","ja":"スマートフォンをスピーカーに接続してください。","zh":"請把手機連接到喇叭。"}] },
  { id: "game-console", examples: [{"sortOrder":0,"en":"I connected the game console to the TV.","ja":"ゲーム機をテレビにつなぎました。","zh":"我把遊戲機接到電視上。"}] },
  { id: "router", examples: [{"sortOrder":0,"en":"Restart the router if the internet stops working.","ja":"インターネットにつながらないときは、ルーターを再起動してください。","zh":"網路連不上時，請重新啟動路由器。"}] },
  { id: "telephone", examples: [{"sortOrder":0,"en":"The telephone is ringing.","ja":"電話が鳴っています。","zh":"電話在響。"}] },
  { id: "doorbell", examples: [{"sortOrder":0,"en":"The video doorbell rang, so I checked the monitor.","ja":"テレビドアホンが鳴ったので、モニターを確認しました。","zh":"視訊門鈴響了，所以我查看螢幕。"}] },
  { id: "doormat", examples: [{"sortOrder":0,"en":"Wipe your shoes on the doormat before coming in.","ja":"入る前に玄関マットで靴の裏を拭いてください。","zh":"進門前請在玄關墊上擦鞋底。"}] },
  { id: "cabinet", examples: [{"sortOrder":0,"en":"The board games are stored in the cabinet.","ja":"ボードゲームはキャビネットにしまってあります。","zh":"桌遊收在櫃子裡。"}] },
  { id: "back-cushion", examples: [{"sortOrder":0,"en":"Put a back cushion behind your lower back.","ja":"腰の後ろに背もたれクッションを置いてください。","zh":"請把靠墊放在腰後面。"}] },
  { id: "footstool", examples: [{"sortOrder":0,"en":"Rest your feet on the footstool.","ja":"足置きに足を乗せてください。","zh":"請把腳放在腳凳上。"}] },
  { id: "recliner", examples: [{"sortOrder":0,"en":"Lean back in the recliner and relax.","ja":"リクライニングチェアの背もたれを倒して休みます。","zh":"把躺椅椅背往後放，休息一下。"}] },
  { id: "side-table", examples: [{"sortOrder":0,"en":"Put your drink on the side table.","ja":"飲み物はサイドテーブルに置いてください。","zh":"飲料請放在邊桌上。"}] },
  { id: "magazine", examples: [{"sortOrder":0,"en":"I read this magazine on the sofa.","ja":"ソファでこの雑誌を読みました。","zh":"我在沙發上看這本雜誌。"}] },
  { id: "newspaper", examples: [{"sortOrder":0,"en":"My father reads the newspaper every morning.","ja":"父は毎朝、新聞を読みます。","zh":"爸爸每天早上看報紙。"}] },
  { id: "candle", examples: [{"sortOrder":0,"en":"Light the candle after dinner.","ja":"夕食後にろうそくに火をつけます。","zh":"晚餐後點蠟燭。"}] },
  { id: "diffuser", examples: [{"sortOrder":0,"en":"I put a reed diffuser on the shelf.","ja":"棚にリードディフューザーを置きました。","zh":"我把擴香瓶放在架子上。"}] },
  { id: "smoke-detector", examples: [{"sortOrder":0,"en":"Test the smoke detector once a month.","ja":"月に一度、煙式火災警報器が鳴るか確認します。","zh":"每月確認一次煙霧警報器是否會響。"}] },
  { id: "remote-control-holder", examples: [{"sortOrder":0,"en":"Put the remote back in the remote control holder.","ja":"リモコンをリモコンホルダーに戻してください。","zh":"請把遙控器放回收納盒。"}] },
  { id: "set-top-box", examples: [{"sortOrder":0,"en":"Connect the set-top box to the TV with an HDMI cable.","ja":"セットトップボックスをHDMIケーブルでテレビにつなぎます。","zh":"用 HDMI 線把電視盒接到電視。"}] },
  { id: "projector", examples: [{"sortOrder":0,"en":"We project movies onto the screen.","ja":"プロジェクターで映画をスクリーンに映します。","zh":"我們用投影機把電影投在布幕上。"}] },
  { id: "projector-screen", examples: [{"sortOrder":0,"en":"Pull down the projector screen before the movie.","ja":"映画を見る前にプロジェクタースクリーンを下ろします。","zh":"看電影前先把投影幕拉下來。"}] },
  { id: "robot-vacuum", examples: [{"sortOrder":0,"en":"The robot vacuum cleans while I am out.","ja":"外出中にロボット掃除機が床を掃除します。","zh":"我外出時，掃地機器人會清掃地板。"}] },
  { id: "office-chair", examples: [{"sortOrder":0,"en":"This office chair is height-adjustable.","ja":"このオフィスチェアは高さを調節できます。","zh":"這張辦公椅可以調整高度。"}] },
  { id: "computer", examples: [{"sortOrder":0,"en":"Please restart the computer.","ja":"パソコンを再起動してください。","zh":"請重新啟動電腦。"}] },
  { id: "mouse-pad", examples: [{"sortOrder":0,"en":"My mouse moves better on this mouse pad.","ja":"このマウスパッドだと、マウスがスムーズに動きます。","zh":"滑鼠放在這張滑鼠墊上比較順。"}] },
  { id: "photocopier", examples: [{"sortOrder":0,"en":"The photocopier is jammed.","ja":"コピー機で紙が詰まりました。","zh":"影印機卡紙了。"}] },
  { id: "scanner", examples: [{"sortOrder":0,"en":"Scan both sides of the document.","ja":"書類の両面をスキャンしてください。","zh":"請掃描文件的正反兩面。"}] },
  { id: "mobile-phone", examples: [{"sortOrder":0,"en":"Please put your smartphone on silent mode.","ja":"スマートフォンをマナーモードにしてください。","zh":"請把手機調成靜音模式。"}] },
  { id: "headphones", examples: [{"sortOrder":0,"en":"I wear headphones during online meetings.","ja":"オンライン会議ではヘッドホンを使います。","zh":"我開線上會議時會戴頭戴式耳機。"}] },
  { id: "microphone", examples: [{"sortOrder":0,"en":"Please speak closer to the microphone.","ja":"もう少しマイクに近づいて話してください。","zh":"請靠近麥克風說話。"}] },
  { id: "webcam", examples: [{"sortOrder":0,"en":"The webcam isn't working.","ja":"ウェブカメラが映りません。","zh":"網路攝影機沒有反應。"}] },
  { id: "whiteboard", examples: [{"sortOrder":0,"en":"The schedule is written on the whiteboard.","ja":"予定はホワイトボードに書いてあります。","zh":"行程寫在白板上。"}] },
  { id: "whiteboard-marker", examples: [{"sortOrder":0,"en":"This whiteboard marker is running dry.","ja":"このホワイトボードマーカーはインクが薄くなっています。","zh":"這支白板筆快沒水了。"}] },
  { id: "eraser", examples: [{"sortOrder":0,"en":"Please erase the whiteboard after the meeting.","ja":"会議のあと、ホワイトボード用イレーザーで消してください。","zh":"會議結束後請把白板擦乾淨。"}] },
  { id: "sticky-notes", examples: [{"sortOrder":0,"en":"Leave a sticky note on my monitor.","ja":"モニターに付箋を貼っておいてください。","zh":"請在我的螢幕上貼一張便利貼。"}] },
  { id: "ballpoint-pen", examples: [{"sortOrder":0,"en":"Please fill out this form with a black ballpoint pen.","ja":"この用紙は黒いボールペンで記入してください。","zh":"請用黑色原子筆填寫這張表格。"}] },
  { id: "highlighter", examples: [{"sortOrder":0,"en":"Highlight the important parts in yellow.","ja":"大事なところに黄色い蛍光ペンで線を引いてください。","zh":"請用黃色螢光筆標出重點。"}] },
  { id: "marker", examples: [{"sortOrder":0,"en":"Write the address on the box with a permanent marker.","ja":"箱に油性マーカーで宛名を書いてください。","zh":"請用油性筆在箱子上寫地址。"}] },
  { id: "ruler", examples: [{"sortOrder":0,"en":"Draw a straight line with a ruler.","ja":"定規でまっすぐな線を引いてください。","zh":"用尺畫一條直線。"}] },
  { id: "utility-knife", examples: [{"sortOrder":0,"en":"Cut the cardboard with a utility knife.","ja":"カッターナイフで段ボールを切ります。","zh":"用美工刀裁開紙箱。"}] },
  { id: "tape", examples: [{"sortOrder":0,"en":"I repaired the torn paper with tape.","ja":"破れた紙をセロテープで直しました。","zh":"我用透明膠帶把破掉的紙黏好。"}] },
  { id: "glue", examples: [{"sortOrder":0,"en":"Can I borrow the glue?","ja":"のりを貸してもらえますか？","zh":"可以借我膠水嗎？"}] },
  { id: "staples", examples: [{"sortOrder":0,"en":"We're out of staples.","ja":"ホチキスの針がなくなりました。","zh":"訂書針用完了。"}] },
  { id: "paper-clip", examples: [{"sortOrder":0,"en":"Fasten these pages with a paper clip.","ja":"この書類はゼムクリップで留めてください。","zh":"請用迴紋針夾住這幾張紙。"}] },
  { id: "binder-clip", examples: [{"sortOrder":0,"en":"Use a binder clip to hold these documents together.","ja":"この書類はダブルクリップでまとめてください。","zh":"用長尾夾把這些文件夾在一起。"}] },
  { id: "folder", examples: [{"sortOrder":0,"en":"Keep the handout in this clear file folder.","ja":"配布資料はこのクリアファイルに入れてください。","zh":"請把講義放進這個透明資料夾。"}] },
  { id: "file-folder", examples: [{"sortOrder":0,"en":"I sorted the invoices into separate file folders.","ja":"請求書を個別フォルダーに分けて入れました。","zh":"我把請款單分別放進檔案夾。"}] },
  { id: "document", examples: [{"sortOrder":0,"en":"Please send me the document by email.","ja":"書類をメールで送ってください。","zh":"請用電子郵件把文件寄給我。"}] },
  { id: "paper", examples: [{"sortOrder":0,"en":"Please load more paper into the printer.","ja":"プリンターに紙を補充してください。","zh":"請幫印表機補充紙張。"}] },
  { id: "notepad", examples: [{"sortOrder":0,"en":"I wrote down the phone number in my notepad.","ja":"電話番号をメモ帳に書きました。","zh":"我把電話號碼記在便條本上。"}] },
  { id: "envelope", examples: [{"sortOrder":0,"en":"Put the contract in this envelope.","ja":"契約書をこの封筒に入れてください。","zh":"請把合約放進這個信封。"}] },
  { id: "business-card", examples: [{"sortOrder":0,"en":"I exchanged business cards with the client.","ja":"取引先の方と名刺を交換しました。","zh":"我和客戶交換了名片。"}] },
  { id: "calendar", examples: [{"sortOrder":0,"en":"The meeting is marked on the calendar.","ja":"会議の日程はカレンダーに書いてあります。","zh":"會議日期標在日曆上。"}] },
  { id: "paper-shredder", examples: [{"sortOrder":0,"en":"Please shred this confidential document.","ja":"この機密書類はシュレッダーにかけてください。","zh":"請把這份機密文件放進碎紙機。"}] },
  { id: "filing-cabinet", examples: [{"sortOrder":0,"en":"The old contracts are in the filing cabinet.","ja":"古い契約書はファイリングキャビネットに入っています。","zh":"舊合約放在文件櫃裡。"}] },
  { id: "conference-table", examples: [{"sortOrder":0,"en":"The handouts are on the conference table.","ja":"資料は会議テーブルの上にあります。","zh":"資料放在會議桌上。"}] },
  { id: "meeting-room", examples: [{"sortOrder":0,"en":"The meeting room is reserved until three.","ja":"会議室は3時まで予約されています。","zh":"會議室預約到三點。"}] },
  { id: "reception-desk", examples: [{"sortOrder":0,"en":"Please check in at the reception desk.","ja":"受付カウンターで手続きをしてください。","zh":"請先到接待櫃檯報到。"}] },
  { id: "water-dispenser", examples: [{"sortOrder":0,"en":"I filled my bottle at the water dispenser.","ja":"ウォーターサーバーで水筒に水を入れました。","zh":"我在飲水機裝滿水壺。"}] },
  { id: "coffee-machine", examples: [{"sortOrder":0,"en":"The coffee machine is out of beans.","ja":"コーヒーマシンの豆が切れています。","zh":"咖啡機沒有咖啡豆了。"}] },
  { id: "access-card", examples: [{"sortOrder":0,"en":"I forgot my access card, so I borrowed a temporary one at reception.","ja":"入館カードを忘れたので、受付で仮カードを借りました。","zh":"我忘了帶門禁卡，所以在櫃檯借了臨時卡。"}] },
  { id: "employee-id-card", examples: [{"sortOrder":0,"en":"Please wear your employee ID card where it can be seen.","ja":"社員証は見える位置につけてください。","zh":"請把員工證佩戴在明顯的位置。"}] },
  { id: "office-supplies", examples: [{"sortOrder":0,"en":"We're running low on office supplies.","ja":"事務用品の在庫が少なくなっています。","zh":"辦公用品快用完了。"}] },
  { id: "street", examples: [{"sortOrder":0,"en":"This street is quiet at night.","ja":"この通りは夜になると静かです。","zh":"這條街晚上很安靜。"}] },
  { id: "road", examples: [{"sortOrder":0,"en":"This road is closed at night.","ja":"この道路は夜間通行止めです。","zh":"這條馬路晚上禁止通行。"}] },
  { id: "intersection", examples: [{"sortOrder":0,"en":"Turn left at the next intersection.","ja":"次の交差点を左に曲がってください。","zh":"請在下一個路口左轉。"}] },
  { id: "traffic-sign", examples: [{"sortOrder":0,"en":"Follow the traffic signs.","ja":"交通標識に従って進んでください。","zh":"請依照交通標誌行駛。"}] },
  { id: "stop-sign", examples: [{"sortOrder":0,"en":"Come to a complete stop at the stop sign.","ja":"一時停止標識では必ず止まってください。","zh":"看到停車標誌時一定要完全停下。"}] },
  { id: "bus-stop", examples: [{"sortOrder":0,"en":"The bus stop is in front of the convenience store.","ja":"バス停はコンビニの前です。","zh":"公車站在便利商店前面。"}] },
  { id: "station", examples: [{"sortOrder":0,"en":"I'll meet you in front of the station.","ja":"駅の前で待ち合わせましょう。","zh":"我們在車站前碰面吧。"}] },
  { id: "subway-station", examples: [{"sortOrder":0,"en":"The subway station entrance is across the street.","ja":"地下鉄の駅の入口は通りの向こう側です。","zh":"地鐵站入口在街道對面。"}] },
  { id: "taxi-stand", examples: [{"sortOrder":0,"en":"Let's wait at the taxi stand.","ja":"タクシー乗り場で待ちましょう。","zh":"我們在計程車站等吧。"}] },
  { id: "parking-lot", examples: [{"sortOrder":0,"en":"The parking lot is full.","ja":"駐車場は満車です。","zh":"停車場已經滿了。"}] },
  { id: "parking-space", examples: [{"sortOrder":0,"en":"There's an empty parking space over there.","ja":"あそこに空いている駐車スペースがあります。","zh":"那邊有一個空的停車位。"}] },
  { id: "parking-meter", examples: [{"sortOrder":0,"en":"Put a 100-yen coin in the parking meter.","ja":"パーキングメーターに百円硬貨を入れます。","zh":"把一百日圓硬幣投入停車收費表。"}] },
  { id: "bike-lane", examples: [{"sortOrder":0,"en":"Please keep out of the bike lane.","ja":"自転車専用レーンには入らないでください。","zh":"請不要走進自行車道。"}] },
  { id: "lane", examples: [{"sortOrder":0,"en":"Move into the left lane.","ja":"左の車線に移ってください。","zh":"請切換到左側車線。"}] },
  { id: "pedestrian-bridge", examples: [{"sortOrder":0,"en":"Use the pedestrian bridge to cross the road.","ja":"歩道橋を渡って向こう側へ行きましょう。","zh":"走天橋到馬路對面吧。"}] },
  { id: "underpass", examples: [{"sortOrder":0,"en":"Use the underpass to cross the road.","ja":"地下道を通って道路の向こう側へ行きます。","zh":"走地下道到馬路對面。"}] },
  { id: "bridge", examples: [{"sortOrder":0,"en":"We crossed the bridge on foot.","ja":"橋を歩いて渡りました。","zh":"我們走路過了那座橋。"}] },
  { id: "tunnel", examples: [{"sortOrder":0,"en":"Turn on the headlights in the tunnel.","ja":"トンネルではライトをつけてください。","zh":"進隧道時請開車燈。"}] },
  { id: "roundabout", examples: [{"sortOrder":0,"en":"Take the second exit at the roundabout.","ja":"ロータリーの二つ目の出口を出てください。","zh":"請從圓環的第二個出口出去。"}] },
  { id: "corner", examples: [{"sortOrder":0,"en":"Turn right at the next corner.","ja":"次の角を右に曲がってください。","zh":"請在下一個轉角右轉。"}] },
  { id: "alley", examples: [{"sortOrder":0,"en":"Let's take the alley as a shortcut.","ja":"近道なので、この路地を通りましょう。","zh":"走這條巷子比較近。"}] },
  { id: "shop", examples: [{"sortOrder":0,"en":"That shop closes at eight.","ja":"あの店は八時に閉まります。","zh":"那間商店八點關門。"}] },
  { id: "convenience-store", examples: [{"sortOrder":0,"en":"I'll buy some water at the convenience store.","ja":"コンビニで水を買ってきます。","zh":"我去便利商店買水。"}] },
  { id: "restaurant", examples: [{"sortOrder":0,"en":"I booked a table at the restaurant.","ja":"レストランを予約しました。","zh":"我已經訂好餐廳了。"}] },
  { id: "cafe", examples: [{"sortOrder":0,"en":"Let's have coffee at that cafe.","ja":"あのカフェでコーヒーを飲みましょう。","zh":"我們去那間咖啡店喝咖啡吧。"}] },
  { id: "bank", examples: [{"sortOrder":0,"en":"I need to stop by the bank.","ja":"銀行に寄ってから帰ります。","zh":"我回家前要去一趟銀行。"}] },
  { id: "post-office", examples: [{"sortOrder":0,"en":"I mailed the package at the post office.","ja":"郵便局で荷物を送りました。","zh":"我在郵局寄了包裹。"}] },
  { id: "pharmacy", examples: [{"sortOrder":0,"en":"I'll pick up my medicine at the pharmacy.","ja":"薬局で薬を受け取ります。","zh":"我要去藥局領藥。"}] },
  { id: "supermarket", examples: [{"sortOrder":0,"en":"I'm going to the supermarket after work.","ja":"仕事のあとでスーパーに寄ります。","zh":"我下班後要去超市。"}] },
  { id: "vending-machine", examples: [{"sortOrder":0,"en":"I bought a bottle of tea from the vending machine.","ja":"自動販売機でお茶を買いました。","zh":"我在自動販賣機買了一瓶茶。"}] },
  { id: "park", examples: [{"sortOrder":0,"en":"Let's eat lunch in the park.","ja":"公園でお昼を食べましょう。","zh":"我們去公園吃午餐吧。"}] },
  { id: "tree", examples: [{"sortOrder":0,"en":"Let's rest in the shade of that tree.","ja":"あの木の下で休みましょう。","zh":"我們去那棵樹下休息吧。"}] },
  { id: "flower-bed", examples: [{"sortOrder":0,"en":"Don't step into the flower bed.","ja":"花壇の中に入らないでください。","zh":"請不要踩進花圃。"}] },
  { id: "pedestrian", examples: [{"sortOrder":0,"en":"Pedestrians have the right of way here.","ja":"ここでは歩行者が優先です。","zh":"這裡行人優先。"}] },
  { id: "signboard", examples: [{"sortOrder":0,"en":"The shop's signboard is easy to spot.","ja":"店の看板がよく目立ちます。","zh":"那間店的招牌很顯眼。"}] },
  { id: "billboard", examples: [{"sortOrder":0,"en":"That billboard is easy to see from the station.","ja":"あの広告看板は駅からよく見えます。","zh":"從車站就能清楚看到那面廣告看板。"}] },
  { id: "fire-hydrant", examples: [{"sortOrder":0,"en":"Don't park in front of the fire hydrant.","ja":"消火栓の前に駐車しないでください。","zh":"請不要停在消防栓前面。"}] },
  { id: "construction-zone", examples: [{"sortOrder":0,"en":"Be careful near the construction zone.","ja":"工事現場の近くでは気をつけてください。","zh":"經過施工區附近時請小心。"}] },
  { id: "roadblock", examples: [{"sortOrder":0,"en":"The barricade is blocking the road.","ja":"バリケードで道路がふさがれています。","zh":"路障把道路封住了。"}] },
  { id: "traffic-cone", examples: [{"sortOrder":0,"en":"The traffic cones mark the work area.","ja":"カラーコーンで作業区域が囲まれています。","zh":"交通錐把施工區圍了起來。"}] },
  { id: "manhole-cover", examples: [{"sortOrder":0,"en":"The manhole cover is slippery when wet.","ja":"マンホールの蓋はぬれると滑りやすいです。","zh":"人孔蓋濕了會很滑。"}] },
  { id: "utility-pole", examples: [{"sortOrder":0,"en":"I'm waiting by the utility pole.","ja":"電柱のそばで待っています。","zh":"我在電線桿旁邊等。"}] },
  { id: "power-lines", examples: [{"sortOrder":0,"en":"The power lines are swaying in the wind.","ja":"電線が風で揺れています。","zh":"電線被風吹得搖晃。"}] },
  { id: "security-camera", examples: [{"sortOrder":0,"en":"A security camera is installed above the entrance.","ja":"入口の上に防犯カメラが付いています。","zh":"入口上方裝有監視器。"}] },
  { id: "pedestrian-button", examples: [{"sortOrder":0,"en":"Press the pedestrian button and wait.","ja":"歩行者用押しボタンを押して待ちましょう。","zh":"按下行人按鈕後等一下。"}] },
  { id: "street-vendor", examples: [{"sortOrder":0,"en":"Let's get ramen at the food cart.","ja":"屋台でラーメンを食べましょう。","zh":"我們去餐車吃拉麵吧。"}] },
  { id: "vendor", examples: [{"sortOrder":0,"en":"I bought vegetables at the market stall.","ja":"露店で野菜を買いました。","zh":"我在市場攤位買了蔬菜。"}] },
  { id: "newsstand", examples: [{"sortOrder":0,"en":"I bought a newspaper at the newsstand.","ja":"新聞売店で新聞を買いました。","zh":"我在報攤買了報紙。"}] },
  { id: "shopping-basket", examples: [{"sortOrder":0,"en":"I found the shopping basket at the supermarket.","ja":"スーパーで買い物かごを見つけました。","zh":"我在超市找到購物籃。"}] },
  { id: "checkout-counter", examples: [{"sortOrder":0,"en":"I found the checkout counter at the supermarket.","ja":"スーパーで会計カウンターを見つけました。","zh":"我在超市找到收銀台。"}] },
  { id: "self-checkout-machine", examples: [{"sortOrder":0,"en":"I found the self-checkout machine at the supermarket.","ja":"スーパーでセルフレジを見つけました。","zh":"我在超市找到自助結帳機。"}] },
  { id: "invoice", examples: [{"sortOrder":0,"en":"I received the invoice at the office.","ja":"オフィスで請求書を受け取りました。","zh":"我在辦公室收到請款單。"}] },
  { id: "plastic-bag", examples: [{"sortOrder":0,"en":"I found the plastic bag at the supermarket.","ja":"スーパーでビニール袋を見つけました。","zh":"我在超市找到塑膠袋。"}] },
  { id: "reusable-bag", examples: [{"sortOrder":0,"en":"I found the reusable bag at the supermarket.","ja":"スーパーでエコバッグを見つけました。","zh":"我在超市找到環保袋。"}] },
  { id: "sale", examples: [{"sortOrder":0,"en":"I found the sale at the supermarket.","ja":"スーパーでセールを見つけました。","zh":"我在超市找到特價。"}] },
  { id: "discount", examples: [{"sortOrder":0,"en":"I found the discount at the supermarket.","ja":"スーパーで割引を見つけました。","zh":"我在超市找到折扣。"}] },
  { id: "coupon", examples: [{"sortOrder":0,"en":"I found the coupon at the supermarket.","ja":"スーパーでクーポンを見つけました。","zh":"我在超市找到優惠券。"}] },
  { id: "membership-card", examples: [{"sortOrder":0,"en":"I found the membership card at the supermarket.","ja":"スーパーで会員カードを見つけました。","zh":"我在超市找到會員卡。"}] },
  { id: "barcode", examples: [{"sortOrder":0,"en":"I found the barcode at the supermarket.","ja":"スーパーでバーコードを見つけました。","zh":"我在超市找到條碼。"}] },
  { id: "refrigerated-section", examples: [{"sortOrder":0,"en":"I found the refrigerated section at the supermarket.","ja":"スーパーで冷蔵コーナーを見つけました。","zh":"我在超市找到冷藏區。"}] },
  { id: "frozen-section", examples: [{"sortOrder":0,"en":"I found the frozen section at the supermarket.","ja":"スーパーで冷凍食品コーナーを見つけました。","zh":"我在超市找到冷凍區。"}] },
  { id: "produce-section", examples: [{"sortOrder":0,"en":"I found the produce section at the supermarket.","ja":"スーパーで青果コーナーを見つけました。","zh":"我在超市找到蔬果區。"}] },
  { id: "meat-section", examples: [{"sortOrder":0,"en":"I found the meat section at the supermarket.","ja":"スーパーで精肉コーナーを見つけました。","zh":"我在超市找到肉品區。"}] },
  { id: "seafood-section", examples: [{"sortOrder":0,"en":"I found the seafood section at the supermarket.","ja":"スーパーで鮮魚コーナーを見つけました。","zh":"我在超市找到海鮮區。"}] },
  { id: "deli-section", examples: [{"sortOrder":0,"en":"I found the deli section at the supermarket.","ja":"スーパーでデリコーナーを見つけました。","zh":"我在超市找到熟食區。"}] },
  { id: "bakery-section", examples: [{"sortOrder":0,"en":"I found the bakery section at the supermarket.","ja":"スーパーでベーカリーコーナーを見つけました。","zh":"我在超市找到烘焙區。"}] },
  { id: "beverage-section", examples: [{"sortOrder":0,"en":"I found the beverage section at the supermarket.","ja":"スーパーで飲料コーナーを見つけました。","zh":"我在超市找到飲料區。"}] },
  { id: "snack-section", examples: [{"sortOrder":0,"en":"I found the snack section at the supermarket.","ja":"スーパーでお菓子コーナーを見つけました。","zh":"我在超市找到零食區。"}] },
  { id: "household-goods-section", examples: [{"sortOrder":0,"en":"I found the household goods section at the supermarket.","ja":"スーパーで日用品コーナーを見つけました。","zh":"我在超市找到日用品區。"}] },
  { id: "frozen-food", examples: [{"sortOrder":0,"en":"I found the frozen food at the supermarket.","ja":"スーパーで冷凍食品を見つけました。","zh":"我在超市找到冷凍食品。"}] },
  { id: "canned-food", examples: [{"sortOrder":0,"en":"I found the canned food at the supermarket.","ja":"スーパーで缶詰を見つけました。","zh":"我在超市找到罐頭。"}] },
  { id: "garbage-bag", examples: [{"sortOrder":0,"en":"I found the garbage bag at the supermarket.","ja":"スーパーでゴミ袋を見つけました。","zh":"我在超市找到垃圾袋。"}] },
  { id: "school-bus", examples: [{"sortOrder":0,"en":"The school bus is a useful way to travel.","ja":"スクールバスは便利な交通手段です。","zh":"校車是實用的交通工具。"}] },
  { id: "coach", examples: [{"sortOrder":0,"en":"The coach is a useful way to travel.","ja":"観光バスは便利な交通手段です。","zh":"長途巴士是實用的交通工具。"}] },
  { id: "minibus", examples: [{"sortOrder":0,"en":"The minibus is a useful way to travel.","ja":"マイクロバスは便利な交通手段です。","zh":"小巴是實用的交通工具。"}] },
  { id: "truck", examples: [{"sortOrder":0,"en":"The truck is a useful way to travel.","ja":"トラックは便利な交通手段です。","zh":"貨車是實用的交通工具。"}] },
  { id: "van", examples: [{"sortOrder":0,"en":"The van is a useful way to travel.","ja":"バンは便利な交通手段です。","zh":"廂型車是實用的交通工具。"}] },
  { id: "ambulance", examples: [{"sortOrder":0,"en":"The ambulance is a useful way to travel.","ja":"救急車は便利な交通手段です。","zh":"救護車是實用的交通工具。"}] },
  { id: "police-car", examples: [{"sortOrder":0,"en":"The police car is a useful way to travel.","ja":"パトカーは便利な交通手段です。","zh":"警車是實用的交通工具。"}] },
  { id: "fire-truck", examples: [{"sortOrder":0,"en":"The fire truck is a useful way to travel.","ja":"消防車は便利な交通手段です。","zh":"消防車是實用的交通工具。"}] },
  { id: "garbage-truck", examples: [{"sortOrder":0,"en":"The garbage truck is a useful way to travel.","ja":"ゴミ収集車は便利な交通手段です。","zh":"垃圾車是實用的交通工具。"}] },
  { id: "tow-truck", examples: [{"sortOrder":0,"en":"The tow truck is a useful way to travel.","ja":"レッカー車は便利な交通手段です。","zh":"拖吊車是實用的交通工具。"}] },
  { id: "camper-van", examples: [{"sortOrder":0,"en":"The camper van is a useful way to travel.","ja":"キャンピングカーは便利な交通手段です。","zh":"露營車是實用的交通工具。"}] },
  { id: "sports-car", examples: [{"sortOrder":0,"en":"The sports car is a useful way to travel.","ja":"スポーツカーは便利な交通手段です。","zh":"跑車是實用的交通工具。"}] },
  { id: "electric-car", examples: [{"sortOrder":0,"en":"The electric car is a useful way to travel.","ja":"電気自動車は便利な交通手段です。","zh":"電動車是實用的交通工具。"}] },
  { id: "electric-scooter", examples: [{"sortOrder":0,"en":"The electric scooter is a useful way to travel.","ja":"電動キックボードは便利な交通手段です。","zh":"電動滑板車是實用的交通工具。"}] },
  { id: "scooter", examples: [{"sortOrder":0,"en":"The scooter is a useful way to travel.","ja":"キックボードは便利な交通手段です。","zh":"滑板車是實用的交通工具。"}] },
  { id: "skateboard", examples: [{"sortOrder":0,"en":"The skateboard is a useful way to travel.","ja":"スケートボードは便利な交通手段です。","zh":"滑板是實用的交通工具。"}] },
  { id: "roller-skates", examples: [{"sortOrder":0,"en":"The roller skates is a useful way to travel.","ja":"ローラースケートは便利な交通手段です。","zh":"溜冰鞋是實用的交通工具。"}] },
  { id: "tram", examples: [{"sortOrder":0,"en":"The tram is a useful way to travel.","ja":"路面電車は便利な交通手段です。","zh":"電車是實用的交通工具。"}] },
  { id: "light-rail", examples: [{"sortOrder":0,"en":"The light rail is a useful way to travel.","ja":"ライトレールは便利な交通手段です。","zh":"輕軌是實用的交通工具。"}] },
  { id: "high-speed-train", examples: [{"sortOrder":0,"en":"The high-speed train is a useful way to travel.","ja":"新幹線は便利な交通手段です。","zh":"高鐵是實用的交通工具。"}] },
  { id: "monorail", examples: [{"sortOrder":0,"en":"The monorail is a useful way to travel.","ja":"モノレールは便利な交通手段です。","zh":"單軌電車是實用的交通工具。"}] },
  { id: "cable-car", examples: [{"sortOrder":0,"en":"The cable car is a useful way to travel.","ja":"ケーブルカーは便利な交通手段です。","zh":"纜車是實用的交通工具。"}] },
  { id: "gondola-lift", examples: [{"sortOrder":0,"en":"The gondola lift is a useful way to travel.","ja":"ゴンドラリフトは便利な交通手段です。","zh":"吊艙纜車是實用的交通工具。"}] },
  { id: "helicopter", examples: [{"sortOrder":0,"en":"The helicopter is a useful way to travel.","ja":"ヘリコプターは便利な交通手段です。","zh":"直升機是實用的交通工具。"}] },
  { id: "hot-air-balloon", examples: [{"sortOrder":0,"en":"The hot air balloon is a useful way to travel.","ja":"熱気球は便利な交通手段です。","zh":"熱氣球是實用的交通工具。"}] },
  { id: "airship", examples: [{"sortOrder":0,"en":"The airship is a useful way to travel.","ja":"飛行船は便利な交通手段です。","zh":"飛船是實用的交通工具。"}] },
  { id: "rocket", examples: [{"sortOrder":0,"en":"The rocket is a useful way to travel.","ja":"ロケットは便利な交通手段です。","zh":"火箭是實用的交通工具。"}] },
  { id: "ferry", examples: [{"sortOrder":0,"en":"The ferry is a useful way to travel.","ja":"フェリーは便利な交通手段です。","zh":"渡輪是實用的交通工具。"}] },
  { id: "cruise-ship", examples: [{"sortOrder":0,"en":"The cruise ship is a useful way to travel.","ja":"クルーズ船は便利な交通手段です。","zh":"遊輪是實用的交通工具。"}] },
  { id: "sailboat", examples: [{"sortOrder":0,"en":"The sailboat is a useful way to travel.","ja":"ヨットは便利な交通手段です。","zh":"帆船是實用的交通工具。"}] },
  { id: "speedboat", examples: [{"sortOrder":0,"en":"The speedboat is a useful way to travel.","ja":"スピードボートは便利な交通手段です。","zh":"快艇是實用的交通工具。"}] },
  { id: "canoe", examples: [{"sortOrder":0,"en":"The canoe is a useful way to travel.","ja":"カヌーは便利な交通手段です。","zh":"獨木舟是實用的交通工具。"}] },
  { id: "kayak", examples: [{"sortOrder":0,"en":"The kayak is a useful way to travel.","ja":"カヤックは便利な交通手段です。","zh":"皮艇是實用的交通工具。"}] },
  { id: "submarine", examples: [{"sortOrder":0,"en":"The submarine is a useful way to travel.","ja":"潜水艦は便利な交通手段です。","zh":"潛水艇是實用的交通工具。"}] },
  { id: "mrt", examples: [{"sortOrder":0,"en":"The MRT is a useful way to travel.","ja":"MRTは便利な交通手段です。","zh":"捷運是實用的交通工具。"}] },
  { id: "rickshaw", examples: [{"sortOrder":0,"en":"The rickshaw is a useful way to travel.","ja":"人力車は便利な交通手段です。","zh":"人力車是實用的交通工具。"}] },
  { id: "tricycle", examples: [{"sortOrder":0,"en":"The tricycle is a useful way to travel.","ja":"三輪車は便利な交通手段です。","zh":"三輪車是實用的交通工具。"}] },
  { id: "white-sugar", examples: [{"sortOrder":0,"en":"Stir a teaspoon of white sugar into the coffee.","ja":"コーヒーに白砂糖を小さじ一杯入れます。","zh":"在咖啡裡加入一茶匙白糖。"}] },
  { id: "brown-sugar", examples: [{"sortOrder":0,"en":"Stir brown sugar into the milk tea.","ja":"ミルクティーにブラウンシュガーを入れます。","zh":"在奶茶裡加入紅糖。"}] },
  { id: "dark-brown-sugar", examples: [{"sortOrder":0,"en":"Stir dark brown sugar into the coffee.","ja":"コーヒーに黒糖を入れます。","zh":"在咖啡裡加入黑糖。"}] },
  { id: "rock-sugar", examples: [{"sortOrder":0,"en":"Add one piece of rock sugar to the tea.","ja":"お茶に氷砂糖を一つ入れます。","zh":"在茶裡放一顆冰糖。"}] },
  { id: "honey", examples: [{"sortOrder":0,"en":"Drizzle honey over the yogurt.","ja":"ヨーグルトに蜂蜜をかけます。","zh":"在優格上淋蜂蜜。"}] },
  { id: "thick-soy-sauce", examples: [{"sortOrder":0,"en":"Drizzle Taiwanese thick soy sauce over the turnip cake.","ja":"大根餅に台湾とろみ醤油をかけます。","zh":"在蘿蔔糕上淋醬油膏。"}] },
  { id: "dark-soy-sauce", examples: [{"sortOrder":0,"en":"Use dark soy sauce to give the braised pork a deeper color.","ja":"老抽を加えて、煮込み料理に色とコクをつけます。","zh":"用老抽替滷肉上色。"}] },
  { id: "light-soy-sauce", examples: [{"sortOrder":0,"en":"Use light soy sauce to season the stir-fry.","ja":"生抽で炒め物に味をつけます。","zh":"炒菜時用生抽調味。"}] },
  { id: "white-vinegar", examples: [{"sortOrder":0,"en":"Use white vinegar for the pickles.","ja":"ピクルスにホワイトビネガーを使います。","zh":"醃漬物要用白醋。"}] },
  { id: "black-vinegar", examples: [{"sortOrder":0,"en":"Dip the dumplings in black vinegar.","ja":"餃子に黒酢をつけて食べます。","zh":"水餃沾黑醋吃。"}] },
  { id: "apple-cider-vinegar", examples: [{"sortOrder":0,"en":"I use apple cider vinegar in salad dressing.","ja":"サラダのドレッシングにリンゴ酢を使います。","zh":"我用蘋果醋做沙拉醬。"}] },
  { id: "mirin", examples: [{"sortOrder":0,"en":"Add mirin to the simmered dish.","ja":"煮物にみりんを加えます。","zh":"在燉煮料理裡加入味醂。"}] },
  { id: "rice-wine", examples: [{"sortOrder":0,"en":"Add Taiwanese rice wine to three cup chicken.","ja":"三杯鶏に台湾米酒を加えます。","zh":"三杯雞裡要加入米酒。"}] },
  { id: "sake", examples: [{"sortOrder":0,"en":"Add sake when simmering the fish.","ja":"魚を煮るときに日本酒を加えます。","zh":"煮魚時加入清酒。"}] },
  { id: "vegetable-oil", examples: [{"sortOrder":0,"en":"Coat the pan with vegetable oil.","ja":"フライパンに植物油をひきます。","zh":"在平底鍋裡抹上植物油。"}] },
  { id: "chili-oil", examples: [{"sortOrder":0,"en":"Add chili oil to the dumpling sauce.","ja":"餃子のたれにラー油を入れます。","zh":"在水餃沾醬裡加入辣椒油。"}] },
  { id: "yellow-mustard", examples: [{"sortOrder":0,"en":"Squeeze yellow mustard onto the hot dog.","ja":"ホットドッグにイエローマスタードをかけます。","zh":"在熱狗上擠黃芥末。"}] },
  { id: "wasabi", examples: [{"sortOrder":0,"en":"Eat the sashimi with wasabi.","ja":"刺身にわさびをつけて食べます。","zh":"生魚片沾山葵吃。"}] },
  { id: "sweet-chili-sauce", examples: [{"sortOrder":0,"en":"Dip the spring rolls in sweet chili sauce.","ja":"生春巻きをスイートチリソースにつけます。","zh":"把春捲沾甜辣醬吃。"}] },
  { id: "chili-bean-paste", examples: [{"sortOrder":0,"en":"Use chili bean paste in mapo tofu.","ja":"麻婆豆腐に豆板醤を使います。","zh":"麻婆豆腐要用豆瓣醬。"}] },
  { id: "shacha-sauce", examples: [{"sortOrder":0,"en":"Add shacha sauce to the hot pot dipping sauce.","ja":"火鍋のつけだれに沙茶醤を加えます。","zh":"在火鍋沾醬裡加入沙茶醬。"}] },
  { id: "peanut-butter", examples: [{"sortOrder":0,"en":"Spread peanut butter on the toast.","ja":"トーストにピーナッツバターを塗ります。","zh":"在吐司上抹花生醬。"}] },
  { id: "sesame-paste", examples: [{"sortOrder":0,"en":"Use sesame paste to make the dressing.","ja":"ごまペーストで和え物のたれを作ります。","zh":"用芝麻醬做拌醬。"}] },
  { id: "miso", examples: [{"sortOrder":0,"en":"Dissolve the miso to make miso soup.","ja":"味噌を溶いて味噌汁を作ります。","zh":"把味噌化開來煮味噌湯。"}] },
  { id: "curry-roux", examples: [{"sortOrder":0,"en":"Add the curry roux to the pot and let it melt.","ja":"鍋にカレールーを入れて溶かします。","zh":"把咖哩塊放進鍋裡煮化。"}] },
  { id: "sichuan-peppercorn", examples: [{"sortOrder":0,"en":"Add Sichuan peppercorns to the mapo tofu.","ja":"麻婆豆腐に花椒を加えます。","zh":"在麻婆豆腐裡加入花椒。"}] },
  { id: "star-anise", examples: [{"sortOrder":0,"en":"Add one star anise to the braised pork.","ja":"豚の角煮に八角を一つ入れます。","zh":"在滷肉裡放一顆八角。"}] },
  { id: "cinnamon-bark", examples: [{"sortOrder":0,"en":"Put a cinnamon stick in the tea.","ja":"紅茶にシナモンスティックを入れます。","zh":"在茶裡放一根肉桂棒。"}] },
  { id: "cumin-powder", examples: [{"sortOrder":0,"en":"Add cumin powder to the curry.","ja":"カレーにクミンパウダーを加えます。","zh":"在咖哩裡加入孜然粉。"}] },
  { id: "turmeric-powder", examples: [{"sortOrder":0,"en":"Add turmeric powder to the curry.","ja":"カレーにターメリックパウダーを加えます。","zh":"在咖哩裡加入薑黃粉。"}] },
  { id: "shichimi", examples: [{"sortOrder":0,"en":"Sprinkle shichimi over the udon.","ja":"うどんに七味唐辛子をふりかけます。","zh":"在烏龍麵上撒七味粉。"}] },
  { id: "coriander-seeds", examples: [{"sortOrder":0,"en":"Crush the coriander seeds before adding them to the curry.","ja":"コリアンダーシードを砕いてカレーに加えます。","zh":"把香菜籽壓碎後加入咖哩。"}] },
  { id: "fennel-seeds", examples: [{"sortOrder":0,"en":"Mix fennel seeds into the bread dough.","ja":"パン生地にフェンネルシードを混ぜます。","zh":"把小茴香拌進麵包麵糰。"}] },
  { id: "cloves", examples: [{"sortOrder":0,"en":"Add one clove to the curry.","ja":"カレーにクローブを一粒入れます。","zh":"在咖哩裡放一顆丁香。"}] },
  { id: "cardamom", examples: [{"sortOrder":0,"en":"Add cardamom to the chai.","ja":"チャイにカルダモンを加えます。","zh":"在印度奶茶裡加入豆蔻。"}] },
  { id: "oregano", examples: [{"sortOrder":0,"en":"Sprinkle oregano on the pizza.","ja":"ピザにオレガノをふりかけます。","zh":"在披薩上撒奧勒岡。"}] },
  { id: "parsley", examples: [{"sortOrder":0,"en":"Sprinkle parsley over the soup.","ja":"スープにパセリを散らします。","zh":"在湯上撒巴西里。"}] },
  { id: "vanilla-extract", examples: [{"sortOrder":0,"en":"Add vanilla extract to the cake batter.","ja":"ケーキの生地にバニラエッセンスを加えます。","zh":"在蛋糕麵糊裡加入香草精。"}] },
  { id: "baking-powder", examples: [{"sortOrder":0,"en":"Add baking powder to the cake batter.","ja":"ケーキの生地にベーキングパウダーを入れます。","zh":"在蛋糕麵糊裡加入發粉。"}] },
  { id: "baking-soda", examples: [{"sortOrder":0,"en":"Add baking soda to the cookie dough.","ja":"クッキーの生地に重曹を入れます。","zh":"在餅乾麵糰裡加入小蘇打粉。"}] },
  { id: "potato-starch", examples: [{"sortOrder":0,"en":"Thicken the sauce with potato starch.","ja":"片栗粉であんにとろみをつけます。","zh":"用太白粉把醬汁勾芡。"}] },
  { id: "cornstarch", examples: [{"sortOrder":0,"en":"Thicken the soup with cornstarch.","ja":"コーンスターチでスープにとろみをつけます。","zh":"用玉米澱粉把湯勾芡。"}] },
  { id: "flour", examples: [{"sortOrder":0,"en":"I use flour to make bread.","ja":"小麦粉でパンを作ります。","zh":"我用麵粉做麵包。"}] },
  { id: "bouillon-powder", examples: [{"sortOrder":0,"en":"Dissolve the bouillon powder in the soup.","ja":"スープにブイヨンパウダーを溶かします。","zh":"把高湯粉溶進湯裡。"}] },
  { id: "chicken-bouillon-powder", examples: [{"sortOrder":0,"en":"Add chicken bouillon powder to the stir-fry.","ja":"炒め物に鶏ガラスープの素を加えます。","zh":"炒菜時加入雞粉。"}] },
  { id: "kombu-powder", examples: [{"sortOrder":0,"en":"Add a little kombu powder to the miso soup.","ja":"味噌汁に昆布パウダーを少し入れます。","zh":"在味噌湯裡加一點昆布粉。"}] },
  { id: "bonito-powder", examples: [{"sortOrder":0,"en":"Sprinkle bonito powder on the okonomiyaki.","ja":"お好み焼きに鰹節粉をかけます。","zh":"在大阪燒上撒柴魚粉。"}] },
  { id: "aries", examples: [{"sortOrder":0,"en":"My zodiac sign is Aries.","ja":"私の星座は牡羊座です。","zh":"我的星座是牡羊座。"}] },
  { id: "taurus", examples: [{"sortOrder":0,"en":"She was born under Taurus.","ja":"彼女はおうし座です。","zh":"她是金牛座。"}] },
  { id: "gemini", examples: [{"sortOrder":0,"en":"His zodiac sign is Gemini.","ja":"彼の星座は双子座です。","zh":"他的星座是雙子座。"}] },
  { id: "cancer", examples: [{"sortOrder":0,"en":"Her zodiac sign is Cancer.","ja":"彼女の星座は蟹座です。","zh":"她的星座是巨蟹座。"}] },
  { id: "leo", examples: [{"sortOrder":0,"en":"Leo is represented by a lion.","ja":"獅子座はライオンで表現されています。","zh":"獅子座以獅子作為代表。"}] },
  { id: "virgo", examples: [{"sortOrder":0,"en":"My sister is a Virgo.","ja":"私の妹は乙女座です。","zh":"我妹妹是處女座。"}] },
  { id: "libra", examples: [{"sortOrder":0,"en":"Libra is represented by scales.","ja":"天秤座は天秤で表されます。","zh":"天秤座以天秤作為代表。"}] },
  { id: "scorpio", examples: [{"sortOrder":0,"en":"He is a Scorpio.","ja":"彼は蠍座です。","zh":"他是天蠍座。"}] },
  { id: "sagittarius", examples: [{"sortOrder":0,"en":"Sagittarius is represented by an archer.","ja":"射手座は射手によって表されます。","zh":"射手座以弓箭手作為代表。"}] },
  { id: "capricorn", examples: [{"sortOrder":0,"en":"My father is a Capricorn.","ja":"私の父は山羊座です。","zh":"我爸爸是摩羯座。"}] },
  { id: "aquarius", examples: [{"sortOrder":0,"en":"Aquarius is represented by a water bearer.","ja":"水瓶座は水を運ぶ人によって表されます。","zh":"水瓶座以持水者作為代表。"}] },
  { id: "pisces", examples: [{"sortOrder":0,"en":"Pisces is represented by two fish.","ja":"魚座は2匹の魚で表されます。","zh":"雙魚座以兩條魚作為代表。"}] },
];
