import type { Example, Word, WordRelation } from "@/types";
import imageUrls from "./image-urls.json";
import { MAIN_WORD_EXPANSION_BATCH_3_WORDS } from "./main-word-expansion-2026-09-batch-3";
import { MAIN_WORD_EXPANSION_BATCH_2_WORDS } from "./main-word-expansion-2026-09-batch-2";
import { MAIN_WORD_EXPANSION_WORDS } from "./main-word-expansion-2026-09";
import supplementalRawWords from "./supplemental-words.json";

// Internal: the inline seed below uses the pre-v2 shape (single Chinese
// string, flat examples, untyped related/confusing arrays). The Word type
// in @/types is the v2 shape. We convert lazily at the bottom of this file
// rather than rewriting 1800 lines of inline literals.
type LegacyExample = {
  en: string;
  zh: string;
  ja?: string;
  cefrLevel?: Example["cefrLevel"];
};
type LegacyConfusing = { word: string; note: string };
type LegacyWord = {
  id: string;
  word: string;
  alsoKnownAs?: string[];
  chinese: string;
  category: string;
  partOfSpeech: string;
  pronunciation: string;
  imageUrl?: string;
  chineseDefinition?: string;
  definitions?: Word["definitions"];
  collocations?: string[];
  examples: LegacyExample[];
  relatedWords?: string[];
  confusingWords?: LegacyConfusing[];
  note?: string;
};

const imageMap = imageUrls as Record<string, string>;
const supplementalWords = supplementalRawWords as LegacyWord[];

const rawWords: LegacyWord[] = [
  // ---------- Kitchen ----------
  {
    id: "fridge",
    word: "fridge",
    alsoKnownAs: ["refrigerator"],
    chinese: "冰箱",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/frɪdʒ/",
    collocations: ["open the fridge", "put in the fridge", "empty fridge"],
    examples: [
      { en: "Put the milk in the fridge.", zh: "把牛奶放進冰箱。" },
      { en: "The fridge is full of food.", zh: "冰箱裡裝滿了食物。" },
      { en: "Can you check the fridge for eggs?", zh: "你能看看冰箱裡有沒有蛋嗎？" },
    ],
    relatedWords: ["freezer", "milk", "kitchen", "door"],
    confusingWords: [
      { word: "refrigerator", note: "refrigerator 比較正式，fridge 比較口語。" },
    ],
  },
  {
    id: "microwave",
    word: "microwave",
    chinese: "微波爐",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/ˈmaɪ.kroʊ.weɪv/",
    collocations: ["microwave the food", "in the microwave"],
    examples: [
      { en: "Heat the soup in the microwave.", zh: "把湯放進微波爐加熱。" },
      { en: "Don't put metal in the microwave.", zh: "不要把金屬放進微波爐。" },
      { en: "The microwave beeps when it's done.", zh: "微波爐完成時會發出嗶聲。" },
    ],
    relatedWords: ["oven", "heat", "food"],
  },
  {
    id: "oven",
    word: "oven",
    chinese: "烤箱",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/ˈʌv.ən/",
    collocations: ["preheat the oven", "in the oven"],
    examples: [
      { en: "Preheat the oven to 180 degrees.", zh: "預熱烤箱到 180 度。" },
      { en: "The cake is still in the oven.", zh: "蛋糕還在烤箱裡。" },
      { en: "Be careful, the oven is hot.", zh: "小心，烤箱很燙。" },
    ],
    relatedWords: ["bake", "microwave", "stove"],
    confusingWords: [
      { word: "microwave", note: "oven 是烤箱，用熱風烤；microwave 是微波爐。" },
    ],
  },
  {
    id: "stove",
    word: "stove",
    chinese: "爐子 / 瓦斯爐",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/stoʊv/",
    collocations: ["turn on the stove", "gas stove"],
    examples: [
      { en: "She is cooking on the stove.", zh: "她正在爐子上煮東西。" },
      { en: "Turn off the stove when you finish.", zh: "煮完後請關掉爐子。" },
      { en: "Our stove uses gas.", zh: "我們的爐子是用瓦斯的。" },
    ],
    relatedWords: ["pan", "pot", "fire", "gas"],
  },
  {
    id: "sink",
    word: "sink",
    chinese: "水槽",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/sɪŋk/",
    collocations: ["wash in the sink", "kitchen sink"],
    examples: [
      { en: "The dishes are in the sink.", zh: "碗盤在水槽裡。" },
      { en: "Don't pour oil into the sink.", zh: "不要把油倒進水槽。" },
      { en: "She washed her hands at the sink.", zh: "她在水槽邊洗手。" },
    ],
    relatedWords: ["faucet", "water", "dish"],
  },
  {
    id: "faucet",
    word: "faucet",
    alsoKnownAs: ["tap"],
    chinese: "水龍頭",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/ˈfɔː.sət/",
    collocations: ["turn on the faucet", "leaky faucet"],
    examples: [
      { en: "Turn off the faucet to save water.", zh: "關掉水龍頭以節省用水。" },
      { en: "The faucet is leaking.", zh: "水龍頭在漏水。" },
      { en: "Cold water comes out of this faucet.", zh: "這個水龍頭流出來的是冷水。" },
    ],
    relatedWords: ["sink", "water", "pipe"],
    confusingWords: [
      { word: "tap", note: "美式英文常用 faucet，英式英文常用 tap。" },
    ],
  },
  {
    id: "pan",
    word: "pan",
    chinese: "平底鍋",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/pæn/",
    collocations: ["frying pan", "non-stick pan"],
    examples: [
      { en: "Heat the oil in a pan.", zh: "把油在平底鍋裡加熱。" },
      { en: "She fried the eggs in a pan.", zh: "她用平底鍋煎蛋。" },
      { en: "This pan is non-stick.", zh: "這個平底鍋是不沾鍋。" },
    ],
    relatedWords: ["pot", "stove", "cook"],
    confusingWords: [
      { word: "pot", note: "pan 通常是淺的平底鍋；pot 是較深的鍋子（湯鍋）。" },
    ],
  },
  {
    id: "pot",
    word: "pot",
    chinese: "鍋子 / 湯鍋",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/pɑːt/",
    collocations: ["a pot of soup", "boil in a pot"],
    examples: [
      { en: "Boil water in the pot.", zh: "用鍋子煮開水。" },
      { en: "She cooked a big pot of soup.", zh: "她煮了一大鍋湯。" },
      { en: "Cover the pot with a lid.", zh: "把鍋蓋蓋上。" },
    ],
    relatedWords: ["pan", "soup", "lid"],
  },
  {
    id: "cutting-board",
    word: "cutting board",
    chinese: "砧板",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/ˈkʌt.ɪŋ ˌbɔːrd/",
    collocations: ["wooden cutting board", "on the cutting board"],
    examples: [
      { en: "Chop the onions on the cutting board.", zh: "在砧板上切洋蔥。" },
      { en: "Use a clean cutting board for meat.", zh: "切肉要用乾淨的砧板。" },
      { en: "The cutting board is made of wood.", zh: "這個砧板是木製的。" },
    ],
    relatedWords: ["knife", "chop", "kitchen"],
  },
  {
    id: "knife",
    word: "knife",
    chinese: "刀子",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/naɪf/",
    collocations: ["sharp knife", "kitchen knife"],
    examples: [
      { en: "Be careful with the knife.", zh: "用刀子要小心。" },
      { en: "This knife is very sharp.", zh: "這把刀非常鋒利。" },
      { en: "She cut the bread with a knife.", zh: "她用刀切麵包。" },
    ],
    relatedWords: ["fork", "spoon", "cut"],
  },
  {
    id: "bowl",
    word: "bowl",
    chinese: "碗",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/boʊl/",
    collocations: ["a bowl of soup", "rice bowl"],
    examples: [
      { en: "I'd like a bowl of rice.", zh: "我想要一碗飯。" },
      { en: "Put the salad in the bowl.", zh: "把沙拉放進碗裡。" },
      { en: "The bowl is full of fruit.", zh: "碗裡裝滿了水果。" },
    ],
    relatedWords: ["plate", "spoon", "soup"],
  },
  {
    id: "plate",
    word: "plate",
    chinese: "盤子",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/pleɪt/",
    collocations: ["clean plate", "dinner plate"],
    examples: [
      { en: "Please pass me a plate.", zh: "請遞給我一個盤子。" },
      { en: "He finished everything on his plate.", zh: "他把盤子裡的東西都吃完了。" },
      { en: "The plate is hot.", zh: "盤子很燙。" },
    ],
    relatedWords: ["bowl", "fork", "dish"],
    confusingWords: [
      { word: "dish", note: "plate 是盤子本身；dish 可指盤子，也可指一道菜。" },
    ],
  },
  {
    id: "chopsticks",
    word: "chopsticks",
    chinese: "筷子",
    category: "kitchen",
    partOfSpeech: "noun (plural)",
    pronunciation: "/ˈtʃɑːp.stɪks/",
    collocations: ["use chopsticks", "a pair of chopsticks"],
    examples: [
      { en: "Can you use chopsticks?", zh: "你會用筷子嗎？" },
      { en: "He picked up the noodles with chopsticks.", zh: "他用筷子夾起麵條。" },
      { en: "I need a pair of chopsticks.", zh: "我需要一雙筷子。" },
    ],
    relatedWords: ["fork", "spoon", "knife"],
    note: "chopsticks 是複數名詞，永遠以 -s 結尾。",
  },
  {
    id: "spoon",
    word: "spoon",
    chinese: "湯匙",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/spuːn/",
    collocations: ["a spoon of sugar", "soup spoon"],
    examples: [
      { en: "Stir the coffee with a spoon.", zh: "用湯匙攪拌咖啡。" },
      { en: "Add a spoon of sugar.", zh: "加一匙糖。" },
      { en: "The baby is learning to use a spoon.", zh: "寶寶正在學用湯匙。" },
    ],
    relatedWords: ["fork", "knife", "bowl"],
  },
  {
    id: "mug",
    word: "mug",
    chinese: "馬克杯",
    category: "kitchen",
    partOfSpeech: "noun",
    pronunciation: "/mʌɡ/",
    collocations: ["a mug of coffee", "favorite mug"],
    examples: [
      { en: "I drink coffee from a big mug.", zh: "我用大馬克杯喝咖啡。" },
      { en: "This mug has my name on it.", zh: "這個馬克杯上有我的名字。" },
      { en: "Pour the tea into the mug.", zh: "把茶倒進馬克杯。" },
    ],
    relatedWords: ["cup", "coffee", "tea"],
    confusingWords: [
      { word: "cup", note: "mug 是有把手的厚杯，多用於熱飲；cup 範圍更廣。" },
    ],
  },

  // ---------- Bathroom ----------
  {
    id: "toothbrush",
    word: "toothbrush",
    chinese: "牙刷",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈtuːθ.brʌʃ/",
    collocations: ["electric toothbrush", "new toothbrush"],
    examples: [
      { en: "I need a new toothbrush.", zh: "我需要一支新牙刷。" },
      { en: "Brush your teeth with a toothbrush.", zh: "用牙刷刷牙。" },
      { en: "Her toothbrush is pink.", zh: "她的牙刷是粉紅色的。" },
    ],
    relatedWords: ["toothpaste", "teeth", "brush"],
  },
  {
    id: "toothpaste",
    word: "toothpaste",
    chinese: "牙膏",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈtuːθ.peɪst/",
    collocations: ["a tube of toothpaste"],
    examples: [
      { en: "Put toothpaste on your toothbrush.", zh: "把牙膏擠在牙刷上。" },
      { en: "We're running out of toothpaste.", zh: "牙膏快用完了。" },
      { en: "This toothpaste tastes like mint.", zh: "這牙膏是薄荷口味。" },
    ],
    relatedWords: ["toothbrush", "teeth"],
  },
  {
    id: "towel",
    word: "towel",
    chinese: "毛巾",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈtaʊ.əl/",
    collocations: ["dry with a towel", "bath towel"],
    examples: [
      { en: "Dry your hands with the towel.", zh: "用毛巾擦乾手。" },
      { en: "The towels are in the closet.", zh: "毛巾在櫃子裡。" },
      { en: "She wrapped a towel around her hair.", zh: "她用毛巾包住頭髮。" },
    ],
    relatedWords: ["bath", "soap", "shower"],
  },
  {
    id: "soap",
    word: "soap",
    chinese: "肥皂",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/soʊp/",
    collocations: ["bar of soap", "wash with soap"],
    examples: [
      { en: "Wash your hands with soap.", zh: "用肥皂洗手。" },
      { en: "This soap smells like lemon.", zh: "這塊肥皂有檸檬味。" },
      { en: "I need a new bar of soap.", zh: "我需要一塊新的肥皂。" },
    ],
    relatedWords: ["water", "wash", "shampoo"],
  },
  {
    id: "shampoo",
    word: "shampoo",
    chinese: "洗髮精",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ʃæmˈpuː/",
    collocations: ["wash with shampoo"],
    examples: [
      { en: "I use this shampoo every day.", zh: "我每天都用這款洗髮精。" },
      { en: "We need to buy more shampoo.", zh: "我們得買更多洗髮精。" },
      { en: "This shampoo is good for dry hair.", zh: "這款洗髮精適合乾性頭髮。" },
    ],
    relatedWords: ["soap", "hair", "conditioner"],
  },
  {
    id: "shower",
    word: "shower",
    chinese: "淋浴 / 蓮蓬頭",
    category: "bathroom",
    partOfSpeech: "noun / verb",
    pronunciation: "/ˈʃaʊ.ər/",
    collocations: ["take a shower", "hot shower"],
    examples: [
      { en: "I take a shower every morning.", zh: "我每天早上洗澡。" },
      { en: "The shower is broken.", zh: "蓮蓬頭壞了。" },
      { en: "He sings in the shower.", zh: "他洗澡時會唱歌。" },
    ],
    relatedWords: ["bath", "soap", "towel"],
    confusingWords: [
      { word: "bath", note: "shower 是站著淋浴；bath 是泡澡。" },
    ],
  },
  {
    id: "mirror",
    word: "mirror",
    chinese: "鏡子",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈmɪr.ər/",
    collocations: ["look in the mirror"],
    examples: [
      { en: "She looked at herself in the mirror.", zh: "她在鏡子裡看著自己。" },
      { en: "The mirror is fogged up.", zh: "鏡子起霧了。" },
      { en: "There's a big mirror on the wall.", zh: "牆上有一面大鏡子。" },
    ],
    relatedWords: ["wall", "reflection"],
  },
  {
    id: "toilet",
    word: "toilet",
    chinese: "馬桶",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈtɔɪ.lət/",
    collocations: ["flush the toilet"],
    examples: [
      { en: "Please flush the toilet.", zh: "請沖馬桶。" },
      { en: "The toilet is clogged.", zh: "馬桶塞住了。" },
      { en: "Where's the toilet?", zh: "廁所在哪裡？" },
    ],
    relatedWords: ["bathroom", "flush"],
    confusingWords: [
      { word: "bathroom", note: "toilet 指馬桶本身；bathroom 指整個浴室空間。" },
    ],
  },
  {
    id: "comb",
    word: "comb",
    chinese: "梳子",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/koʊm/",
    collocations: ["comb your hair"],
    examples: [
      { en: "Use a comb to fix your hair.", zh: "用梳子整理頭髮。" },
      { en: "I lost my comb.", zh: "我的梳子不見了。" },
      { en: "This comb is plastic.", zh: "這把梳子是塑膠的。" },
    ],
    relatedWords: ["brush", "hair"],
    note: "comb 的 b 不發音。",
  },
  {
    id: "hair-dryer",
    word: "hair dryer",
    chinese: "吹風機",
    category: "bathroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈher ˌdraɪ.ər/",
    collocations: ["use a hair dryer", "blow with a hair dryer"],
    examples: [
      { en: "She dried her hair with a hair dryer.", zh: "她用吹風機把頭髮吹乾。" },
      { en: "The hair dryer is loud.", zh: "吹風機聲音很大。" },
      { en: "Do you have a hair dryer?", zh: "你有吹風機嗎？" },
    ],
    relatedWords: ["hair", "dry"],
  },

  // ---------- Bedroom ----------
  {
    id: "bed",
    word: "bed",
    chinese: "床",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/bed/",
    collocations: ["go to bed", "make the bed"],
    examples: [
      { en: "I go to bed at 11 p.m.", zh: "我晚上 11 點睡覺。" },
      { en: "Please make your bed.", zh: "請整理你的床。" },
      { en: "The cat is sleeping on the bed.", zh: "貓在床上睡覺。" },
    ],
    relatedWords: ["pillow", "blanket", "sleep"],
  },
  {
    id: "pillow",
    word: "pillow",
    chinese: "枕頭",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈpɪl.oʊ/",
    collocations: ["soft pillow", "pillow case"],
    examples: [
      { en: "This pillow is too soft.", zh: "這個枕頭太軟了。" },
      { en: "She put her head on the pillow.", zh: "她把頭靠在枕頭上。" },
      { en: "I need a new pillow.", zh: "我需要一個新枕頭。" },
    ],
    relatedWords: ["bed", "blanket", "sleep"],
  },
  {
    id: "blanket",
    word: "blanket",
    chinese: "毯子",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈblæŋ.kət/",
    collocations: ["warm blanket", "under the blanket"],
    examples: [
      { en: "It's cold; grab a blanket.", zh: "好冷，拿條毯子吧。" },
      { en: "He hid under the blanket.", zh: "他躲在毯子下面。" },
      { en: "This blanket is very warm.", zh: "這條毯子很暖。" },
    ],
    relatedWords: ["pillow", "bed", "sheet"],
  },
  {
    id: "closet",
    word: "closet",
    chinese: "衣櫃",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈklɑː.zət/",
    collocations: ["walk-in closet", "open the closet"],
    examples: [
      { en: "Hang the coat in the closet.", zh: "把外套掛到衣櫃裡。" },
      { en: "Her closet is full of dresses.", zh: "她的衣櫃裡塞滿了洋裝。" },
      { en: "Close the closet door.", zh: "把衣櫃門關上。" },
    ],
    relatedWords: ["clothes", "door", "drawer"],
  },
  {
    id: "lamp",
    word: "lamp",
    chinese: "燈",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/læmp/",
    collocations: ["turn on the lamp", "bedside lamp"],
    examples: [
      { en: "Turn on the lamp.", zh: "把燈打開。" },
      { en: "She reads under a lamp.", zh: "她在燈下看書。" },
      { en: "The lamp is broken.", zh: "燈壞了。" },
    ],
    relatedWords: ["light", "bulb", "desk"],
  },
  {
    id: "alarm-clock",
    word: "alarm clock",
    chinese: "鬧鐘",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/əˈlɑːrm ˌklɑːk/",
    collocations: ["set the alarm clock"],
    examples: [
      { en: "I set the alarm clock for 7 a.m.", zh: "我把鬧鐘設成早上 7 點。" },
      { en: "The alarm clock woke me up.", zh: "鬧鐘把我吵醒了。" },
      { en: "Where is my alarm clock?", zh: "我的鬧鐘在哪？" },
    ],
    relatedWords: ["clock", "wake", "morning"],
  },
  {
    id: "curtain",
    word: "curtain",
    chinese: "窗簾",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈkɝː.tən/",
    collocations: ["open the curtain", "close the curtain"],
    examples: [
      { en: "Please open the curtains.", zh: "請把窗簾拉開。" },
      { en: "The curtains are blue.", zh: "窗簾是藍色的。" },
      { en: "Close the curtains at night.", zh: "晚上把窗簾拉上。" },
    ],
    relatedWords: ["window", "blind"],
  },
  {
    id: "wardrobe",
    word: "wardrobe",
    chinese: "衣櫥",
    category: "bedroom",
    partOfSpeech: "noun",
    pronunciation: "/ˈwɔːr.droʊb/",
    collocations: ["open the wardrobe"],
    examples: [
      { en: "She opened her wardrobe.", zh: "她打開了衣櫥。" },
      { en: "There is a mirror on the wardrobe.", zh: "衣櫥上有面鏡子。" },
      { en: "His wardrobe is mostly black.", zh: "他的衣服大多是黑色的。" },
    ],
    relatedWords: ["closet", "clothes"],
    confusingWords: [
      { word: "closet", note: "wardrobe 多用於英式英文；美式英文常說 closet。" },
    ],
  },

  // ---------- Living Room ----------
  {
    id: "sofa",
    word: "sofa",
    alsoKnownAs: ["couch"],
    chinese: "沙發",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/ˈsoʊ.fə/",
    collocations: ["sit on the sofa"],
    examples: [
      { en: "Let's sit on the sofa.", zh: "我們坐在沙發上吧。" },
      { en: "The cat is on the sofa.", zh: "貓在沙發上。" },
      { en: "Our sofa is too small.", zh: "我們的沙發太小。" },
    ],
    relatedWords: ["couch", "chair", "cushion"],
    confusingWords: [
      { word: "couch", note: "sofa 和 couch 幾乎相同；couch 更口語。" },
    ],
  },
  {
    id: "tv",
    word: "TV",
    alsoKnownAs: ["television"],
    chinese: "電視",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/ˌtiːˈviː/",
    collocations: ["watch TV", "turn on the TV"],
    examples: [
      { en: "We watch TV every night.", zh: "我們每天晚上看電視。" },
      { en: "Turn off the TV, please.", zh: "請把電視關掉。" },
      { en: "The TV is too loud.", zh: "電視太大聲了。" },
    ],
    relatedWords: ["remote", "channel", "screen"],
  },
  {
    id: "remote",
    word: "remote",
    alsoKnownAs: ["remote control"],
    chinese: "遙控器",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/rɪˈmoʊt/",
    collocations: ["TV remote", "find the remote"],
    examples: [
      { en: "Where is the remote?", zh: "遙控器在哪裡？" },
      { en: "Pass me the remote.", zh: "把遙控器遞給我。" },
      { en: "The remote needs new batteries.", zh: "遙控器要換新電池。" },
    ],
    relatedWords: ["TV", "battery", "channel"],
  },
  {
    id: "coffee-table",
    word: "coffee table",
    chinese: "茶几",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/ˈkɑː.fi ˌteɪ.bəl/",
    collocations: ["on the coffee table"],
    examples: [
      { en: "Put the magazine on the coffee table.", zh: "把雜誌放在茶几上。" },
      { en: "There's a vase on the coffee table.", zh: "茶几上有個花瓶。" },
      { en: "Don't put your feet on the coffee table.", zh: "不要把腳放在茶几上。" },
    ],
    relatedWords: ["sofa", "table"],
  },
  {
    id: "rug",
    word: "rug",
    chinese: "地毯（小）",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/rʌɡ/",
    collocations: ["soft rug", "on the rug"],
    examples: [
      { en: "There's a rug under the table.", zh: "桌子底下有塊地毯。" },
      { en: "The dog is sleeping on the rug.", zh: "狗在地毯上睡覺。" },
      { en: "This rug is handmade.", zh: "這塊地毯是手工的。" },
    ],
    relatedWords: ["carpet", "floor"],
    confusingWords: [
      { word: "carpet", note: "rug 較小、可移動；carpet 通常鋪滿整個地板。" },
    ],
  },
  {
    id: "clock",
    word: "clock",
    chinese: "時鐘",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/klɑːk/",
    collocations: ["wall clock"],
    examples: [
      { en: "The clock says it's three.", zh: "時鐘顯示三點。" },
      { en: "There's a clock on the wall.", zh: "牆上有個時鐘。" },
      { en: "The clock is fast.", zh: "時鐘快了。" },
    ],
    relatedWords: ["watch", "time", "alarm clock"],
    confusingWords: [
      { word: "watch", note: "clock 是放在桌上或牆上；watch 是戴在手上的手錶。" },
    ],
  },
  {
    id: "picture-frame",
    word: "picture frame",
    chinese: "相框",
    category: "living-room",
    partOfSpeech: "noun",
    pronunciation: "/ˈpɪk.tʃər ˌfreɪm/",
    examples: [
      { en: "She put the photo in a picture frame.", zh: "她把照片放進相框。" },
      { en: "The picture frame is wooden.", zh: "相框是木製的。" },
      { en: "There are many picture frames on the shelf.", zh: "架子上有很多相框。" },
    ],
    relatedWords: ["photo", "wall"],
  },

  // ---------- Office ----------
  {
    id: "desk",
    word: "desk",
    chinese: "書桌 / 工作桌",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/desk/",
    collocations: ["sit at the desk", "office desk"],
    examples: [
      { en: "I put my laptop on the desk.", zh: "我把筆電放在書桌上。" },
      { en: "Clean your desk before leaving.", zh: "離開前清理你的書桌。" },
      { en: "Her desk is by the window.", zh: "她的書桌靠近窗戶。" },
    ],
    relatedWords: ["chair", "lamp", "bookshelf", "notebook"],
    confusingWords: [
      { word: "table", note: "desk 通常指讀書或工作的桌子；table 比較泛用。" },
    ],
  },
  {
    id: "laptop",
    word: "laptop",
    chinese: "筆記型電腦",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈlæp.tɑːp/",
    collocations: ["open the laptop", "on my laptop"],
    examples: [
      { en: "I work on my laptop.", zh: "我用筆電工作。" },
      { en: "The laptop is out of battery.", zh: "筆電沒電了。" },
      { en: "Close your laptop, please.", zh: "請把筆電合上。" },
    ],
    relatedWords: ["computer", "keyboard", "screen"],
  },
  {
    id: "keyboard",
    word: "keyboard",
    chinese: "鍵盤",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈkiː.bɔːrd/",
    collocations: ["type on a keyboard"],
    examples: [
      { en: "I type fast on this keyboard.", zh: "我在這鍵盤上打字很快。" },
      { en: "The keyboard is wireless.", zh: "這個鍵盤是無線的。" },
      { en: "Don't spill water on the keyboard.", zh: "別把水灑在鍵盤上。" },
    ],
    relatedWords: ["mouse", "computer", "type"],
  },
  {
    id: "mouse",
    word: "mouse",
    chinese: "滑鼠",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/maʊs/",
    collocations: ["click the mouse", "wireless mouse"],
    examples: [
      { en: "Click here with the mouse.", zh: "用滑鼠點這裡。" },
      { en: "My mouse stopped working.", zh: "我的滑鼠不能用了。" },
      { en: "This is a wireless mouse.", zh: "這是個無線滑鼠。" },
    ],
    relatedWords: ["keyboard", "computer", "click"],
    confusingWords: [
      { word: "mouse (animal)", note: "mouse 也指「老鼠」，看上下文判斷。" },
    ],
  },
  {
    id: "monitor",
    word: "monitor",
    chinese: "螢幕",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈmɑː.nə.tər/",
    collocations: ["external monitor"],
    examples: [
      { en: "I have two monitors at my desk.", zh: "我桌上有兩台螢幕。" },
      { en: "Turn off the monitor when you leave.", zh: "離開時請把螢幕關掉。" },
      { en: "The monitor is too bright.", zh: "螢幕太亮了。" },
    ],
    relatedWords: ["screen", "computer"],
  },
  {
    id: "notebook",
    word: "notebook",
    chinese: "筆記本",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈnoʊt.bʊk/",
    collocations: ["write in a notebook"],
    examples: [
      { en: "Write your notes in the notebook.", zh: "把筆記寫在筆記本上。" },
      { en: "I lost my notebook.", zh: "我的筆記本不見了。" },
      { en: "She has a small notebook in her bag.", zh: "她包包裡有本小筆記本。" },
    ],
    relatedWords: ["pen", "paper", "desk"],
  },
  {
    id: "pen",
    word: "pen",
    chinese: "原子筆",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/pen/",
    collocations: ["blue pen", "out of ink"],
    examples: [
      { en: "Can I borrow your pen?", zh: "可以借你的筆嗎？" },
      { en: "The pen ran out of ink.", zh: "筆沒墨水了。" },
      { en: "Sign here with a pen.", zh: "用筆在這裡簽名。" },
    ],
    relatedWords: ["pencil", "paper", "ink"],
    confusingWords: [
      { word: "pencil", note: "pen 是原子筆／鋼筆；pencil 是鉛筆。" },
    ],
  },
  {
    id: "stapler",
    word: "stapler",
    chinese: "釘書機",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈsteɪ.plər/",
    examples: [
      { en: "Where is the stapler?", zh: "釘書機在哪裡？" },
      { en: "The stapler is out of staples.", zh: "釘書機沒釘針了。" },
      { en: "She stapled the papers together.", zh: "她把紙釘在一起。" },
    ],
    relatedWords: ["paper", "office"],
  },
  {
    id: "printer",
    word: "printer",
    chinese: "印表機",
    category: "office",
    partOfSpeech: "noun",
    pronunciation: "/ˈprɪn.tər/",
    collocations: ["print on the printer"],
    examples: [
      { en: "The printer is out of paper.", zh: "印表機沒紙了。" },
      { en: "Please send it to the printer.", zh: "請把它送到印表機。" },
      { en: "Our printer is broken.", zh: "我們的印表機壞了。" },
    ],
    relatedWords: ["paper", "ink", "office"],
  },

  // ---------- Street ----------
  {
    id: "traffic-light",
    word: "traffic light",
    chinese: "紅綠燈",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈtræf.ɪk ˌlaɪt/",
    collocations: ["red traffic light"],
    examples: [
      { en: "Stop at the traffic light.", zh: "在紅綠燈前停下。" },
      { en: "The traffic light is green now.", zh: "紅綠燈現在是綠燈。" },
      { en: "Wait for the traffic light to change.", zh: "等紅綠燈變號。" },
    ],
    relatedWords: ["road", "crosswalk", "stop"],
  },
  {
    id: "crosswalk",
    word: "crosswalk",
    chinese: "斑馬線",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈkrɑːs.wɑːk/",
    examples: [
      { en: "Use the crosswalk to cross the road.", zh: "走斑馬線過馬路。" },
      { en: "There is a crosswalk ahead.", zh: "前方有斑馬線。" },
      { en: "Cars must stop at the crosswalk.", zh: "車子必須在斑馬線前停車。" },
    ],
    relatedWords: ["traffic light", "road", "pedestrian"],
  },
  {
    id: "sidewalk",
    word: "sidewalk",
    chinese: "人行道",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈsaɪd.wɑːk/",
    collocations: ["walk on the sidewalk"],
    examples: [
      { en: "Walk on the sidewalk.", zh: "走在人行道上。" },
      { en: "The sidewalk is crowded.", zh: "人行道很擁擠。" },
      { en: "Don't ride your bike on the sidewalk.", zh: "不要在人行道上騎腳踏車。" },
    ],
    relatedWords: ["road", "street"],
    confusingWords: [
      { word: "pavement", note: "美式英文是 sidewalk；英式英文是 pavement。" },
    ],
  },
  {
    id: "street-sign",
    word: "street sign",
    chinese: "路標",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈstriːt ˌsaɪn/",
    examples: [
      { en: "Read the street sign carefully.", zh: "仔細看路標。" },
      { en: "The street sign was bent.", zh: "路標彎掉了。" },
      { en: "There's a stop sign at the corner.", zh: "轉角有停車標誌。" },
    ],
    relatedWords: ["road", "sign"],
  },
  {
    id: "bench",
    word: "bench",
    chinese: "長椅",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/bentʃ/",
    collocations: ["sit on a bench", "park bench"],
    examples: [
      { en: "Let's sit on the bench.", zh: "我們坐長椅吧。" },
      { en: "An old man sat on the bench.", zh: "一位老先生坐在長椅上。" },
      { en: "The bench is wet.", zh: "長椅是濕的。" },
    ],
    relatedWords: ["park", "chair"],
  },
  {
    id: "streetlight",
    word: "streetlight",
    chinese: "路燈",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈstriːt.laɪt/",
    examples: [
      { en: "The streetlights turned on.", zh: "路燈亮起來了。" },
      { en: "Park under the streetlight.", zh: "把車停在路燈下。" },
      { en: "One streetlight is broken.", zh: "有一盞路燈壞了。" },
    ],
    relatedWords: ["light", "night", "street"],
  },
  {
    id: "trash-can",
    word: "trash can",
    chinese: "垃圾桶",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈtræʃ ˌkæn/",
    collocations: ["throw in the trash can"],
    examples: [
      { en: "Throw it in the trash can.", zh: "把它丟進垃圾桶。" },
      { en: "The trash can is full.", zh: "垃圾桶滿了。" },
      { en: "Where's the nearest trash can?", zh: "最近的垃圾桶在哪？" },
    ],
    relatedWords: ["garbage", "recycle"],
    confusingWords: [
      { word: "bin", note: "英式英文常說 bin；美式英文常說 trash can。" },
    ],
  },
  {
    id: "mailbox",
    word: "mailbox",
    chinese: "郵筒",
    category: "street",
    partOfSpeech: "noun",
    pronunciation: "/ˈmeɪl.bɑːks/",
    examples: [
      { en: "Drop the letter in the mailbox.", zh: "把信投進郵筒。" },
      { en: "The mailbox is red.", zh: "郵筒是紅色的。" },
      { en: "The mailbox is on the corner.", zh: "郵筒在街角。" },
    ],
    relatedWords: ["letter", "post", "mail"],
  },

  // ---------- Supermarket ----------
  {
    id: "shopping-cart",
    word: "shopping cart",
    chinese: "購物車",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/ˈʃɑː.pɪŋ ˌkɑːrt/",
    collocations: ["push the shopping cart"],
    examples: [
      { en: "Push the shopping cart slowly.", zh: "慢慢推購物車。" },
      { en: "The shopping cart is full.", zh: "購物車裝滿了。" },
      { en: "Where can I find a shopping cart?", zh: "我可以在哪裡找到購物車？" },
    ],
    relatedWords: ["basket", "shop", "store"],
    confusingWords: [
      { word: "trolley", note: "英式英文用 trolley；美式英文用 cart。" },
    ],
  },
  {
    id: "cashier",
    word: "cashier",
    chinese: "收銀員",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/kæˈʃɪr/",
    examples: [
      { en: "The cashier scanned my groceries.", zh: "收銀員掃描了我買的商品。" },
      { en: "The cashier was friendly.", zh: "收銀員很親切。" },
      { en: "The cashier gave me the receipt.", zh: "收銀員把收據交給我。" },
    ],
    relatedWords: ["pay", "receipt", "money"],
  },
  {
    id: "receipt",
    word: "receipt",
    chinese: "收據 / 發票",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/rɪˈsiːt/",
    collocations: ["keep the receipt"],
    examples: [
      { en: "Keep your receipt, please.", zh: "請保留收據。" },
      { en: "I lost the receipt.", zh: "我把收據弄丟了。" },
      { en: "Show your receipt at the exit.", zh: "在出口出示收據。" },
    ],
    relatedWords: ["cashier", "pay", "money"],
    note: "receipt 的 p 不發音。",
  },
  {
    id: "aisle",
    word: "aisle",
    chinese: "走道",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/aɪl/",
    examples: [
      { en: "The bread is in aisle three.", zh: "麵包在第三排走道。" },
      { en: "Walk down the aisle.", zh: "沿著走道往前走。" },
      { en: "Which aisle has snacks?", zh: "哪一排走道有零食？" },
    ],
    relatedWords: ["shelf", "store"],
    note: "aisle 的 s 不發音，讀作 /aɪl/。",
  },
  {
    id: "shelf",
    word: "shelf",
    chinese: "架子",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/ʃelf/",
    collocations: ["on the shelf", "top shelf"],
    examples: [
      { en: "The cereal is on the top shelf.", zh: "麥片在最上層架子。" },
      { en: "The shelf is empty.", zh: "架子是空的。" },
      { en: "Put it back on the shelf.", zh: "把它放回架子上。" },
    ],
    relatedWords: ["aisle", "store"],
    note: "複數是 shelves。",
  },
  {
    id: "bag",
    word: "bag",
    chinese: "袋子",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/bæɡ/",
    collocations: ["paper bag", "plastic bag"],
    examples: [
      { en: "Paper or plastic bag?", zh: "要紙袋還是塑膠袋？" },
      { en: "Bring your own bag.", zh: "請自備購物袋。" },
      { en: "The bag is too heavy.", zh: "袋子太重了。" },
    ],
    relatedWords: ["plastic", "shopping"],
  },
  {
    id: "price-tag",
    word: "price tag",
    chinese: "價格標籤",
    category: "supermarket",
    partOfSpeech: "noun",
    pronunciation: "/ˈpraɪs ˌtæɡ/",
    examples: [
      { en: "Check the price tag.", zh: "看一下價格標籤。" },
      { en: "There's no price tag on this.", zh: "這個沒有貼價格標籤。" },
      { en: "The price tag says $5.", zh: "價格標籤寫著 5 美元。" },
    ],
    relatedWords: ["price", "tag", "store"],
  },

  // ---------- Transportation ----------
  {
    id: "car",
    word: "car",
    chinese: "汽車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/kɑːr/",
    collocations: ["drive a car", "park the car"],
    examples: [
      { en: "I drive a car to work.", zh: "我開車上班。" },
      { en: "Park the car over there.", zh: "把車停在那邊。" },
      { en: "Whose car is this?", zh: "這是誰的車？" },
    ],
    relatedWords: ["drive", "road", "park"],
  },
  {
    id: "bus",
    word: "bus",
    chinese: "公車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/bʌs/",
    collocations: ["take the bus", "miss the bus"],
    examples: [
      { en: "I take the bus to school.", zh: "我搭公車上學。" },
      { en: "Don't miss the bus.", zh: "別錯過公車。" },
      { en: "The bus is late.", zh: "公車誤點了。" },
    ],
    relatedWords: ["bus stop", "driver", "ticket"],
  },
  {
    id: "bicycle",
    word: "bicycle",
    alsoKnownAs: ["bike"],
    chinese: "腳踏車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/ˈbaɪ.sɪ.kəl/",
    collocations: ["ride a bicycle"],
    examples: [
      { en: "He rides his bicycle every day.", zh: "他每天騎腳踏車。" },
      { en: "I learned to ride a bicycle at six.", zh: "我六歲學會騎腳踏車。" },
      { en: "Where is my bicycle?", zh: "我的腳踏車在哪？" },
    ],
    relatedWords: ["ride", "wheel", "helmet"],
    confusingWords: [
      { word: "bike", note: "bicycle 較正式；bike 是口語縮寫。" },
    ],
  },
  {
    id: "motorcycle",
    word: "motorcycle",
    chinese: "機車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/ˈmoʊ.tər.saɪ.kəl/",
    collocations: ["ride a motorcycle"],
    examples: [
      { en: "He rides a motorcycle to work.", zh: "他騎機車上班。" },
      { en: "Always wear a helmet on a motorcycle.", zh: "騎機車一定要戴安全帽。" },
      { en: "Her motorcycle is red.", zh: "她的機車是紅色的。" },
    ],
    relatedWords: ["scooter", "helmet"],
  },
  {
    id: "train",
    word: "train",
    chinese: "火車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/treɪn/",
    collocations: ["take the train", "miss the train"],
    examples: [
      { en: "We took the train to Taipei.", zh: "我們搭火車去台北。" },
      { en: "The train is leaving.", zh: "火車要開了。" },
      { en: "I missed the last train.", zh: "我錯過了最後一班火車。" },
    ],
    relatedWords: ["station", "ticket", "platform"],
  },
  {
    id: "airplane",
    word: "airplane",
    alsoKnownAs: ["plane"],
    chinese: "飛機",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/ˈer.pleɪn/",
    collocations: ["take a plane", "by airplane"],
    examples: [
      { en: "We flew on an airplane.", zh: "我們搭飛機。" },
      { en: "The airplane is taking off.", zh: "飛機要起飛了。" },
      { en: "I'm afraid of airplanes.", zh: "我怕坐飛機。" },
    ],
    relatedWords: ["airport", "fly", "ticket"],
  },
  {
    id: "boat",
    word: "boat",
    chinese: "小船",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/boʊt/",
    examples: [
      { en: "We took a boat across the lake.", zh: "我們搭船渡湖。" },
      { en: "The boat is small.", zh: "船很小。" },
      { en: "There's a fishing boat.", zh: "有一艘漁船。" },
    ],
    relatedWords: ["ship", "water", "river"],
    confusingWords: [
      { word: "ship", note: "boat 通常較小；ship 通常指大船。" },
    ],
  },
  {
    id: "taxi",
    word: "taxi",
    alsoKnownAs: ["cab"],
    chinese: "計程車",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/ˈtæk.si/",
    collocations: ["take a taxi", "call a taxi"],
    examples: [
      { en: "Let's take a taxi.", zh: "我們搭計程車吧。" },
      { en: "I called a taxi.", zh: "我叫了計程車。" },
      { en: "The taxi is waiting outside.", zh: "計程車在外面等。" },
    ],
    relatedWords: ["car", "driver", "fare"],
  },
  {
    id: "subway",
    word: "subway",
    chinese: "地鐵",
    category: "transportation",
    partOfSpeech: "noun",
    pronunciation: "/ˈsʌb.weɪ/",
    collocations: ["take the subway"],
    examples: [
      { en: "I take the subway every day.", zh: "我每天搭地鐵。" },
      { en: "The subway is crowded.", zh: "地鐵很擠。" },
      { en: "Where is the subway station?", zh: "地鐵站在哪？" },
    ],
    relatedWords: ["train", "station", "ticket"],
    confusingWords: [
      { word: "underground / metro", note: "英國稱 underground；其他地區也常稱 metro。" },
    ],
  },

  // ---------- Seasonings ----------
  {
    id: "salt",
    word: "salt",
    chinese: "鹽",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/sɔːlt/",
    collocations: ["a pinch of salt", "table salt", "sea salt"],
    examples: [
      { en: "Pass me the salt, please.", zh: "請把鹽遞給我。" },
      { en: "This soup needs more salt.", zh: "這碗湯需要多一點鹽。" },
      { en: "Add a pinch of salt to the batter.", zh: "在麵糊裡加一小撮鹽。" },
    ],
    relatedWords: ["pepper", "sugar", "spice"],
  },
  {
    id: "sugar",
    word: "sugar",
    chinese: "糖",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈʃʊɡ.ər/",
    collocations: ["brown sugar", "white sugar", "a spoon of sugar"],
    examples: [
      { en: "Do you take sugar in your coffee?", zh: "你的咖啡要加糖嗎？" },
      { en: "Add a spoon of sugar.", zh: "加一匙糖。" },
      { en: "I'm trying to eat less sugar.", zh: "我正在減少吃糖。" },
    ],
    relatedWords: ["salt", "honey", "sweet"],
  },
  {
    id: "pepper",
    word: "pepper",
    chinese: "胡椒",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈpep.ər/",
    collocations: ["salt and pepper", "ground pepper"],
    examples: [
      { en: "This dish needs more pepper.", zh: "這道菜需要多一點胡椒。" },
      { en: "Add salt and pepper to taste.", zh: "加鹽和胡椒調味。" },
      { en: "He sneezed because of the pepper.", zh: "他因為胡椒而打了個噴嚏。" },
    ],
    relatedWords: ["black-pepper", "white-pepper", "salt"],
    confusingWords: [
      { word: "bell pepper", note: "pepper 也可以指甜椒（bell pepper），看上下文。" },
    ],
  },
  {
    id: "black-pepper",
    word: "black pepper",
    chinese: "黑胡椒",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/blæk ˈpep.ər/",
    collocations: ["freshly ground black pepper"],
    examples: [
      { en: "Grind some black pepper on top.", zh: "在上面磨點黑胡椒。" },
      { en: "I prefer black pepper to white pepper.", zh: "我喜歡黑胡椒勝過白胡椒。" },
      { en: "Black pepper goes well with steak.", zh: "黑胡椒和牛排很搭。" },
    ],
    relatedWords: ["pepper", "white-pepper", "salt"],
  },
  {
    id: "white-pepper",
    word: "white pepper",
    chinese: "白胡椒",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/waɪt ˈpep.ər/",
    examples: [
      { en: "White pepper is common in Chinese soups.", zh: "白胡椒在中式湯品裡很常見。" },
      { en: "Use white pepper for a milder taste.", zh: "想要味道溫和一點就用白胡椒。" },
      { en: "Sprinkle white pepper over the noodles.", zh: "在麵上撒點白胡椒。" },
    ],
    relatedWords: ["pepper", "black-pepper"],
    confusingWords: [
      { word: "black pepper", note: "白胡椒辛香較柔和；黑胡椒帶有強烈果香。" },
    ],
  },
  {
    id: "soy-sauce",
    word: "soy sauce",
    chinese: "醬油",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/sɔɪ ˌsɔːs/",
    collocations: ["a bottle of soy sauce", "light soy sauce", "dark soy sauce"],
    examples: [
      { en: "Do you want soy sauce with that?", zh: "你要加醬油嗎？" },
      { en: "Dip the dumplings in soy sauce.", zh: "把餃子沾醬油。" },
      { en: "Add a tablespoon of soy sauce.", zh: "加一湯匙醬油。" },
    ],
    relatedWords: ["oyster-sauce", "fish-sauce", "vinegar"],
  },
  {
    id: "vinegar",
    word: "vinegar",
    chinese: "醋",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈvɪn.ə.ɡər/",
    collocations: ["a splash of vinegar", "white vinegar"],
    examples: [
      { en: "Add a splash of vinegar.", zh: "加一點醋。" },
      { en: "Vinegar is used in salad dressing.", zh: "醋常用在沙拉醬裡。" },
      { en: "This sauce is too sour from the vinegar.", zh: "這醬汁因為醋太酸了。" },
    ],
    relatedWords: ["rice-vinegar", "soy-sauce"],
  },
  {
    id: "rice-vinegar",
    word: "rice vinegar",
    chinese: "米醋",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/raɪs ˈvɪn.ə.ɡər/",
    examples: [
      { en: "Use rice vinegar for sushi rice.", zh: "做壽司飯要用米醋。" },
      { en: "Rice vinegar is milder than white vinegar.", zh: "米醋比白醋來得溫和。" },
      { en: "Add rice vinegar to the dipping sauce.", zh: "在沾醬裡加米醋。" },
    ],
    relatedWords: ["vinegar", "soy-sauce"],
  },
  {
    id: "chili-sauce",
    word: "chili sauce",
    chinese: "辣椒醬",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈtʃɪl.i ˌsɔːs/",
    collocations: ["hot chili sauce", "a bottle of chili sauce"],
    examples: [
      { en: "I like chili sauce on everything.", zh: "我什麼東西都愛加辣椒醬。" },
      { en: "Sriracha is a popular chili sauce.", zh: "Sriracha 是很受歡迎的辣椒醬。" },
      { en: "This chili sauce is too spicy for me.", zh: "這辣椒醬對我來說太辣了。" },
    ],
    relatedWords: ["chili-powder", "chili-flakes", "ketchup"],
  },
  {
    id: "chili-powder",
    word: "chili powder",
    chinese: "辣椒粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈtʃɪl.i ˌpaʊ.dər/",
    examples: [
      { en: "Add a teaspoon of chili powder.", zh: "加一茶匙辣椒粉。" },
      { en: "Chili powder makes the dish spicy.", zh: "辣椒粉讓菜變辣。" },
      { en: "Sprinkle chili powder over the chicken.", zh: "在雞肉上撒辣椒粉。" },
    ],
    relatedWords: ["chili-sauce", "chili-flakes", "curry-powder"],
  },
  {
    id: "chili-flakes",
    word: "chili flakes",
    chinese: "辣椒片",
    category: "seasonings",
    partOfSpeech: "noun (plural)",
    pronunciation: "/ˈtʃɪl.i ˌfleɪks/",
    examples: [
      { en: "Sprinkle chili flakes on your pizza.", zh: "在你的披薩上撒辣椒片。" },
      { en: "Add chili flakes for extra heat.", zh: "想要更辣就加辣椒片。" },
      { en: "He keeps chili flakes on the table.", zh: "他在桌上放著辣椒片。" },
    ],
    relatedWords: ["chili-powder", "chili-sauce"],
  },
  {
    id: "mustard",
    word: "mustard",
    chinese: "芥末",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈmʌs.tɚd/",
    collocations: ["yellow mustard", "Dijon mustard"],
    examples: [
      { en: "Would you like mustard on your hotdog?", zh: "熱狗要加芥末嗎？" },
      { en: "Spread some mustard on the sandwich.", zh: "在三明治上抹點芥末。" },
      { en: "I don't like the taste of mustard.", zh: "我不喜歡芥末的味道。" },
    ],
    relatedWords: ["ketchup", "mayonnaise"],
  },
  {
    id: "ketchup",
    word: "ketchup",
    chinese: "番茄醬",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈketʃ.ʌp/",
    collocations: ["a bottle of ketchup", "tomato ketchup"],
    examples: [
      { en: "Can I have ketchup with the fries?", zh: "薯條可以給我番茄醬嗎？" },
      { en: "He puts ketchup on everything.", zh: "他什麼東西都加番茄醬。" },
      { en: "The ketchup bottle is almost empty.", zh: "番茄醬快用完了。" },
    ],
    relatedWords: ["mustard", "mayonnaise", "chili-sauce"],
  },
  {
    id: "mayonnaise",
    word: "mayonnaise",
    alsoKnownAs: ["mayo"],
    chinese: "美乃滋 / 蛋黃醬",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˌmeɪ.əˈneɪz/",
    examples: [
      { en: "Spread mayo on the bread.", zh: "在麵包上抹美乃滋。" },
      { en: "Add mayonnaise to the salad.", zh: "在沙拉裡加美乃滋。" },
      { en: "I prefer mustard over mayonnaise.", zh: "我比較喜歡芥末，不愛美乃滋。" },
    ],
    relatedWords: ["ketchup", "mustard"],
    confusingWords: [
      { word: "mayo", note: "mayo 是 mayonnaise 的口語縮寫，意思相同。" },
    ],
  },
  {
    id: "oyster-sauce",
    word: "oyster sauce",
    chinese: "蠔油",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈɔɪ.stɚ ˌsɔːs/",
    examples: [
      { en: "Add oyster sauce to the stir-fry.", zh: "在炒菜裡加蠔油。" },
      { en: "Oyster sauce makes the dish savory.", zh: "蠔油讓菜餚更鮮甜。" },
      { en: "A drizzle of oyster sauce is enough.", zh: "淋一點蠔油就夠了。" },
    ],
    relatedWords: ["soy-sauce", "fish-sauce"],
  },
  {
    id: "fish-sauce",
    word: "fish sauce",
    chinese: "魚露",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/fɪʃ ˌsɔːs/",
    examples: [
      { en: "Fish sauce is essential in Thai cooking.", zh: "魚露在泰式料理裡很重要。" },
      { en: "Just a few drops of fish sauce is enough.", zh: "只要幾滴魚露就夠了。" },
      { en: "The smell of fish sauce is strong.", zh: "魚露的味道很重。" },
    ],
    relatedWords: ["soy-sauce", "oyster-sauce"],
  },
  {
    id: "sesame-oil",
    word: "sesame oil",
    chinese: "麻油 / 芝麻油",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈsez.ə.mi ˌɔɪl/",
    examples: [
      { en: "Drizzle some sesame oil on top.", zh: "在上面淋點麻油。" },
      { en: "Sesame oil has a strong fragrance.", zh: "麻油香氣濃郁。" },
      { en: "Use sesame oil for the dipping sauce.", zh: "沾醬用麻油。" },
    ],
    relatedWords: ["olive-oil", "cooking-wine"],
  },
  {
    id: "olive-oil",
    word: "olive oil",
    chinese: "橄欖油",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈɑː.lɪv ˌɔɪl/",
    collocations: ["extra virgin olive oil", "a bottle of olive oil"],
    examples: [
      { en: "Cook with olive oil.", zh: "用橄欖油料理。" },
      { en: "Extra virgin olive oil is the best.", zh: "特級初榨橄欖油是最好的。" },
      { en: "Drizzle olive oil over the salad.", zh: "在沙拉上淋橄欖油。" },
    ],
    relatedWords: ["sesame-oil", "vinegar"],
  },
  {
    id: "cooking-wine",
    word: "cooking wine",
    chinese: "料酒",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈkʊk.ɪŋ ˌwaɪn/",
    examples: [
      { en: "Add cooking wine to remove the smell.", zh: "加料酒去腥。" },
      { en: "Use cooking wine, not drinking wine.", zh: "用料酒，不是飲用的酒。" },
      { en: "A splash of cooking wine improves the flavor.", zh: "加一點料酒能提升風味。" },
    ],
    relatedWords: ["vinegar", "soy-sauce", "sesame-oil"],
  },
  {
    id: "msg",
    word: "MSG",
    alsoKnownAs: ["monosodium glutamate"],
    chinese: "味精",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˌem.esˈdʒiː/",
    examples: [
      { en: "Some restaurants don't use MSG.", zh: "有些餐廳不用味精。" },
      { en: "MSG enhances the umami flavor.", zh: "味精能提升鮮味。" },
      { en: "She is sensitive to MSG.", zh: "她對味精敏感。" },
    ],
    relatedWords: ["salt", "sugar"],
    note: "MSG 是 monosodium glutamate 的縮寫，三個字母分開唸。",
  },
  {
    id: "garlic-powder",
    word: "garlic powder",
    chinese: "蒜粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈɡɑːr.lɪk ˌpaʊ.dər/",
    examples: [
      { en: "Sprinkle garlic powder on the meat.", zh: "在肉上撒點蒜粉。" },
      { en: "Garlic powder is easier than fresh garlic.", zh: "蒜粉比新鮮大蒜方便。" },
      { en: "Add a teaspoon of garlic powder.", zh: "加一茶匙蒜粉。" },
    ],
    relatedWords: ["onion-powder", "curry-powder"],
  },
  {
    id: "onion-powder",
    word: "onion powder",
    chinese: "洋蔥粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈʌn.jən ˌpaʊ.dər/",
    examples: [
      { en: "Add a pinch of onion powder.", zh: "加一點洋蔥粉。" },
      { en: "Onion powder is great in dry rubs.", zh: "洋蔥粉很適合做乾醃料。" },
      { en: "I'm out of onion powder.", zh: "我的洋蔥粉用完了。" },
    ],
    relatedWords: ["garlic-powder", "curry-powder"],
  },
  {
    id: "curry-powder",
    word: "curry powder",
    chinese: "咖哩粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈkɝː.i ˌpaʊ.dər/",
    examples: [
      { en: "Stir in two spoons of curry powder.", zh: "拌入兩匙咖哩粉。" },
      { en: "Curry powder gives the dish its yellow color.", zh: "咖哩粉讓菜變成黃色。" },
      { en: "Indian curry powder is more aromatic.", zh: "印度咖哩粉香氣更濃。" },
    ],
    relatedWords: ["five-spice-powder", "cumin", "chili-powder"],
  },
  {
    id: "five-spice-powder",
    word: "five-spice powder",
    chinese: "五香粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˌfaɪvˈspaɪs ˌpaʊ.dər/",
    examples: [
      { en: "Five-spice powder is common in Chinese cooking.", zh: "五香粉在中式料理裡很常用。" },
      { en: "Use a little five-spice powder for flavor.", zh: "用一點五香粉提味。" },
      { en: "Five-spice powder includes star anise and cinnamon.", zh: "五香粉裡有八角和肉桂。" },
    ],
    relatedWords: ["curry-powder", "cinnamon", "cumin"],
  },
  {
    id: "cinnamon",
    word: "cinnamon",
    chinese: "肉桂 / 肉桂粉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈsɪn.ə.mən/",
    collocations: ["a cinnamon stick", "ground cinnamon"],
    examples: [
      { en: "Sprinkle cinnamon on the latte.", zh: "在拿鐵上撒肉桂粉。" },
      { en: "Cinnamon goes well with apples.", zh: "肉桂和蘋果很搭。" },
      { en: "Add a cinnamon stick to the tea.", zh: "在茶裡加一根肉桂棒。" },
    ],
    relatedWords: ["five-spice-powder", "sugar"],
  },
  {
    id: "cumin",
    word: "cumin",
    chinese: "孜然",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈkʌm.ɪn/",
    examples: [
      { en: "Cumin adds a warm, earthy flavor.", zh: "孜然帶來溫暖、土香的風味。" },
      { en: "Cumin is essential in chili and curry.", zh: "孜然在辣椒料理和咖哩裡不可少。" },
      { en: "Toast the cumin seeds before grinding.", zh: "把孜然籽烤過再磨。" },
    ],
    relatedWords: ["curry-powder", "five-spice-powder"],
  },
  {
    id: "cilantro",
    word: "cilantro",
    alsoKnownAs: ["coriander"],
    chinese: "香菜",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/sɪˈlæn.troʊ/",
    examples: [
      { en: "Garnish with fresh cilantro.", zh: "用新鮮香菜裝飾。" },
      { en: "Some people hate the taste of cilantro.", zh: "有些人討厭香菜的味道。" },
      { en: "Chop the cilantro finely.", zh: "把香菜切細。" },
    ],
    relatedWords: ["basil", "rosemary", "thyme"],
    confusingWords: [
      { word: "coriander", note: "美式英文常說 cilantro 指葉子；coriander 在英式英文中是葉子和籽的通稱。" },
    ],
  },
  {
    id: "basil",
    word: "basil",
    chinese: "羅勒",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈbeɪ.zəl/",
    examples: [
      { en: "Top the pizza with fresh basil.", zh: "披薩上放新鮮羅勒。" },
      { en: "Basil is the main herb in pesto.", zh: "羅勒是青醬的主要香草。" },
      { en: "Thai basil has a sharper flavor.", zh: "泰式羅勒（九層塔）味道更強烈。" },
    ],
    relatedWords: ["cilantro", "rosemary", "thyme"],
  },
  {
    id: "rosemary",
    word: "rosemary",
    chinese: "迷迭香",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈroʊz.mer.i/",
    collocations: ["a sprig of rosemary", "fresh rosemary"],
    examples: [
      { en: "Rosemary goes great with roasted chicken.", zh: "迷迭香配烤雞很棒。" },
      { en: "Add a sprig of rosemary.", zh: "加一小枝迷迭香。" },
      { en: "Rosemary smells very fragrant.", zh: "迷迭香聞起來很香。" },
    ],
    relatedWords: ["basil", "thyme", "bay-leaf"],
  },
  {
    id: "thyme",
    word: "thyme",
    chinese: "百里香",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/taɪm/",
    examples: [
      { en: "Thyme is good for soups and stews.", zh: "百里香適合做湯和燉菜。" },
      { en: "Add fresh thyme leaves.", zh: "加新鮮百里香葉。" },
      { en: "Dried thyme works in a pinch.", zh: "臨時找不到新鮮的，乾百里香也可以。" },
    ],
    relatedWords: ["rosemary", "basil", "bay-leaf"],
    note: "thyme 的 th 不發音，讀作 /taɪm/，跟 time 同音。",
  },
  {
    id: "bay-leaf",
    word: "bay leaf",
    chinese: "月桂葉",
    category: "seasonings",
    partOfSpeech: "noun",
    pronunciation: "/ˈbeɪ ˌliːf/",
    examples: [
      { en: "Remove the bay leaf before serving.", zh: "上菜前把月桂葉拿出來。" },
      { en: "Bay leaves add depth to the broth.", zh: "月桂葉讓湯底更有層次。" },
      { en: "Drop a bay leaf into the pot.", zh: "在鍋裡丟一片月桂葉。" },
    ],
    relatedWords: ["thyme", "rosemary"],
    note: "複數是 bay leaves。",
  },
];

// Convert one legacy seed entry into the v2 Word shape (single zh definition,
// translations object on each example, typed relations).
function legacyToV2(legacy: LegacyWord): Word {
  const examples: Example[] = legacy.examples.map((e, i) => ({
    en: e.en,
    zh: e.zh,
    translations: { zh: e.zh, ...(e.ja ? { ja: e.ja } : {}) },
    cefrLevel: e.cefrLevel,
    sortOrder: i,
  }));
  const relations: WordRelation[] = [
    ...(legacy.relatedWords ?? []).map((id) => ({ wordId: id, type: "see-also" as const })),
    ...(legacy.confusingWords ?? []).map((c) => ({
      wordId: c.word,
      type: "confusing" as const,
      note: c.note,
    })),
  ];
  return {
    id: legacy.id,
    word: legacy.word,
    alsoKnownAs: legacy.alsoKnownAs,
    category: legacy.category,
    partOfSpeech: legacy.partOfSpeech,
    pronunciation: legacy.pronunciation,
    imageUrl: legacy.imageUrl ?? "",
    status: "published",
    definitions: legacy.definitions ?? [
      { language: "zh", definition: legacy.chinese, sortOrder: 0 },
    ],
    chinese: legacy.chinese,
    chineseDefinition: legacy.chineseDefinition,
    examples,
    tags: [],
    relations,
    collocations: legacy.collocations,
    note: legacy.note,
    relatedWords: legacy.relatedWords,
    confusingWords: legacy.confusingWords,
  };
}

// lib/image-urls.json is the canonical image per word — regenerated from the
// DB with `npm run sync-image-urls`. An inline imageUrl on a seed entry is
// only the initial image for a brand-new word that hasn't been synced yet,
// and must already be a Supabase Storage word-images URL (WORD_IMPORT.md §6).
export const words: Word[] = [
  ...rawWords,
  ...supplementalWords,
  ...(MAIN_WORD_EXPANSION_WORDS as LegacyWord[]),
  ...(MAIN_WORD_EXPANSION_BATCH_2_WORDS as LegacyWord[]),
  ...(MAIN_WORD_EXPANSION_BATCH_3_WORDS as LegacyWord[]),
].map((w) => {
  const withImage = imageMap[w.id] ? { ...w, imageUrl: imageMap[w.id] } : w;
  return legacyToV2(withImage);
});

export const getWord = (id: string): Word | undefined =>
  words.find((w) => w.id === id);

export const getWordsByCategory = (categoryId: string): Word[] =>
  words.filter((w) => w.category === categoryId);

export const searchWords = (query: string): Word[] => {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return words.filter((w) => {
    const haystack = [
      w.word,
      w.chinese,
      ...(w.alsoKnownAs ?? []),
      w.category,
      ...(w.relatedWords ?? []),
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
};
