import type {
  MainWordComplexExample,
  MainWordSimpleExampleOverride,
} from "./types";

export const BATHROOM_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "toothbrush", en: "I replace my toothbrush when the bristles spread out because it no longer cleans well.", ja: "毛先が広がるときれいに磨けないので、歯ブラシを交換します。", zh: "牙刷刷毛張開後就刷不乾淨，所以我會更換牙刷。" },
  { id: "toothpaste", en: "If your teeth are sensitive, choose a toothpaste made for sensitive teeth.", ja: "歯がしみる場合は、知覚過敏用の歯磨き粉を選んでください。", zh: "如果牙齒敏感，請選擇抗敏感牙膏。" },
  { id: "towel", en: "After using the towel, hang it up so it can dry before the next person needs it.", ja: "次の人が使うまでに乾くように、タオルを使ったら掛けてください。", zh: "毛巾用完後請掛起來，讓下一個人使用前能晾乾。" },
  { id: "soap", en: "Because the soap is slippery when wet, put it back in the dish after washing your hands.", ja: "ぬれた石けんは滑りやすいので、手を洗ったら受け皿に戻してください。", zh: "肥皂沾水後很滑，洗完手請放回皂盤。" },
  { id: "shampoo", en: "When my scalp feels dry, I use less shampoo and rinse it out carefully.", ja: "頭皮が乾燥しているときは、シャンプーを少なめにして丁寧にすすぎます。", zh: "頭皮乾燥時，我會減少洗髮精用量並仔細沖洗。" },
  { id: "shower", en: "Since I was running late, I took a quick shower instead of filling the bathtub.", ja: "時間がなかったので、お風呂をためずに短いシャワーで済ませました。", zh: "因為快遲到了，我沒有放洗澡水，只快速沖了個澡。" },
  { id: "mirror", en: "The mirror fogs up after a hot shower, so I open the window for a few minutes.", ja: "熱いシャワーのあと鏡が曇るので、数分間窓を開けます。", zh: "洗完熱水澡後鏡子會起霧，所以我會開窗幾分鐘。" },
  { id: "toilet", en: "If the toilet does not flush properly, stop using it and tell the staff.", ja: "トイレの水がきちんと流れない場合は、使用をやめて係の人に伝えてください。", zh: "如果馬桶無法正常沖水，請停止使用並告知工作人員。" },
  { id: "comb", en: "Because my hair tangles easily, I use a wide-toothed comb after washing it.", ja: "髪が絡まりやすいので、洗ったあとは目の粗いくしを使います。", zh: "我的頭髮容易打結，所以洗完後會用寬齒梳。" },
  { id: "hair-dryer", en: "Before using the hair dryer, I dry my hair with a towel so it takes less time.", ja: "ドライヤーの時間を短くするために、使う前にタオルで髪の水分を取ります。", zh: "使用吹風機前，我會先用毛巾吸乾頭髮，這樣比較省時間。" },
  { id: "toilet-seat", en: "If the toilet seat is wet, wipe it before sitting down and leave it clean for the next person.", ja: "便座がぬれていたら、座る前に拭き、次の人のためにもきれいにしておきます。", zh: "馬桶座圈如果濕了，坐下前先擦乾，也要留給下一個人乾淨使用。" },
  { id: "toilet-tank", en: "Because water kept running into the toilet, the plumber checked the toilet tank.", ja: "トイレの水が流れ続けていたので、修理業者がトイレタンクを確認しました。", zh: "馬桶一直進水，所以水電師傅檢查了馬桶水箱。" },
  { id: "toilet-paper", en: "When the toilet paper is almost gone, replace the roll instead of leaving it empty.", ja: "トイレットペーパーが残り少なくなったら、空のままにせず新しいロールに替えます。", zh: "衛生紙快用完時要換新的一卷，不要留下空紙筒。" },
  { id: "tissue", en: "I keep a box of tissues near the washbasin so guests can use them when needed.", ja: "来客が必要なときに使えるように、洗面台の近くにティッシュを置いています。", zh: "我在洗手台附近放一盒面紙，方便客人需要時使用。" },
  { id: "washbasin", en: "After brushing my teeth, I rinse the washbasin so no toothpaste is left behind.", ja: "歯を磨いたあとは、歯磨き粉が残らないように洗面台を流します。", zh: "刷完牙後，我會沖洗洗手台，不讓牙膏殘留。" },
  { id: "drain", en: "If water goes down slowly, remove the hair from the drain before using a strong cleaner.", ja: "水の流れが遅いときは、強い洗剤を使う前に排水口の髪の毛を取り除きます。", zh: "排水變慢時，先清掉排水孔的頭髮，再考慮使用強效清潔劑。" },
  { id: "bathroom-cabinet", en: "I keep medicine out of the bathroom cabinet because the room becomes hot and humid.", ja: "浴室は高温多湿になるので、薬は洗面所の収納棚に入れないようにしています。", zh: "浴室容易高溫潮濕，所以我不把藥放在浴櫃裡。" },
  { id: "towel-rack", en: "Spread the towel across the towel rack so the damp parts can dry evenly.", ja: "ぬれた部分が均等に乾くように、タオル掛けに広げて掛けてください。", zh: "把毛巾攤開掛在毛巾架上，潮濕處才能均勻晾乾。" },
  { id: "hook", en: "Since the hook is loose, do not hang a heavy bag on it until it is fixed.", ja: "フックが緩んでいるので、直すまでは重いかばんを掛けないでください。", zh: "掛鉤鬆了，修好前請不要掛重的包包。" },
  { id: "bathtub", en: "Before filling the bathtub, I rinse it quickly and check that the plug is closed.", ja: "お湯をためる前に、バスタブをさっと流して栓が閉まっているか確認します。", zh: "放洗澡水前，我會快速沖洗浴缸並確認塞子已塞好。" },
  { id: "shower-room", en: "Because the shower room floor was slippery, I rinsed away the soap before leaving.", ja: "シャワールームの床が滑りやすかったので、出る前に石けんを洗い流しました。", zh: "淋浴間地板很滑，所以我離開前把肥皂沖乾淨。" },
  { id: "shower-head", en: "If the water sprays unevenly, soak the shower head to remove the mineral buildup.", ja: "お湯が均等に出ない場合は、シャワーヘッドをつけ置きして水あかを落とします。", zh: "出水不均勻時，可以浸泡蓮蓬頭去除水垢。" },
  { id: "shower-curtain", en: "After showering, leave the shower curtain open so both sides can dry.", ja: "シャワーのあとは、両面が乾くようにシャワーカーテンを広げておきます。", zh: "洗完澡後把浴簾攤開，讓兩面都能晾乾。" },
  { id: "shower-curtain-rod", en: "Before hanging wet clothes, check how much weight the shower curtain rod can hold.", ja: "ぬれた服を掛ける前に、シャワーカーテンポールが重さに耐えられるか確認してください。", zh: "掛濕衣服前，請先確認浴簾桿能承受多少重量。" },
  { id: "bathroom-door", en: "Keep the bathroom door slightly open after a shower so moisture can escape.", ja: "湿気を逃がすために、シャワーのあとは浴室のドアを少し開けておきます。", zh: "洗完澡後把浴室門留一條縫，讓濕氣散出去。" },
  { id: "bath-mat", en: "When the bath mat becomes damp, hang it up before mold starts to grow.", ja: "バスマットが湿ったら、カビが生える前に干してください。", zh: "地墊變濕後要掛起來，以免開始發霉。" },
  { id: "non-slip-mat", en: "We put a non-slip mat in the bathtub because my grandmother was worried about falling.", ja: "祖母が転ぶのを心配していたので、浴槽に滑り止めマットを敷きました。", zh: "奶奶擔心跌倒，所以我們在浴缸裡鋪了防滑墊。" },
  { id: "bath-towel", en: "Since the bath towel is still wet, please take a clean one from the shelf.", ja: "そのバスタオルはまだぬれているので、棚から清潔なものを取ってください。", zh: "那條浴巾還是濕的，請從架上拿一條乾淨的。" },
  { id: "hand-towel", en: "I change the hand towel every day because several people use the bathroom.", ja: "何人も洗面所を使うので、ハンドタオルは毎日交換しています。", zh: "因為好幾個人共用浴室，我每天都會更換手巾。" },
  { id: "dental-floss", en: "Even after brushing, I use dental floss to clean between my teeth before bed.", ja: "歯を磨いたあとでも、寝る前にデンタルフロスで歯の間を掃除します。", zh: "即使刷過牙，我睡前還是會用牙線清潔牙縫。" },
  { id: "mouthwash", en: "Because this mouthwash is concentrated, dilute it according to the directions before using it.", ja: "このマウスウォッシュは濃縮タイプなので、説明どおりに薄めてから使います。", zh: "這款漱口水是濃縮型，使用前要依照說明稀釋。" },
  { id: "facial-cleanser", en: "When my skin feels irritated, I stop using the facial cleanser and rinse with warm water.", ja: "肌に刺激を感じたら、洗顔料の使用をやめてぬるま湯で流します。", zh: "皮膚感到刺激時，我會停用洗面乳並用溫水沖洗。" },
  { id: "body-wash", en: "If the body wash bottle is empty, refill it before the next person takes a shower.", ja: "ボディソープが空になったら、次の人がシャワーを浴びる前に補充してください。", zh: "沐浴乳空了的話，請在下一個人洗澡前補充。" },
  { id: "conditioner", en: "After rinsing out the shampoo, I apply conditioner mainly to the ends of my hair.", ja: "シャンプーを流したあと、コンディショナーを毛先を中心につけます。", zh: "沖掉洗髮精後，我主要把潤髮乳抹在髮尾。" },
  { id: "hair-conditioner", en: "Because my hair was damaged by coloring, I left the hair conditioner on for a few minutes.", ja: "カラーで髪が傷んでいたので、ヘアコンディショナーを数分なじませました。", zh: "頭髮因染髮受損，所以我讓護髮素停留了幾分鐘。" },
  { id: "razor", en: "Replace the razor blade when it starts pulling your skin instead of cutting smoothly.", ja: "カミソリが滑らかにそれず肌を引っ張るようになったら、刃を交換します。", zh: "刮鬍刀開始拉扯皮膚、刮不順時就要換刀片。" },
  { id: "shaving-cream", en: "Leave the shaving cream on for a minute so the hair softens before you shave.", ja: "毛が柔らかくなるように、そる前にシェービングクリームを一分ほどなじませます。", zh: "刮鬍前讓刮鬍泡停留一分鐘，使毛髮變軟。" },
  { id: "hairbrush", en: "I clean the hairbrush regularly because loose hair collects between the bristles.", ja: "毛の間に抜けた髪がたまるので、ヘアブラシを定期的に掃除します。", zh: "掉落的頭髮會卡在刷毛間，所以我定期清理髮刷。" },
  { id: "cotton-swab", en: "Do not push a cotton swab deep into your ear, because it may cause an injury.", ja: "けがをするおそれがあるので、綿棒を耳の奥まで入れないでください。", zh: "棉花棒不要伸進耳朵深處，以免受傷。" },
  { id: "cotton-pad", en: "I put makeup remover on a cotton pad and hold it over my eye before wiping gently.", ja: "化粧用コットンにリムーバーを含ませ、目元に少し置いてから優しく拭きます。", zh: "我把卸妝液倒在化妝棉上，先敷在眼睛上，再輕輕擦拭。" },
  { id: "cotton-ball", en: "After opening the package, keep the cotton balls in a clean container so they stay dry.", ja: "袋を開けたあとは、コットンボールがぬれないように清潔な容器へ入れます。", zh: "包裝打開後，把棉球放進乾淨容器，避免受潮。" },
  { id: "nail-clipper", en: "Because long nails can split, I trim them with a nail clipper after bathing.", ja: "爪が長いと割れやすいので、入浴後に爪切りで整えます。", zh: "指甲太長容易裂，所以我洗澡後會用指甲剪修剪。" },
  { id: "laundry-basket", en: "When the laundry basket is full, I carry everything to the washing machine at once.", ja: "ランドリーバスケットがいっぱいになったら、まとめて洗濯機まで運びます。", zh: "洗衣籃滿了以後，我會一次把衣物拿到洗衣機旁。" },
  { id: "hamper", en: "Since the hamper was damp, I emptied it and let it dry before adding more clothes.", ja: "洗濯かごが湿っていたので、中を空にして乾かしてから服を入れました。", zh: "髒衣籃受潮了，所以我先清空晾乾，再放入其他衣服。" },
  { id: "cleaning-brush", en: "Use the cleaning brush on the tile joints where the sponge cannot reach.", ja: "スポンジでは届かないタイルの目地は、掃除ブラシでこすります。", zh: "海綿刷不到的磁磚縫，可以用清潔刷刷洗。" },
  { id: "toilet-brush", en: "After cleaning the bowl, rinse the toilet brush and let it dry before putting it away.", ja: "便器を掃除したら、トイレブラシをすすいで乾かしてから片づけます。", zh: "刷完馬桶後，沖洗馬桶刷並晾乾再收起來。" },
  { id: "cleaner", en: "Before using the cleaner on the whole wall, test it on a small hidden area.", ja: "壁全体に洗剤を使う前に、目立たない小さな場所で試してください。", zh: "清潔劑用在整面牆前，先在不明顯的小區域測試。" },
  { id: "disinfectant", en: "After wiping the handle with disinfectant, wait until it dries before touching it.", ja: "取っ手を消毒液で拭いたら、乾くまで触らないでください。", zh: "用消毒液擦過把手後，等它乾了再碰。" },
  { id: "mold-remover", en: "Because mold remover has a strong smell, open the window and wear gloves while using it.", ja: "カビ取り剤はにおいが強いので、窓を開けて手袋をして使ってください。", zh: "除霉劑味道很重，使用時請開窗並戴手套。" },
  { id: "bathroom-cleaner", en: "Let the bathroom cleaner sit on the soap stains before scrubbing them with a sponge.", ja: "石けんかすをスポンジでこする前に、浴室用洗剤をしばらくなじませます。", zh: "刷洗皂垢前，先讓浴室清潔劑停留一會兒。" },
  { id: "bucket", en: "Since the water was dirty, I emptied the bucket before rinsing the floor again.", ja: "水が汚れていたので、床をもう一度流す前にバケツの水を替えました。", zh: "水已經髒了，所以我再次沖地板前先換掉水桶裡的水。" },
  { id: "wash-basin", en: "I filled the wash basin with warm water so I could soak the stained shirt by hand.", ja: "汚れたシャツを手洗いするために、洗面器へぬるま湯を入れました。", zh: "為了手洗有污漬的襯衫，我在臉盆裡裝了溫水浸泡。" },
  { id: "gloves", en: "Wear the gloves when using strong cleaner so it does not irritate your hands.", ja: "強い洗剤で手が荒れないように、掃除するときは手袋をしてください。", zh: "使用強效清潔劑時請戴手套，以免刺激雙手。" },
  { id: "hand-soap", en: "If the hand soap pump is clogged, rinse the nozzle with warm water.", ja: "ハンドソープのポンプが詰まったら、ノズルをぬるま湯で洗ってください。", zh: "洗手乳壓頭堵住時，用溫水沖洗噴嘴。" },
  { id: "lotion", en: "I apply body lotion after bathing while my skin is still slightly damp.", ja: "入浴後、肌が少し湿っているうちにボディローションを塗ります。", zh: "洗澡後趁皮膚還微濕時，我會擦乳液。" },
  { id: "moisturizer", en: "When the air is dry, I use moisturizer before bed to keep my skin from feeling tight.", ja: "空気が乾燥している日は、肌がつっぱらないように寝る前に保湿クリームを塗ります。", zh: "空氣乾燥時，我睡前會擦保濕乳，避免皮膚緊繃。" },
  { id: "cosmetics", en: "Because heat can damage cosmetics, I store them away from the sunny window.", ja: "熱で化粧品が傷むことがあるので、日の当たる窓辺には置きません。", zh: "高溫可能使化妝品變質，所以我不把它們放在有陽光的窗邊。" },
  { id: "cleansing-oil", en: "Massage the cleansing oil onto dry skin before adding water to rinse off the makeup.", ja: "メイクを落とすときは、乾いた肌にクレンジングオイルをなじませてから水を加えます。", zh: "卸妝時先把卸妝油按摩在乾燥皮膚上，再加水沖掉。" },
  { id: "micellar-water", en: "When I only wear light makeup, I remove it with micellar water instead of cleansing oil.", ja: "薄いメイクの日は、クレンジングオイルではなくクレンジングウォーターで落とします。", zh: "只化淡妝時，我會用卸妝水而不是卸妝油。" },
  { id: "perfume", en: "Since the perfume is strong, I use only one spray before going to the office.", ja: "香りが強い香水なので、出勤前は一度だけつけます。", zh: "這款香水味道很濃，所以上班前我只噴一次。" },
  { id: "deodorant", en: "I carry deodorant in summer because I often walk to the station in the heat.", ja: "夏は暑い中を駅まで歩くことが多いので、デオドラントを持ち歩いています。", zh: "夏天我常冒著熱氣走到車站，所以會隨身帶體香劑。" },
  { id: "scale", en: "To compare my weight fairly, I use the scale at the same time each morning.", ja: "体重を正しく比べられるように、毎朝同じ時間に体重計に乗ります。", zh: "為了公平比較體重，我每天早上固定時間量體重。" },
  { id: "bathrobe", en: "I put on the bathrobe after getting out of the bath so I do not get cold.", ja: "湯冷めしないように、お風呂から出たらバスローブを着ます。", zh: "為了不著涼，我洗完澡後會穿上浴袍。" },
  { id: "slippers", en: "Because the bathroom floor is cold in winter, I leave a pair of slippers by the door.", ja: "冬は洗面所の床が冷たいので、ドアのそばにスリッパを置いています。", zh: "冬天浴室地板很冷，所以我在門邊放一雙拖鞋。" },
  { id: "ventilation-fan", en: "Leave the ventilation fan running after a shower until the moisture has cleared.", ja: "湿気がなくなるまで、シャワーのあともしばらく換気扇を回しておきます。", zh: "洗完澡後讓排風扇繼續運轉，直到濕氣散去。" },
  { id: "water-heater", en: "If the water heater shows an error, turn it off and check the instructions before restarting it.", ja: "給湯器にエラーが出たら、電源を切って説明書を確認してから再起動します。", zh: "熱水器顯示錯誤時，先關機查看說明，再重新啟動。" },
  { id: "sanitary-pad", en: "I keep a spare sanitary pad in my bag in case my period starts while I am out.", ja: "外出中に生理が始まっても困らないように、予備の生理用ナプキンをかばんに入れています。", zh: "我在包包裡放一片備用衛生棉，以防外出時月經來。" },
  { id: "tampon", en: "Because tampons must be changed regularly, I set a reminder when I use one.", ja: "タンポンは定期的に交換する必要があるので、使うときは通知を設定します。", zh: "衛生棉條需要定時更換，所以使用時我會設定提醒。" },
  { id: "squeegee", en: "After showering, use the squeegee on the walls so less water is left to form mold.", ja: "カビを防ぐために、シャワーのあとスクイージーで壁の水滴を落とします。", zh: "洗完澡後用刮水器刮掉牆上水珠，可以減少發霉。" },
  { id: "bath-salts", en: "When I want to relax, I add bath salts after the bathtub has filled with warm water.", ja: "ゆっくりしたい日は、お湯をためてからバスソルトを入れます。", zh: "想放鬆的日子，我會在浴缸放滿溫水後加入浴鹽。" },
  { id: "bath-sponge", en: "Rinse the bath sponge thoroughly and let it dry, because soap can remain inside it.", ja: "中に石けんが残りやすいので、バススポンジをよくすすいで乾かします。", zh: "洗澡海綿裡容易殘留肥皂，所以要徹底沖洗並晾乾。" },
];

export const BATHROOM_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  { id: "shampoo", en: "I wash my hair with this shampoo.", ja: "このシャンプーで髪を洗います。", zh: "我用這款洗髮精洗頭。" },
  { id: "gloves", en: "I wear gloves when I clean the bathroom.", ja: "浴室を掃除するときは手袋をします。", zh: "我打掃浴室時會戴手套。" },
  { id: "cosmetics", en: "She keeps her cosmetics in this drawer.", ja: "彼女はこの引き出しに化粧品を入れています。", zh: "她把化妝品放在這個抽屜裡。" },
  { id: "slippers", en: "Please wear these slippers in the bathroom.", ja: "洗面所ではこのスリッパを履いてください。", zh: "在浴室請穿這雙拖鞋。" },
  { id: "bath-salts", en: "I added bath salts to the warm water.", ja: "お湯にバスソルトを入れました。", zh: "我在溫水裡加入浴鹽。" },
];
