import type {
  MainWordComplexExample,
  MainWordSimpleExampleOverride,
} from "./types";

export const BEDROOM_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "bed", en: "Because I have to get up early tomorrow, I am going to bed earlier than usual tonight.", ja: "明日は早起きしなければならないので、今夜はいつもより早く寝ます。", zh: "因為明天得早起，我今晚會比平常早上床睡覺。" },
  { id: "pillow", en: "If this pillow is too high, try the thinner one in the closet instead.", ja: "この枕が高すぎるなら、クローゼットにある薄いものを試してください。", zh: "如果這個枕頭太高，可以改試衣櫃裡較薄的那個。" },
  { id: "blanket", en: "When the room gets cold at night, I keep an extra blanket at the end of the bed.", ja: "夜に部屋が寒くなるので、ベッドの足元に予備の毛布を置いています。", zh: "晚上房間會變冷，所以我在床尾放一條備用毯子。" },
  { id: "closet", en: "Before the rainy season, I air out the closet so my clothes do not become musty.", ja: "服がかび臭くならないように、梅雨の前にクローゼットを換気します。", zh: "梅雨季前我會讓衣櫃通風，避免衣服有霉味。" },
  { id: "lamp", en: "I switched on the lamp because the ceiling light was too bright for reading in bed.", ja: "天井の照明は明るすぎたので、ベッドで本を読むためにランプをつけました。", zh: "頂燈太亮，所以我打開燈在床上看書。" },
  { id: "alarm-clock", en: "I put the alarm clock across the room so I have to get out of bed to turn it off.", ja: "止めるにはベッドから出なければならないように、目覚まし時計を部屋の反対側に置いています。", zh: "我把鬧鐘放在房間另一頭，這樣必須下床才能關掉。" },
  { id: "curtain", en: "I close the curtain before changing clothes because the building across the street is nearby.", ja: "向かいの建物が近いので、着替える前にカーテンを閉めます。", zh: "對面大樓很近，所以我換衣服前會拉上窗簾。" },
  { id: "wardrobe", en: "When the seasons change, I move the clothes I rarely wear to the top of the wardrobe.", ja: "季節が変わると、あまり着ない服をワードローブの上段へ移します。", zh: "換季時，我會把不常穿的衣服移到衣櫥上層。" },
  { id: "mattress", en: "Since the mattress was making my back hurt, I turned it over before buying a new one.", ja: "マットレスで腰が痛くなったので、買い替える前に裏返してみました。", zh: "床墊讓我腰痛，所以買新的以前先試著翻面。" },
  { id: "pillowcase", en: "I change the pillowcase twice a week because it easily collects sweat and skin oil.", ja: "汗や皮脂が付きやすいので、枕カバーは週に二回交換します。", zh: "枕套容易沾汗和油脂，所以我每週換兩次。" },
  { id: "quilt", en: "When the duvet is not in use, I store it with a desiccant packet so it does not get damp.", ja: "掛け布団を使わない間は、湿気を防ぐために除湿剤と一緒にしまいます。", zh: "棉被不用時，我會和乾燥劑一起收納，避免受潮。" },
  { id: "bed-sheet", en: "After washing the bed sheet, I stretch it out before drying it so there are fewer wrinkles.", ja: "しわを減らすために、シーツを洗ったら伸ばしてから干します。", zh: "床單洗好後先拉平再晾，皺褶會比較少。" },
  { id: "bedspread", en: "I fold back the bedspread before sleeping so it does not end up on the floor.", ja: "床に落ちないように、寝る前にベッドカバーを折っておきます。", zh: "睡前我會把床罩折好，免得掉到地上。" },
  { id: "headboard", en: "Because the headboard was rubbing against the wall, I attached a felt pad to the back.", ja: "ヘッドボードが壁にこすれていたので、後ろにフェルトパッドを貼りました。", zh: "床頭板一直摩擦牆面，所以我在後面貼了毛氈墊。" },
  { id: "nightstand", en: "I keep a glass of water on the nightstand in case I wake up thirsty.", ja: "夜中に喉が渇いたときのために、ベッドサイドテーブルに水を置いています。", zh: "我在床頭櫃放一杯水，以防半夜口渴醒來。" },
  { id: "hanger", en: "If you hang the wet shirt on a wide hanger, the shoulders will keep their shape.", ja: "ぬれたシャツを幅の広いハンガーに掛けると、肩の形が崩れにくくなります。", zh: "濕襯衫掛在寬衣架上，肩膀比較不會變形。" },
  { id: "drawer", en: "I put labels on each drawer so I can find socks quickly in the morning.", ja: "朝すぐに靴下を見つけられるように、引き出しごとにラベルを付けました。", zh: "我在每個抽屜貼標籤，早上就能很快找到襪子。" },
  { id: "vanity-table", en: "Since the room is small, I chose a vanity table whose stool fits underneath it.", ja: "部屋が狭いので、椅子を下に収納できるドレッサーを選びました。", zh: "房間很小，所以我選了椅凳能收進下方的梳妝台。" },
  { id: "chair", en: "Instead of leaving clothes on the chair, hang them up before going to bed.", ja: "服を椅子に置いたままにせず、寝る前にハンガーへ掛けてください。", zh: "不要把衣服留在椅子上，睡前請掛起來。" },
  { id: "desk-lamp", en: "When I work late, I angle the desk lamp away from the bed so it does not wake my partner.", ja: "夜遅く作業するときは、相手を起こさないようにデスクランプをベッドとは反対の方向に向けます。", zh: "熬夜工作時，我會把檯燈轉離床鋪，免得吵醒伴侶。" },
  { id: "bedside-lamp", en: "I use the bedside lamp at night because I can turn it off without getting out of bed.", ja: "ベッドから出ずに消せるので、夜はベッドサイドランプを使います。", zh: "晚上我用床頭燈，因為不用下床就能關掉。" },
  { id: "blinds", en: "I tilt the blinds upward so daylight enters without people outside seeing into the room.", ja: "外から部屋の中が見えないように、光だけ入る角度にブラインドを調整します。", zh: "我把百葉窗葉片向上調，讓日光進來又不會被外面看見室內。" },
  { id: "pajamas", en: "After taking a shower, I change into pajamas so I can relax before bed.", ja: "寝る前にゆっくりできるように、シャワーのあとパジャマに着替えます。", zh: "洗完澡後我會換上睡衣，讓自己睡前放鬆。" },
  { id: "robe", en: "Because the hallway is cold in the morning, I put on my dressing gown before leaving the bedroom.", ja: "朝は廊下が寒いので、寝室を出る前にガウンを羽織ります。", zh: "早上走廊很冷，所以離開臥室前我會穿上睡袍。" },
  { id: "storage-box", en: "I use a clear storage box for winter clothes so I can see what is inside.", ja: "中身が分かるように、冬服は透明な収納ボックスに入れています。", zh: "我用透明收納盒裝冬衣，這樣能看見裡面放了什麼。" },
  { id: "bookshelf", en: "When the bookshelf started leaning, I attached it to the wall so it would not fall.", ja: "本棚が傾き始めたので、倒れないように壁へ固定しました。", zh: "書架開始傾斜，所以我把它固定在牆上，避免倒下。" },
  { id: "air-conditioner", en: "I set the air conditioner timer so it turns off after I fall asleep.", ja: "寝入ったあとに止まるように、エアコンのタイマーを設定します。", zh: "我設定空調定時，讓它在我睡著後自動關閉。" },
  { id: "fan", en: "Rather than pointing the fan directly at the bed, I use it to circulate air around the room.", ja: "扇風機をベッドへ直接向けず、部屋の空気を循環させるように使います。", zh: "我不把電風扇直吹床鋪，而是用它讓房間空氣循環。" },
  { id: "heater", en: "Before turning on the heater, move the blanket away so it cannot catch fire.", ja: "火事にならないように、ヒーターをつける前に毛布を離してください。", zh: "打開電暖器前先把毯子移遠，以免起火。" },
  { id: "humidifier", en: "Because the humidifier can grow mold, I empty and dry the tank every morning.", ja: "加湿器にはカビが生えやすいので、毎朝タンクを空にして乾かします。", zh: "加濕器容易發霉，所以我每天早上倒空水箱並晾乾。" },
  { id: "air-purifier", en: "When pollen levels are high, I keep the window closed and run the air purifier.", ja: "花粉が多い日は、窓を閉めて空気清浄機を運転します。", zh: "花粉濃度高的日子，我會關窗並開啟空氣清淨機。" },
  { id: "door", en: "If the door squeaks at night, close it slowly until we can fix the hinge.", ja: "夜にドアがきしむなら、蝶番を直すまではゆっくり閉めてください。", zh: "如果門晚上會發出吱嘎聲，在修好鉸鏈前請慢慢關。" },
  { id: "window", en: "Before going out, I check that the window is closed in case it rains.", ja: "雨が降っても大丈夫なように、出かける前に窓が閉まっているか確認します。", zh: "出門前我會確認窗戶已關好，以防下雨。" },
  { id: "clothes", en: "When the clothes are completely dry, fold them before putting them back in the closet.", ja: "服が完全に乾いたら、畳んでからクローゼットへ戻します。", zh: "衣服完全乾後，摺好再放回衣櫃。" },
  { id: "photo-frame", en: "I moved the photo frame away from the edge because it could fall during an earthquake.", ja: "地震で落ちるおそれがあるので、写真立てを棚の端から離しました。", zh: "相框在地震時可能掉落，所以我把它移離架子邊緣。" },
];

export const BEDROOM_PREVIOUS_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "lamp", en: "I switched on the lamp because the ceiling light was too bright for reading in bed.", ja: "天井の照明では明るすぎたので、ベッドで本を読むためにランプをつけました。", zh: "頂燈太亮，所以我打開檯燈在床上看書。" },
  { id: "alarm-clock", en: "I put the alarm clock across the room so I have to get out of bed to turn it off.", ja: "起きて止めなければならないように、目覚まし時計を部屋の反対側に置いています。", zh: "我把鬧鐘放在房間另一頭，這樣必須下床才能關掉。" },
  { id: "quilt", en: "When the quilt is not in use, I store it with a drying packet to keep it from getting damp.", ja: "掛け布団を使わない間は、湿気を防ぐために除湿剤と一緒にしまいます。", zh: "棉被不用時，我會和乾燥劑一起收納，避免受潮。" },
  { id: "headboard", en: "Because the headboard was rubbing against the wall, I placed a felt pad behind it.", ja: "ヘッドボードが壁に当たっていたので、後ろにフェルトを貼りました。", zh: "床頭板一直摩擦牆面，所以我在後面貼了毛氈墊。" },
  { id: "desk-lamp", en: "When I work late, I angle the desk lamp away from the bed so it does not wake my partner.", ja: "夜遅く作業するときは、相手を起こさないようにデスクランプをベッドと反対へ向けます。", zh: "熬夜工作時，我會把檯燈轉離床鋪，免得吵醒伴侶。" },
  { id: "robe", en: "Because the hallway is cold in the morning, I put on a robe before leaving the bedroom.", ja: "朝は廊下が寒いので、寝室を出る前にローブを羽織ります。", zh: "早上走廊很冷，所以離開臥室前我會披上睡袍。" },
  { id: "heater", en: "Before turning on the heater, move the blanket away so it cannot catch fire.", ja: "火事にならないように、ヒーターをつける前に毛布を離してください。", zh: "打開暖氣前先把毯子移遠，以免起火。" },
  { id: "window", en: "Before going out, I check that the window is locked in case it rains.", ja: "雨が降っても大丈夫なように、出かける前に窓の鍵を確認します。", zh: "出門前我會確認窗戶已鎖好，以防下雨。" },
];

export const BEDROOM_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  { id: "lamp", en: "I turned on the lamp beside the bed.", ja: "ベッドのそばのランプをつけました。", zh: "我打開了床邊的燈。" },
  { id: "air-conditioner", en: "I turned on the air conditioner before going to bed.", ja: "寝る前にエアコンをつけました。", zh: "睡前我打開了空調。" },
  { id: "air-purifier", en: "I run the air purifier during pollen season.", ja: "花粉の季節は空気清浄機を使います。", zh: "花粉季時我會開空氣清淨機。" },
  { id: "bed-sheet", en: "I changed the bed sheet this morning.", ja: "今朝、シーツを交換しました。", zh: "我今天早上換了床單。" },
  { id: "bedside-lamp", en: "I turned off the bedside lamp before going to sleep.", ja: "寝る前にベッドサイドランプを消しました。", zh: "睡前我關掉了床頭燈。" },
  { id: "bedspread", en: "I folded the bedspread before going to sleep.", ja: "寝る前にベッドカバーを畳みました。", zh: "睡前我把床罩摺好了。" },
  { id: "bookshelf", en: "I put the new book on the bookshelf.", ja: "新しい本を本棚に置きました。", zh: "我把新書放到書架上。" },
  { id: "chair", en: "I hung my jacket on the chair.", ja: "ジャケットを椅子に掛けました。", zh: "我把外套掛在椅子上。" },
  { id: "desk-lamp", en: "I turned on the desk lamp to do my homework.", ja: "宿題をするためにデスクランプをつけました。", zh: "我打開檯燈寫作業。" },
  { id: "door", en: "Please close the bedroom door quietly.", ja: "寝室のドアを静かに閉めてください。", zh: "請輕輕關上臥室的門。" },
  { id: "drawer", en: "I keep my socks in the top drawer.", ja: "靴下を一番上の引き出しに入れています。", zh: "我把襪子放在最上層抽屜。" },
  { id: "fan", en: "I turned on the fan because the room was hot.", ja: "部屋が暑かったので、扇風機をつけました。", zh: "房間很熱，所以我打開電風扇。" },
  { id: "hanger", en: "I hung my shirt on a hanger.", ja: "シャツをハンガーに掛けました。", zh: "我把襯衫掛在衣架上。" },
  { id: "headboard", en: "I leaned against the headboard to read.", ja: "ヘッドボードにもたれて本を読みました。", zh: "我靠著床頭板看書。" },
  { id: "heater", en: "I turned on the heater before changing clothes.", ja: "着替える前にヒーターをつけました。", zh: "換衣服前我打開了電暖器。" },
  { id: "humidifier", en: "I filled the humidifier before bed.", ja: "寝る前に加湿器に水を入れました。", zh: "睡前我幫加濕器加水。" },
  { id: "mattress", en: "I rotated the mattress this morning.", ja: "今朝、マットレスの向きを変えました。", zh: "我今天早上把床墊轉了方向。" },
  { id: "nightstand", en: "I put my phone on the nightstand.", ja: "スマートフォンをベッドサイドテーブルに置きました。", zh: "我把手機放在床頭櫃上。" },
  { id: "photo-frame", en: "I placed the photo frame on the shelf.", ja: "写真立てを棚に置きました。", zh: "我把相框放在架子上。" },
  { id: "pillowcase", en: "I changed the pillowcase after washing my hair.", ja: "髪を洗ったあと、枕カバーを交換しました。", zh: "洗完頭後我換了枕套。" },
  { id: "quilt", en: "I pulled the duvet up because I was cold.", ja: "寒かったので、掛け布団を肩までかけました。", zh: "我覺得冷，便把棉被拉到肩膀。" },
  { id: "robe", en: "I put on my dressing gown after getting out of bed.", ja: "起きてガウンを羽織りました。", zh: "我起床後穿上睡袍。" },
  { id: "storage-box", en: "I stored my winter scarves in a storage box.", ja: "冬のマフラーを収納ボックスにしまいました。", zh: "我把冬季圍巾收進收納盒。" },
  { id: "vanity-table", en: "I do my makeup at the vanity table.", ja: "ドレッサーで化粧をします。", zh: "我在梳妝台化妝。" },
  { id: "window", en: "I opened the window to air out the bedroom.", ja: "寝室を換気するために窓を開けました。", zh: "我打開窗戶讓臥室通風。" },
  { id: "blinds", en: "Please close the blinds.", ja: "ブラインドを閉めてください。", zh: "請關上百葉窗。" },
  { id: "pajamas", en: "I changed into my pajamas.", ja: "パジャマに着替えました。", zh: "我換上睡衣。" },
  { id: "clothes", en: "I folded the clean clothes.", ja: "きれいな服を畳みました。", zh: "我把乾淨衣服摺好。" },
];
