import type {
  MainWordComplexExample,
  MainWordSimpleExampleOverride,
} from "./types";

// Exact complex examples deployed before the 2026-08-26 kitchen semantic
// review. The apply transaction accepts only these known values when moving
// the corrected pairs forward; any other live edit remains a conflict.
export const KITCHEN_PREVIOUS_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  {
    id: "faucet",
    en: "If the faucet keeps dripping after you close it, ask the landlord to repair it.",
    ja: "蛇口を閉めても水が止まらない場合は、大家さんに修理を頼んでください。",
    zh: "如果關上水龍頭後仍一直滴水，請請房東修理。",
  },
  {
    id: "knife",
    en: "Because this knife is very sharp, hold the handle firmly while you cut the pumpkin.",
    ja: "このナイフはよく切れるので、かぼちゃを切るときは柄をしっかり握ってください。",
    zh: "這把刀很鋒利，切南瓜時請握緊刀柄。",
  },
  {
    id: "bowl",
    en: "If there is any salad left, cover the bowl and keep it in the fridge.",
    ja: "サラダが残ったら、ボウルにふたをして冷蔵庫に入れてください。",
    zh: "如果沙拉還有剩，請把碗蓋好放進冰箱。",
  },
  {
    id: "grater",
    en: "When the curry is finished, I use the grater to add a little fresh ginger.",
    ja: "カレーができたら、おろし器ですったしょうがを少し加えます。",
    zh: "咖哩煮好後，我會用刨絲器磨一點新鮮薑加進去。",
  },
  {
    id: "kettle",
    en: "When the kettle starts whistling, turn off the heat before the water boils away.",
    ja: "やかんが鳴り始めたら、お湯がなくなる前に火を止めてください。",
    zh: "水壺開始鳴叫時，請在水燒乾前把火關掉。",
  },
  {
    id: "fork",
    en: "If the pasta is hard to pick up, turn the fork against the edge of the plate.",
    ja: "パスタが取りにくければ、フォークをお皿の端に当てて巻いてください。",
    zh: "如果義大利麵不好叉起來，可以把叉子靠著盤邊捲起來。",
  },
  {
    id: "teapot",
    en: "After pouring hot water into the teapot, wait a few minutes before serving the tea.",
    ja: "ティーポットにお湯を注いだら、数分待ってからお茶を入れます。",
    zh: "把熱水倒進茶壺後，等幾分鐘再倒茶。",
  },
  {
    id: "food-container",
    en: "Let the curry cool before closing the food container, or steam will collect inside.",
    ja: "中に水滴がたまるので、カレーを冷ましてから保存容器の蓋を閉めます。",
    zh: "咖哩放涼後再蓋上保鮮盒，否則水蒸氣會積在裡面。",
  },
];

export const KITCHEN_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  {
    id: "fridge",
    en: "After opening the milk, put it back in the fridge right away so it does not spoil.",
    ja: "牛乳を開けたら、傷まないようにすぐ冷蔵庫へ戻してください。",
    zh: "牛奶開封後，請立刻放回冰箱，以免變質。",
  },
  {
    id: "microwave",
    en: "When I am short on time, I heat yesterday's soup in the microwave for lunch.",
    ja: "時間がない日は、昨日のスープを電子レンジで温めて昼ご飯にします。",
    zh: "沒時間的日子，我會用微波爐加熱昨天的湯當午餐。",
  },
  {
    id: "oven",
    en: "While the oven is preheating, I prepare the vegetables that I am going to roast.",
    ja: "オーブンを予熱している間に、焼く野菜の準備をします。",
    zh: "烤箱預熱時，我會準備等一下要烤的蔬菜。",
  },
  {
    id: "stove",
    en: "Before leaving the kitchen, make sure the stove is turned off and has cooled down.",
    ja: "キッチンを離れる前に、コンロの火が消えて冷めているか確認してください。",
    zh: "離開廚房前，請確認爐火已關閉並且爐子已冷卻。",
  },
  {
    id: "sink",
    en: "Because the sink was full of dishes, I washed them before I started cooking.",
    ja: "シンクに食器がたまっていたので、料理を始める前に洗いました。",
    zh: "因為水槽堆滿了碗盤，我在開始做飯前先洗乾淨。",
  },
  {
    id: "faucet",
    en: "If the faucet keeps dripping after you close it, ask the landlord to repair it.",
    ja: "蛇口を閉めても水が止まらない場合は、大家さんに修理を頼んでください。",
    zh: "如果關上水龍頭後仍一直滴水，請房東修理。",
  },
  {
    id: "pan",
    en: "When the pan is hot enough, add the vegetables and stir them quickly.",
    ja: "フライパンが十分に熱くなったら、野菜を入れて手早く炒めます。",
    zh: "平底鍋夠熱後，放入蔬菜快速翻炒。",
  },
  {
    id: "pot",
    en: "Once the water in the pot starts boiling, turn down the heat and add the noodles.",
    ja: "鍋のお湯が沸いたら、火を弱めて麺を入れます。",
    zh: "鍋裡的水滾後，把火轉小再放入麵條。",
  },
  {
    id: "cutting-board",
    en: "After cutting raw meat, wash the cutting board well before using it for vegetables.",
    ja: "生肉を切ったあとは、野菜に使う前にまな板をよく洗ってください。",
    zh: "切過生肉後，請先把砧板洗乾淨，再拿來切蔬菜。",
  },
  {
    id: "knife",
    en: "When you finish using the knife, wash it and dry it before putting it away.",
    ja: "ナイフを使い終わったら、洗って乾かしてから片づけてください。",
    zh: "刀子用完後，清洗並擦乾再收好。",
  },
  {
    id: "bowl",
    en: "Use a large bowl so the batter does not spill while you mix it.",
    ja: "生地を混ぜるときにこぼれないように、大きなボウルを使ってください。",
    zh: "攪拌麵糊時請使用大攪拌盆，以免灑出來。",
  },
  {
    id: "plate",
    en: "Since this plate has a small crack, I will use a different one for dinner.",
    ja: "このお皿には小さなひびがあるので、夕食には別のお皿を使います。",
    zh: "這個盤子有一道小裂痕，所以晚餐我要換一個使用。",
  },
  {
    id: "chopsticks",
    en: "If using chopsticks is difficult, you can ask the restaurant for a fork.",
    ja: "箸を使うのが難しければ、お店の人にフォークを頼めます。",
    zh: "如果筷子用不習慣，可以請餐廳提供叉子。",
  },
  {
    id: "spoon",
    en: "Because the soup is still hot, use a spoon and taste a little at a time.",
    ja: "スープはまだ熱いので、スプーンで少しずつ味見してください。",
    zh: "湯還很燙，請用湯匙一點一點試味道。",
  },
  {
    id: "mug",
    en: "Before pouring in hot water, I warm the mug so the coffee stays hot longer.",
    ja: "コーヒーが冷めにくいように、お湯を注ぐ前にマグカップを温めます。",
    zh: "為了讓咖啡保溫久一點，我會先溫熱馬克杯再倒熱水。",
  },
  {
    id: "electric-cooker",
    en: "I put the ingredients in the slow cooker before work so dinner is ready when I get home.",
    ja: "帰宅したときに夕食ができているように、出勤前にスロークッカーへ材料を入れます。",
    zh: "我上班前把食材放進慢燉鍋，這樣回家時晚餐就煮好了。",
  },
  {
    id: "rice-cooker",
    en: "If I set the timer on the rice cooker at night, fresh rice is ready in the morning.",
    ja: "夜に炊飯器のタイマーをセットしておくと、朝にはご飯が炊けています。",
    zh: "如果晚上先設定電飯鍋的預約功能，早上就有剛煮好的飯。",
  },
  {
    id: "freezer",
    en: "When I cook too much rice, I divide it into portions and store them in the freezer.",
    ja: "ご飯を炊きすぎたときは、一食分ずつ分けて冷凍庫に保存します。",
    zh: "飯煮太多時，我會分成一餐份量放進冷凍庫保存。",
  },
  {
    id: "range-hood",
    en: "Turn on the range hood before frying fish so the smell does not fill the room.",
    ja: "部屋ににおいがこもらないように、魚を焼く前にレンジフードをつけます。",
    zh: "煎魚前先打開抽油煙機，免得味道充滿整個房間。",
  },
  {
    id: "dishwasher",
    en: "Before starting the dishwasher, scrape the leftover food off the plates.",
    ja: "食洗機を動かす前に、お皿に残った食べ物を取り除いてください。",
    zh: "啟動洗碗機前，請先把盤子上的剩菜刮掉。",
  },
  {
    id: "kitchen-knife",
    en: "When the kitchen knife becomes dull, I have it sharpened instead of forcing it through food.",
    ja: "包丁の切れ味が悪くなったら、無理に切らずに研いでもらいます。",
    zh: "菜刀變鈍時，我會拿去磨利，而不是硬切食材。",
  },
  {
    id: "peeler",
    en: "I use a peeler for the carrots because it removes a thinner layer than a knife.",
    ja: "包丁より薄く皮をむけるので、にんじんにはピーラーを使います。",
    zh: "削皮器削得比刀子薄，所以我用它來削紅蘿蔔。",
  },
  {
    id: "grater",
    en: "When the curry is finished, grate a little fresh ginger into it.",
    ja: "カレーができたら、おろし器でしょうがを少しすりおろして加えます。",
    zh: "咖哩煮好後，用磨泥器磨一點新鮮薑加進去。",
  },
  {
    id: "can-opener",
    en: "Since this can has no pull tab, we need a can opener to open it.",
    ja: "この缶にはプルタブがないので、開けるには缶切りが必要です。",
    zh: "這個罐頭沒有拉環，所以需要用開罐器打開。",
  },
  {
    id: "scissors",
    en: "I keep these scissors in the kitchen because they are only for opening food packages.",
    ja: "食品の袋を開ける専用なので、このはさみはキッチンに置いています。",
    zh: "這把剪刀只用來剪開食品包裝，所以我把它放在廚房。",
  },
  {
    id: "spatula",
    en: "When the pancake bubbles around the edges, slide the spatula underneath and turn it over.",
    ja: "パンケーキの縁に泡が出たら、フライ返しを下に入れて裏返します。",
    zh: "鬆餅邊緣冒泡時，把鍋鏟滑到底下再翻面。",
  },
  {
    id: "ladle",
    en: "After the soup is ready, use the ladle to serve it without spilling any.",
    ja: "スープができたら、こぼさないようにお玉で器によそいます。",
    zh: "湯煮好後，用湯勺盛進碗裡，注意不要灑出來。",
  },
  {
    id: "tongs",
    en: "Because the bread is hot, take it out of the toaster with the tongs.",
    ja: "パンが熱いので、トングを使ってトースターから取り出してください。",
    zh: "麵包很燙，請用夾子把它從烤麵包機裡取出。",
  },
  {
    id: "whisk",
    en: "Whisk the eggs until the yolks and whites are completely mixed.",
    ja: "黄身と白身が完全に混ざるまで、泡立て器で卵を混ぜてください。",
    zh: "用打蛋器攪拌雞蛋，直到蛋黃和蛋白完全混合。",
  },
  {
    id: "measuring-cup",
    en: "Because the recipe is for two people, measure only half the water with the measuring cup.",
    ja: "二人分のレシピなので、計量カップで水を半分だけ量ります。",
    zh: "這份食譜是兩人份，所以用量杯量一半的水就好。",
  },
  {
    id: "measuring-spoon",
    en: "If you add too much salt, the flavor changes, so use a measuring spoon.",
    ja: "塩を入れすぎると味が変わるので、計量スプーンを使ってください。",
    zh: "鹽放太多會改變味道，所以請使用量匙。",
  },
  {
    id: "strainer",
    en: "After the noodles are cooked, pour them into the strainer and drain them well.",
    ja: "麺がゆで上がったら、ザルにあけてしっかり水を切ります。",
    zh: "麵煮好後倒進濾網，把水分充分瀝乾。",
  },
  {
    id: "slotted-spoon",
    en: "Use the slotted spoon to lift the dumplings out while leaving the hot water in the pot.",
    ja: "鍋にお湯を残したまま、穴あきお玉で団子をすくい上げます。",
    zh: "用漏勺把丸子撈起來，讓熱水留在鍋裡。",
  },
  {
    id: "glass",
    en: "Since this glass is chipped, do not use it even if it does not leak.",
    ja: "このコップは欠けているので、水が漏れなくても使わないでください。",
    zh: "這個玻璃杯有缺口，即使不漏水也不要使用。",
  },
  {
    id: "fork",
    en: "If the pasta is hard to pick up, press the fork against the edge of the plate and twirl it.",
    ja: "パスタが取りにくければ、フォークをお皿の端に当てて巻いてください。",
    zh: "如果義大利麵不好叉起來，可以把叉子靠著盤邊捲起來。",
  },
  {
    id: "table-knife",
    en: "Because the butter is cold, let it soften before spreading it with the table knife.",
    ja: "バターが冷たいので、少し柔らかくしてからテーブルナイフで塗ります。",
    zh: "奶油很冰，先讓它稍微變軟，再用餐刀抹開。",
  },
  {
    id: "wok",
    en: "When the wok begins to smoke lightly, add the meat and stir-fry it over high heat.",
    ja: "中華鍋から少し煙が出たら、肉を入れて強火で炒めます。",
    zh: "炒鍋開始微微冒煙後，放入肉用大火翻炒。",
  },
  {
    id: "lid",
    en: "Put the lid on the pot after it boils, but leave a small gap so it does not boil over.",
    ja: "沸騰したら鍋に蓋をしますが、吹きこぼれないように少し隙間を空けます。",
    zh: "鍋子煮滾後蓋上鍋蓋，但要留一點縫，以免溢出。",
  },
  {
    id: "steamer-basket",
    en: "Line the steamer basket before adding the buns so they do not stick to the bottom.",
    ja: "肉まんが底に付かないように、入れる前に蒸し器へシートを敷きます。",
    zh: "放入包子前先在蒸籠墊紙，這樣就不會黏在底部。",
  },
  {
    id: "teapot",
    en: "After pouring hot water into the teapot, wait a few minutes before pouring the tea into cups.",
    ja: "ティーポットにお湯を注いだら、数分待ってからカップにお茶を注ぎます。",
    zh: "把熱水倒進茶壺後，等幾分鐘再把茶倒進杯子。",
  },
  {
    id: "kettle",
    en: "When the kettle starts whistling, turn off the heat before the water boils away.",
    ja: "やかんが鳴り始めたら、お湯がなくなる前に火を止めてください。",
    zh: "燒水壺開始鳴響時，請在水燒乾前關火。",
  },
  {
    id: "coffee-maker",
    en: "I prepare the coffee maker at night so I only have to press a button in the morning.",
    ja: "朝はボタンを押すだけでいいように、夜のうちにコーヒーメーカーを準備します。",
    zh: "我晚上先把咖啡機準備好，早上只要按按鈕就行。",
  },
  {
    id: "toaster",
    en: "If the bread is frozen, use a lower setting so the toaster warms the inside without burning it.",
    ja: "冷凍パンは焦げないように、トースターを弱めに設定して中まで温めます。",
    zh: "如果麵包是冷凍的，把烤麵包機調低一點，才不會外面焦了裡面還沒熱。",
  },
  {
    id: "blender",
    en: "Hold the lid down while the blender is running so the smoothie does not splash out.",
    ja: "スムージーが飛び出さないように、ブレンダーを動かしている間は蓋を押さえます。",
    zh: "果汁機運轉時要壓住蓋子，免得冰沙濺出來。",
  },
  {
    id: "food-processor",
    en: "Because chopping all the onions by hand takes time, I use the food processor for a large batch.",
    ja: "玉ねぎを全部手で刻むと時間がかかるので、量が多いときはフードプロセッサーを使います。",
    zh: "手切大量洋蔥很花時間，所以份量多時我會用食物調理機。",
  },
  {
    id: "air-fryer",
    en: "When I want crispy potatoes with less oil, I cook them in the air fryer.",
    ja: "油を控えてじゃがいもをカリッと仕上げたいときは、エアフライヤーで調理します。",
    zh: "想用少一點油做出酥脆馬鈴薯時，我會使用氣炸鍋。",
  },
  {
    id: "dish-soap",
    en: "If the pan is greasy, add a little dish soap and let it soak before washing it.",
    ja: "フライパンの油汚れがひどいときは、食器用洗剤を少し入れてつけ置きしてから洗います。",
    zh: "平底鍋很油時，加一點洗碗精浸泡後再清洗。",
  },
  {
    id: "sponge",
    en: "Replace the sponge when it starts to smell, even if it still looks clean.",
    ja: "見た目がきれいでも、においがし始めたらスポンジを交換します。",
    zh: "海綿開始有味道時，即使看起來還乾淨也要更換。",
  },
  {
    id: "cloth",
    en: "After wiping the counter, rinse the cloth well and hang it where it can dry.",
    ja: "台を拭いたあとは、ふきんをよくすすいで乾く場所に掛けます。",
    zh: "擦完流理臺後，把抹布洗乾淨並掛在能晾乾的地方。",
  },
  {
    id: "paper-towel",
    en: "When raw egg spills on the counter, I wipe it up with a paper towel before cleaning the surface.",
    ja: "生卵を台にこぼしたら、まずキッチンペーパーで拭き取ってから台を掃除します。",
    zh: "生蛋灑在流理臺上時，我會先用廚房紙巾擦掉，再清潔表面。",
  },
  {
    id: "trash-bag",
    en: "Tie the trash bag tightly before taking it outside so nothing leaks on the floor.",
    ja: "床に漏れないように、外へ出す前にゴミ袋の口をしっかり結んでください。",
    zh: "把垃圾拿出去前，請綁緊垃圾袋，以免有東西漏在地上。",
  },
  {
    id: "plastic-wrap",
    en: "Cover the cut fruit with plastic wrap before refrigerating it so the surface does not dry out.",
    ja: "切った果物の表面が乾かないように、冷蔵庫へ入れる前にラップをかけます。",
    zh: "切好的水果放進冰箱前要包上保鮮膜，才不會表面乾掉。",
  },
  {
    id: "aluminum-foil",
    en: "If the fish browns too quickly, cover it loosely with aluminum foil and continue baking.",
    ja: "魚に早く焼き色が付きすぎたら、アルミホイルを軽くかぶせて焼き続けます。",
    zh: "魚太快上色時，鬆鬆地蓋上鋁箔紙再繼續烤。",
  },
  {
    id: "food-container",
    en: "Cool the curry before closing the food container, or steam will collect inside.",
    ja: "中に水滴がたまるので、カレーを冷ましてから保存容器の蓋を閉めます。",
    zh: "咖哩放涼後再蓋上保鮮盒，否則水蒸氣會積在裡面。",
  },
  {
    id: "seasoning-jar",
    en: "I label each seasoning jar so I do not confuse salt with sugar while cooking.",
    ja: "料理中に塩と砂糖を間違えないように、調味料入れにラベルを付けています。",
    zh: "我會在每個調味罐貼上標籤，做飯時才不會把鹽和糖弄混。",
  },
];

export const KITCHEN_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  { id: "air-fryer", en: "I cooked frozen fries in the air fryer.", ja: "冷凍ポテトをエアフライヤーで調理しました。", zh: "我用氣炸鍋料理冷凍薯條。" },
  { id: "aluminum-foil", en: "Cover the fish with aluminum foil.", ja: "魚にアルミホイルをかぶせてください。", zh: "用鋁箔紙蓋住魚。" },
  { id: "blender", en: "I made a banana smoothie in the blender.", ja: "ブレンダーでバナナスムージーを作りました。", zh: "我用果汁機打了一杯香蕉冰沙。" },
  { id: "bowl", en: "Mix the eggs in the bowl.", ja: "ボウルで卵を混ぜてください。", zh: "請在攪拌盆裡把蛋拌勻。" },
  { id: "can-opener", en: "Open this can with the can opener.", ja: "缶切りでこの缶を開けてください。", zh: "請用開罐器打開這個罐頭。" },
  { id: "cloth", en: "Wipe the counter with this cloth.", ja: "このふきんで調理台を拭いてください。", zh: "用這條抹布擦流理臺。" },
  { id: "coffee-maker", en: "Put the filter in the coffee maker.", ja: "コーヒーメーカーにフィルターを入れてください。", zh: "把濾紙放進咖啡機。" },
  { id: "dish-soap", en: "Wash the greasy plate with dish soap.", ja: "食器用洗剤で油のついたお皿を洗ってください。", zh: "用洗碗精清洗油膩的盤子。" },
  { id: "dishwasher", en: "Put the dirty plates in the dishwasher.", ja: "汚れたお皿を食洗機に入れてください。", zh: "把髒盤子放進洗碗機。" },
  { id: "faucet", en: "Turn off the faucet after washing the dishes.", ja: "食器を洗ったら蛇口を閉めてください。", zh: "洗完碗後請關上水龍頭。" },
  { id: "food-container", en: "Put the leftovers in this food container.", ja: "残り物をこの保存容器に入れてください。", zh: "把剩菜放進這個保鮮盒。" },
  { id: "food-processor", en: "I chopped the onions in the food processor.", ja: "フードプロセッサーで玉ねぎを刻みました。", zh: "我用食物調理機切碎洋蔥。" },
  { id: "fork", en: "Eat the pasta with a fork.", ja: "フォークでパスタを食べてください。", zh: "請用叉子吃義大利麵。" },
  { id: "freezer", en: "Put the ice cream in the freezer.", ja: "アイスクリームを冷凍庫に入れてください。", zh: "把冰淇淋放進冷凍庫。" },
  { id: "fridge", en: "Keep the milk in the fridge.", ja: "牛乳は冷蔵庫に入れておいてください。", zh: "牛奶要放在冰箱裡。" },
  { id: "glass", en: "Pour some water into the glass.", ja: "コップに水を注いでください。", zh: "倒一些水進玻璃杯。" },
  { id: "grater", en: "Grate the ginger with this grater.", ja: "このおろし器でしょうがをすってください。", zh: "請用這個磨泥器磨薑。" },
  { id: "kettle", en: "Boil water in the kettle.", ja: "やかんでお湯を沸かしてください。", zh: "用燒水壺把水煮開。" },
  { id: "kitchen-knife", en: "Slice the cabbage with a kitchen knife.", ja: "包丁でキャベツを切ってください。", zh: "用菜刀切高麗菜。" },
  { id: "knife", en: "Be careful with this sharp knife.", ja: "この鋭いナイフに気をつけてください。", zh: "小心這把鋒利的刀子。" },
  { id: "ladle", en: "Serve the soup with a ladle.", ja: "お玉でスープをよそってください。", zh: "用湯勺盛湯。" },
  { id: "lid", en: "Put the lid on the pot.", ja: "鍋に蓋をしてください。", zh: "把鍋蓋蓋上。" },
  { id: "measuring-cup", en: "Measure the water with a measuring cup.", ja: "計量カップで水を量ってください。", zh: "用量杯量水。" },
  { id: "measuring-spoon", en: "Measure one teaspoon of salt.", ja: "計量スプーンで塩を小さじ一杯量ってください。", zh: "用量匙量一小匙鹽。" },
  { id: "paper-towel", en: "Wipe up the spilled milk with a paper towel.", ja: "こぼれた牛乳をキッチンペーパーで拭いてください。", zh: "用廚房紙巾擦掉灑出的牛奶。" },
  { id: "peeler", en: "Peel the potato with a peeler.", ja: "ピーラーでじゃがいもの皮をむいてください。", zh: "用削皮器削馬鈴薯皮。" },
  { id: "plastic-wrap", en: "Cover the cut fruit with plastic wrap.", ja: "切った果物にラップをかけてください。", zh: "用保鮮膜包住切好的水果。" },
  { id: "plate", en: "Put the toast on a plate.", ja: "トーストをお皿にのせてください。", zh: "把吐司放在盤子上。" },
  { id: "range-hood", en: "Turn on the range hood before frying fish.", ja: "魚を焼く前にレンジフードをつけてください。", zh: "煎魚前請打開抽油煙機。" },
  { id: "rice-cooker", en: "Wash the rice before putting it in the rice cooker.", ja: "炊飯器に入れる前に米を洗ってください。", zh: "把米放進電飯鍋前先洗米。" },
  { id: "scissors", en: "Cut open the food package with scissors.", ja: "はさみで食品の袋を切って開けてください。", zh: "用剪刀剪開食品包裝。" },
  { id: "seasoning-jar", en: "Fill the seasoning jar with salt.", ja: "調味料入れに塩を入れてください。", zh: "把鹽裝進調味罐。" },
  { id: "slotted-spoon", en: "Lift the dumplings with a slotted spoon.", ja: "穴あきお玉で団子をすくってください。", zh: "用漏勺撈起丸子。" },
  { id: "spatula", en: "Flip the pancake with a spatula.", ja: "フライ返しでパンケーキを裏返してください。", zh: "用鍋鏟把鬆餅翻面。" },
  { id: "sponge", en: "Scrub the pan with a sponge.", ja: "スポンジでフライパンをこすってください。", zh: "用海綿刷洗平底鍋。" },
  { id: "steamer-basket", en: "Put the buns in the steamer basket.", ja: "肉まんを蒸し器に入れてください。", zh: "把包子放進蒸籠。" },
  { id: "strainer", en: "Drain the noodles in a strainer.", ja: "ザルで麺の水を切ってください。", zh: "用濾網把麵瀝乾。" },
  { id: "table-knife", en: "Spread butter with a table knife.", ja: "テーブルナイフでバターを塗ってください。", zh: "用餐刀抹奶油。" },
  { id: "teapot", en: "Pour hot water into the teapot.", ja: "ティーポットにお湯を注いでください。", zh: "把熱水倒進茶壺。" },
  { id: "toaster", en: "Toast two slices of bread in the toaster.", ja: "トースターでパンを二枚焼いてください。", zh: "用烤麵包機烤兩片吐司。" },
  { id: "tongs", en: "Turn the meat with the tongs.", ja: "トングで肉を裏返してください。", zh: "用夾子把肉翻面。" },
  { id: "trash-bag", en: "Put the food scraps in the trash bag.", ja: "生ごみをゴミ袋に入れてください。", zh: "把廚餘放進垃圾袋。" },
  { id: "whisk", en: "Beat the eggs with a whisk.", ja: "泡立て器で卵を混ぜてください。", zh: "用打蛋器把蛋打勻。" },
  { id: "wok", en: "Stir-fry the vegetables in the wok.", ja: "中華鍋で野菜を炒めてください。", zh: "用炒鍋炒蔬菜。" },
];
