import type {
  MainWordComplexExample,
  MainWordSimpleExampleOverride,
} from "./types";

export const LIVING_ROOM_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  {
    id: "armchair",
    en: "This armchair is comfortable for reading.",
    ja: "このアームチェアなら快適に読書できます。",
    zh: "這張扶手椅很適合坐著看書。",
  },
  {
    id: "projector",
    en: "We use the projector to show movies on the screen.",
    ja: "プロジェクターで映画をスクリーンに映します。",
    zh: "我們用投影機把電影投在布幕上。",
  },
];

export const LIVING_ROOM_PREVIOUS_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "armchair", en: "When my back is tired, I sit in the armchair because its high back gives me support.", ja: "腰が疲れたときは、背もたれが高くて楽なのでアームチェアに座ります。", zh: "腰累時我會坐扶手椅，因為高椅背能提供支撐。" },
  { id: "cabinet", en: "I moved the medicine to the top shelf of the cabinet so the children cannot reach it.", ja: "子どもの手が届かないように、薬をキャビネットの一番上へ移しました。", zh: "我把藥移到櫃子最上層，讓孩子拿不到。" },
  { id: "cushion", en: "If the sofa feels too deep, place a cushion behind your back before sitting down.", ja: "ソファの奥行きが深すぎるなら、座る前に背中へクッションを置いてください。", zh: "如果沙發太深，坐下前可以在背後放一個抱枕。" },
  { id: "game-console", en: "After finishing the game, turn off the game console instead of leaving it in sleep mode all night.", ja: "ゲームが終わったら、一晩中スリープにせずゲーム機の電源を切ります。", zh: "遊戲結束後要關閉遊戲機，不要整晚留在休眠模式。" },
  { id: "footstool", en: "The footstool also has storage inside, so we keep the extra blankets there.", ja: "この足置きは中が収納になっているので、予備の毛布を入れています。", zh: "這張腳凳內部也能收納，所以我們把備用毯子放在裡面。" },
  { id: "potted-plant", en: "Since this potted plant needs indirect light, I moved it away from the sunny window.", ja: "この鉢植えには柔らかい光が必要なので、日の強い窓辺から離しました。", zh: "這盆栽需要間接光，所以我把它移離陽光直射的窗邊。" },
  { id: "recliner", en: "Before lowering the recliner, check that nothing is behind it or under the footrest.", ja: "リクライニングチェアを倒す前に、後ろや足元に物がないか確認してください。", zh: "放下躺椅前，先確認後方和腳靠下沒有東西。" },
  { id: "remote", en: "I put the remote beside the TV so everyone can find it after using the sofa.", ja: "誰でも見つけられるように、リモコンは使ったあとテレビの横へ戻します。", zh: "遙控器用完後我會放回電視旁，讓大家都找得到。" },
  { id: "robot-vacuum", en: "Before starting the robot vacuum, I pick up cables so it will not get stuck.", ja: "ロボット掃除機が止まらないように、動かす前に床のケーブルを片づけます。", zh: "啟動掃地機器人前，我會收起電線，避免它卡住。" },
  { id: "side-table", en: "Since the side table is narrow, use a coaster so the glass will not slide off.", ja: "サイドテーブルは狭いので、コップが滑らないようにコースターを使ってください。", zh: "邊桌很窄，請使用杯墊，避免杯子滑落。" },
  { id: "telephone", en: "If the telephone rings while I am cooking, please answer it and take a message.", ja: "私が料理中に電話が鳴ったら、出て伝言を聞いておいてください。", zh: "我做飯時電話如果響了，請幫忙接聽並記下留言。" },
];

export const LIVING_ROOM_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "sofa", en: "Since friends are visiting tonight, I moved the sofa to make more space around the table.", ja: "今夜友達が来るので、テーブルの周りを広くするためにソファを動かしました。", zh: "今晚朋友要來，所以我移動沙發，讓桌子周圍更寬敞。" },
  { id: "tv", en: "If the TV is too loud after ten, the neighbors downstairs can hear it.", ja: "夜十時を過ぎてテレビの音が大きいと、下の階の人にも聞こえてしまいます。", zh: "晚上十點後電視太大聲，樓下鄰居也會聽見。" },
  { id: "remote", en: "After using the remote, I put it beside the TV so everyone can find it.", ja: "誰でも見つけられるように、リモコンは使ったあとテレビの横へ戻します。", zh: "遙控器用完後我會放回電視旁，讓大家都找得到。" },
  { id: "coffee-table", en: "Before the children start playing, move the cups off the coffee table so they are not knocked over.", ja: "子どもが遊び始める前に、倒されないようにコーヒーテーブルのカップを片づけます。", zh: "孩子開始玩以前，把茶几上的杯子收走，以免被撞倒。" },
  { id: "rug", en: "Because the rug kept sliding, I placed a non-slip sheet underneath it.", ja: "ラグがずれて危なかったので、下に滑り止めシートを敷きました。", zh: "小地毯一直滑動，所以我在下面鋪了防滑墊。" },
  { id: "clock", en: "Although the clock is five minutes fast, I leave it that way so I am not late.", ja: "時計は五分進んでいますが、遅刻しないようにそのままにしています。", zh: "時鐘雖然快五分鐘，我為了避免遲到而故意不調整。" },
  { id: "picture-frame", en: "I chose a light picture frame because the shelf cannot support anything heavy.", ja: "棚に重い物を置けないので、軽い写真フレームを選びました。", zh: "架子承受不了重物，所以我選了輕的相框。" },
  { id: "armchair", en: "When my back is tired, I sit in the armchair because its high back gives me support.", ja: "腰が疲れたときは、高い背もたれが腰を支えてくれるので、アームチェアに座ります。", zh: "腰累時我會坐扶手椅，因為高椅背能提供支撐。" },
  { id: "tv-stand", en: "I left space behind the TV stand so the cables are easy to reach and do not bend sharply.", ja: "ケーブルに手が届き、強く曲がらないように、テレビ台の後ろに隙間を空けました。", zh: "我在電視櫃後方留出空間，方便拿取線材，也避免過度彎折。" },
  { id: "cushion", en: "If the sofa feels too deep, place a cushion behind your back before sitting down.", ja: "ソファの奥行きが深すぎるなら、座る前に背中にクッションを当ててください。", zh: "如果沙發太深，坐下前可以在背後放一個抱枕。" },
  { id: "floor-lamp", en: "I moved the floor lamp behind the chair so its light falls directly on my book.", ja: "本に直接光が当たるように、フロアランプを椅子の後ろへ動かしました。", zh: "我把落地燈移到椅子後方，讓光能直接照在書上。" },
  { id: "table-lamp", en: "Since the table lamp has a dimmer, I lower the light when we watch a movie.", ja: "テーブルランプは明るさを調節できるので、映画を見るときは暗くします。", zh: "檯燈能調光，所以看電影時我會把亮度降低。" },
  { id: "ceiling-light", en: "If the ceiling light flickers again, turn it off until the electrician checks it.", ja: "シーリングライトがまた点滅したら、電気工事の人が確認するまで消してください。", zh: "吸頂燈如果又閃爍，請先關掉，等電工檢查。" },
  { id: "display-cabinet", en: "Because the cups in the display cabinet are fragile, I keep the doors locked when children visit.", ja: "飾り棚のカップは割れやすいので、子どもが来るときは扉に鍵をかけます。", zh: "展示櫃裡的杯子容易破，所以孩子來訪時我會把櫃門鎖上。" },
  { id: "wall-art", en: "Before hanging the wall art, we measured the space so it would be centered above the sofa.", ja: "壁飾りがソファの中央に来るように、掛ける前に位置を測りました。", zh: "掛牆面藝術前，我們先量好位置，讓它對準沙發中央。" },
  { id: "vase", en: "Change the water in the vase every day so the flowers stay fresh longer.", ja: "花を長くきれいに保つために、花瓶の水は毎日替えます。", zh: "每天更換花瓶裡的水，花就能維持新鮮更久。" },
  { id: "potted-plant", en: "Since this potted plant needs indirect light, I moved it away from the sunny window.", ja: "この鉢植えは明るい日陰を好むので、日差しの強い窓辺から離しました。", zh: "這盆栽需要間接光，所以我把它移離陽光直射的窗邊。" },
  { id: "dehumidifier", en: "When the dehumidifier tank is full, it stops automatically until I empty it.", ja: "除湿機はタンクが満水になると、私が水を捨てるまで自動で止まります。", zh: "除濕機水箱滿了會自動停止，直到我把水倒掉。" },
  { id: "power-outlet", en: "Do not plug another heater into this power outlet because the circuit is already heavily loaded.", ja: "回路に負担がかかっているので、このコンセントに別のヒーターをつながないでください。", zh: "這個迴路負載已很高，請不要再把另一臺暖氣插進這個插座。" },
  { id: "extension-cord", en: "Before using the extension cord, unwind it fully so it does not become hot.", ja: "熱くならないように、延長コードは全部伸ばしてから使ってください。", zh: "使用延長線前請完全攤開，以免過熱。" },
  { id: "charger", en: "Because I need the charger tomorrow, remind me to unplug it and put it in my bag tonight.", ja: "明日充電器が必要なので、今夜コンセントから抜いてかばんに入れるよう声をかけてください。", zh: "明天需要充電器，今晚請提醒我拔下來放進包包。" },
  { id: "speaker", en: "If the speaker keeps disconnecting, move the phone closer before pairing it again.", ja: "スピーカーとの接続が切れるなら、もう一度つなぐ前にスマートフォンを近づけてください。", zh: "喇叭如果一直斷線，重新配對前先把手機移近一點。" },
  { id: "game-console", en: "After finishing the game, turn off the game console instead of leaving it in sleep mode all night.", ja: "ゲームが終わったら、一晩中スリープにしたままにせず、ゲーム機の電源を切ってください。", zh: "遊戲結束後要關閉遊戲機，不要整晚留在休眠模式。" },
  { id: "router", en: "Since the signal is weak upstairs, we moved the router to a more central place.", ja: "二階の電波が弱かったので、ルーターを家の中央に近い場所へ移しました。", zh: "樓上訊號很弱，所以我們把路由器移到房子較中央的位置。" },
  { id: "telephone", en: "If the telephone rings while I am cooking, please answer it and take a message.", ja: "私が料理中に電話が鳴ったら、出て伝言を預かっておいてください。", zh: "我做飯時電話如果響了，請幫忙接聽並記下留言。" },
  { id: "doorbell", en: "When the video doorbell shows someone I do not know, I speak through the monitor without opening the door.", ja: "テレビドアホンに知らない人が映ったら、ドアを開けずにモニター越しに話します。", zh: "視訊門鈴顯示陌生人時，我不開門，直接透過螢幕交談。" },
  { id: "doormat", en: "Because it rained all day, I put an extra doormat inside to keep the floor dry.", ja: "一日中雨だったので、床をぬらさないように玄関の内側にも玄関マットを敷きました。", zh: "下了一整天雨，所以我在玄關內也多放一張墊子，保持地板乾燥。" },
  { id: "cabinet", en: "I moved the medicine to the top shelf of the cabinet so the children cannot reach it.", ja: "子どもの手が届かないように、薬をキャビネットの一番上の棚へ移しました。", zh: "我把藥移到櫃子最上層，讓孩子拿不到。" },
  { id: "back-cushion", en: "If you work on the sofa for a long time, use a back cushion to support your lower back.", ja: "ソファで長時間作業するなら、腰を支えるために背もたれクッションを使ってください。", zh: "如果長時間坐在沙發工作，請用靠墊支撐下背。" },
  { id: "footstool", en: "The footstool includes storage inside, so we keep the extra blankets there.", ja: "この足置きは中が収納になっているので、予備の毛布を入れています。", zh: "這張腳凳內部也能收納，所以我們把備用毯子放在裡面。" },
  { id: "recliner", en: "Before reclining the chair, check that nothing is behind it or under the footrest.", ja: "リクライニングチェアを倒す前に、後ろや足置きの下に物がないか確認してください。", zh: "把躺椅往後放之前，先確認後方和腳靠下方沒有東西。" },
  { id: "side-table", en: "Since the side table is narrow, use a non-slip coaster so the glass will not slide off.", ja: "サイドテーブルは狭いので、コップが滑り落ちないように滑り止め付きのコースターを使ってください。", zh: "邊桌很窄，請使用防滑杯墊，避免杯子滑落。" },
  { id: "magazine", en: "After reading the magazine, I marked the recipe page so I could try it later.", ja: "雑誌を読んだあと、今度作れるようにレシピのページへ印を付けました。", zh: "看完雜誌後，我標記了食譜那頁，之後可以試做。" },
  { id: "newspaper", en: "Although I read the news online, I buy the newspaper on Sundays for the local articles.", ja: "ニュースはネットで読みますが、地域の記事を読むために日曜日は新聞を買います。", zh: "雖然我在網路看新聞，星期天還是會為了地方報導買報紙。" },
  { id: "candle", en: "Never leave the candle burning when you leave the room, even for a short time.", ja: "短い時間でも、部屋を離れるときはろうそくの火を消してください。", zh: "即使只離開一下，也不要讓蠟燭無人看管地燃燒。" },
  { id: "diffuser", en: "Because the reed diffuser smelled too strong, I removed half of the reeds.", ja: "リードディフューザーの香りが強すぎたので、スティックを半分に減らしました。", zh: "擴香瓶味道太濃，所以我拿掉了一半的擴香枝。" },
  { id: "smoke-detector", en: "If the smoke detector gives a short beep every minute, its battery may need replacing.", ja: "煙式火災警報器が一分おきに短く鳴るなら、電池交換が必要かもしれません。", zh: "煙霧警報器如果每分鐘短響一次，可能需要更換電池。" },
  { id: "remote-control-holder", en: "We use a remote control holder because the remote used to disappear between the sofa cushions.", ja: "リモコンがソファの隙間によく入ってしまうので、リモコンホルダーを使っています。", zh: "遙控器以前常掉進沙發縫，所以我們使用遙控器收納盒。" },
  { id: "set-top-box", en: "After the set-top box updated, I restarted it because several channels had disappeared.", ja: "セットトップボックスの更新後にいくつかのチャンネルが消えたので、再起動しました。", zh: "電視盒更新後有幾個頻道不見了，所以我重新啟動。" },
  { id: "projector", en: "Since the room was still bright, we closed the curtains before turning on the projector.", ja: "部屋がまだ明るかったので、プロジェクターをつける前にカーテンを閉めました。", zh: "房間還很亮，所以打開投影機前我們先拉上窗簾。" },
  { id: "projector-screen", en: "If the projector screen is wrinkled, leave it down for a while before the presentation starts.", ja: "プロジェクタースクリーンにしわがあるなら、発表が始まる少し前から下ろしておきます。", zh: "投影幕如果有皺褶，簡報開始前先放下一段時間。" },
  { id: "robot-vacuum", en: "Before starting the robot vacuum, I pick up cables so it will not get stuck.", ja: "ロボット掃除機がケーブルに引っかからないように、動かす前に床のケーブルを片づけます。", zh: "啟動掃地機器人前，我會收起電線，避免它卡住。" },
];
