import type { MainWordComplexExample } from "./types";

export const OFFICE_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "desk", en: "Before leaving the office, I clear my desk so the cleaner can wipe it easily.", ja: "清掃の人が拭きやすいように、退社前にデスクの上を片づけます。", zh: "下班前我會清空辦公桌，讓清潔人員容易擦拭。" },
  { id: "laptop", en: "Because I will work from home tomorrow, I remembered to take my laptop and charger.", ja: "明日は在宅勤務なので、ノートパソコンと充電器を忘れずに持ち帰りました。", zh: "明天要在家工作，所以我記得把筆電和充電器帶回家。" },
  { id: "keyboard", en: "If the keyboard stops responding, reconnect it before restarting the whole computer.", ja: "キーボードが反応しなくなったら、パソコンを再起動する前につなぎ直してください。", zh: "鍵盤沒有反應時，先重新連接，再考慮重開整臺電腦。" },
  { id: "mouse", en: "Since the mouse battery was almost empty, I replaced it before the online presentation.", ja: "マウスの電池が切れそうだったので、オンライン発表の前に交換しました。", zh: "滑鼠電池快沒電了，所以我在視訊簡報前先更換。" },
  { id: "monitor", en: "I raised the monitor until the top of the screen was level with my eyes.", ja: "画面の上端が目の高さになるまで、モニターの位置を上げました。", zh: "我把螢幕抬高，直到畫面上緣與眼睛同高。" },
  { id: "notebook", en: "Although I keep digital notes, I use a notebook when I need to sketch an idea quickly.", ja: "普段はデジタルで記録しますが、考えをすぐ図にしたいときはノートを使います。", zh: "雖然平常使用數位筆記，需要快速畫出想法時我會用筆記本。" },
  { id: "pen", en: "If this pen runs out during the meeting, there are spare ones in the top drawer.", ja: "会議中にこのペンが書けなくなったら、一番上の引き出しに予備があります。", zh: "這支筆如果在會議中沒水，最上面的抽屜裡有備用的。" },
  { id: "stapler", en: "Because the report is thick, use the large stapler near the printer instead of this one.", ja: "報告書が厚いので、これは使わずプリンターのそばにある大きなホチキスを使ってください。", zh: "報告很厚，請改用印表機旁的大型釘書機，不要用這個。" },
  { id: "printer", en: "When the printer displays a paper error, check every tray before sending the job again.", ja: "プリンターに用紙エラーが出たら、もう一度印刷する前に全部のトレイを確認してください。", zh: "印表機顯示紙張錯誤時，重新列印前先檢查所有紙匣。" },
  { id: "office-chair", en: "I adjusted the office chair so my feet rest flat on the floor while I type.", ja: "入力中に足の裏が床につくように、オフィスチェアの高さを調節しました。", zh: "我調整辦公椅高度，讓打字時雙腳能平放在地上。" },
  { id: "computer", en: "Before the computer installs the update, save your files because it may restart automatically.", ja: "パソコンが自動で再起動することがあるので、更新前にファイルを保存してください。", zh: "電腦安裝更新前請先儲存檔案，因為它可能自動重開。" },
  { id: "mouse-pad", en: "When the pointer started jumping, I cleaned the mouse pad and the sensor underneath the mouse.", ja: "ポインターが飛ぶようになったので、マウスパッドとマウス底面のセンサーを掃除しました。", zh: "游標開始亂跳，所以我清潔了滑鼠墊和滑鼠底部感應器。" },
  { id: "photocopier", en: "If the photocopier jams again, leave the paper inside and call the maintenance desk.", ja: "コピー機がまた詰まったら、紙を無理に取らず保守窓口へ連絡してください。", zh: "影印機如果又卡紙，不要硬拉，請聯絡維修窗口。" },
  { id: "scanner", en: "After scanning the contract, check that every page is readable before deleting the original file.", ja: "契約書をスキャンしたら、元のファイルを消す前に全ページが読めるか確認します。", zh: "掃描合約後，刪除原檔前先確認每一頁都清楚可讀。" },
  { id: "mobile-phone", en: "Since the meeting is confidential, leave your smartphone outside the room before it begins.", ja: "機密の会議なので、始まる前にスマートフォンを部屋の外へ置いてください。", zh: "這場會議涉及機密，開始前請把手機留在會議室外。" },
  { id: "headphones", en: "I use headphones in the open office so my online meeting does not disturb anyone nearby.", ja: "周りの人の邪魔にならないように、オープンオフィスでのオンライン会議にはヘッドホンを使います。", zh: "在開放式辦公室開線上會議時我會戴耳機，避免打擾附近的人。" },
  { id: "microphone", en: "If there is an echo, mute the microphone whenever you are not speaking.", ja: "音が反響する場合は、話していない間マイクをミュートにしてください。", zh: "如果有回音，不說話時請把麥克風靜音。" },
  { id: "webcam", en: "Before joining the interview, I checked the webcam angle so the background looked tidy.", ja: "面接に参加する前に、背景が整って見えるようウェブカメラの角度を確認しました。", zh: "加入面試前，我檢查網路攝影機角度，讓背景看起來整潔。" },
  { id: "whiteboard", en: "After the discussion, we photographed the whiteboard so nobody would lose the decisions we made.", ja: "決めた内容を残せるように、話し合いのあとホワイトボードを撮影しました。", zh: "討論後我們拍下白板，才不會遺失做出的決定。" },
  { id: "whiteboard-marker", en: "Because the whiteboard marker was nearly dry, the writing could not be seen from the back row.", ja: "ホワイトボードマーカーのインクが薄く、後ろの席から文字が見えませんでした。", zh: "白板筆快沒水了，坐在後排看不清楚字。" },
  { id: "eraser", en: "If the whiteboard eraser leaves marks, clean its felt surface before using it again.", ja: "ホワイトボード用イレーザーで跡が残るなら、もう一度使う前に表面のフェルトを掃除します。", zh: "白板擦留下痕跡時，再用以前先清潔它的絨布表面。" },
  { id: "sticky-notes", en: "I use different colors of sticky notes so urgent tasks stand out from ordinary reminders.", ja: "急ぎの仕事が普通のメモと区別できるように、付箋の色を変えています。", zh: "我用不同顏色的便利貼，讓緊急工作能從一般提醒中顯眼。" },
  { id: "ballpoint-pen", en: "Since the form will be copied, fill it in with a dark ballpoint pen rather than a pencil.", ja: "この用紙はコピーするので、鉛筆ではなく濃い色のボールペンで記入してください。", zh: "這張表格之後要影印，請用深色原子筆填寫，不要用鉛筆。" },
  { id: "highlighter", en: "When reviewing the contract, use the highlighter only on sections that need a decision.", ja: "契約書を確認するときは、判断が必要な箇所だけ蛍光ペンで印を付けてください。", zh: "檢查合約時，只用螢光筆標出需要決定的部分。" },
  { id: "marker", en: "I wrote the room number with a permanent marker so rain would not wash it off the box.", ja: "雨で消えないように、油性マーカーで箱に部屋番号を書きました。", zh: "我用油性筆在箱子上寫房號，這樣雨水不會沖掉。" },
  { id: "ruler", en: "Before cutting the label, measure it with a ruler so it fits the folder tab.", ja: "フォルダーの見出しに合うように、ラベルを切る前に定規で測ります。", zh: "裁標籤前先用尺量，讓它能放進資料夾標籤處。" },
  { id: "utility-knife", en: "Because the utility knife blade is exposed, retract it immediately after cutting the box.", ja: "刃が出たままだと危ないので、箱を切ったらすぐカッターナイフへ戻してください。", zh: "美工刀刀片露在外面很危險，裁完紙箱後請立刻收回。" },
  { id: "tape", en: "If the tape will not stick, wipe the dust off the surface before trying again.", ja: "セロテープが付かないときは、もう一度貼る前に表面のほこりを拭いてください。", zh: "膠帶黏不住時，先擦掉表面灰塵再試一次。" },
  { id: "glue", en: "Let the glue dry completely before putting the repaired document back in the folder.", ja: "直した書類をフォルダーへ戻す前に、のりを完全に乾かしてください。", zh: "修好的文件放回資料夾前，要讓膠水完全乾燥。" },
  { id: "staples", en: "When you refill the stapler, make sure the staples are the correct size for that model.", ja: "ホチキスの針を補充するときは、その機種に合うサイズか確認してください。", zh: "補充訂書針時，請確認尺寸適合那臺釘書機。" },
  { id: "paper-clip", en: "Use a paper clip if the pages may need to be separated again later.", ja: "あとで書類を分ける可能性があるなら、ホチキスではなくゼムクリップを使います。", zh: "如果之後可能還要拆開文件，就使用迴紋針。" },
  { id: "binder-clip", en: "Because the stack was too thick for a paper clip, I secured it with a binder clip.", ja: "書類が厚くてゼムクリップでは留まらなかったので、ダブルクリップを使いました。", zh: "這疊文件太厚，迴紋針夾不住，所以我用了長尾夾。" },
  { id: "folder", en: "I keep the handout in a clear file folder so it does not get bent in my bag.", ja: "かばんの中で折れないように、配布資料をクリアファイルへ入れています。", zh: "我把講義放進透明資料夾，避免在包包裡折到。" },
  { id: "file-folder", en: "After checking each invoice, I place it in the file folder for the correct month.", ja: "請求書を確認したら、該当する月の個別フォルダーへ入れます。", zh: "每張請款單確認後，我會放進對應月份的檔案夾。" },
  { id: "document", en: "Before sharing the document, remove the comments that were only meant for our team.", ja: "書類を共有する前に、社内向けだけのコメントを削除してください。", zh: "分享文件前，請移除只供我們團隊看的註解。" },
  { id: "paper", en: "Since the draft is not final, print it on both sides to use less paper.", ja: "まだ最終版ではないので、紙を節約するために両面印刷してください。", zh: "草稿還不是定稿，請雙面列印以節省紙張。" },
  { id: "notepad", en: "I keep a notepad beside the phone so I can write down messages while speaking.", ja: "電話で話しながら伝言を書けるように、そばにメモ帳を置いています。", zh: "我在電話旁放便條本，通話時就能記下留言。" },
  { id: "envelope", en: "Seal the envelope only after checking that every page of the contract is inside.", ja: "契約書が全ページ入っているか確認してから、封筒を閉じてください。", zh: "確認合約每一頁都在裡面後，再封上信封。" },
  { id: "business-card", en: "After receiving the business card, I repeated the client's name to make sure I pronounced it correctly.", ja: "名刺を受け取ったあと、読み方を確認するために取引先の名前を繰り返しました。", zh: "收到名片後，我重複念了客戶姓名，確認發音正確。" },
  { id: "calendar", en: "When the deadline changed, I updated the shared calendar so everyone saw the new date.", ja: "締め切りが変わったので、全員に新しい日付が伝わるよう共有カレンダーを更新しました。", zh: "截止日改變後，我更新共用日曆，讓大家看到新日期。" },
  { id: "paper-shredder", en: "If the paper shredder becomes hot, stop feeding paper and let the motor cool down.", ja: "シュレッダーが熱くなったら、紙を入れるのをやめてモーターを冷ましてください。", zh: "碎紙機變熱時停止放紙，讓馬達冷卻。" },
  { id: "filing-cabinet", en: "Because these records contain personal information, the filing cabinet must remain locked.", ja: "この記録には個人情報が含まれるので、ファイリングキャビネットには常に鍵をかけます。", zh: "這些紀錄含個人資料，所以文件櫃必須一直上鎖。" },
  { id: "conference-table", en: "Before the guests arrive, arrange the name cards around the conference table.", ja: "来客が到着する前に、会議テーブルへ名札を並べてください。", zh: "客人抵達前，請在會議桌周圍擺好名牌。" },
  { id: "meeting-room", en: "If the meeting room is still occupied at three, call me instead of interrupting them.", ja: "三時になっても会議室が使用中なら、中へ入らず私に連絡してください。", zh: "三點時會議室如果還有人，請聯絡我，不要打斷他們。" },
  { id: "reception-desk", en: "Since the visitor arrived early, the reception desk asked him to wait in the lobby.", ja: "来客が早く着いたので、受付カウンターでロビーに待つよう案内しました。", zh: "訪客提早抵達，接待櫃檯請他在大廳等候。" },
  { id: "water-dispenser", en: "When the water dispenser bottle is empty, notify facilities rather than lifting it alone.", ja: "ウォーターサーバーのボトルが空になったら、一人で持ち上げず設備担当へ連絡してください。", zh: "飲水機水桶空了時，請通知總務，不要一個人搬。" },
  { id: "coffee-machine", en: "After using the coffee machine, empty the grounds so it is ready for the next person.", ja: "次の人がすぐ使えるように、コーヒーマシンを使ったらかすを捨ててください。", zh: "咖啡機用完後請倒掉咖啡渣，讓下一個人可以直接使用。" },
  { id: "access-card", en: "If the access card does not open the door, ask security to check its expiration date.", ja: "入館カードでドアが開かない場合は、警備員に有効期限を確認してもらってください。", zh: "門禁卡如果打不開門，請警衛檢查有效期限。" },
  { id: "employee-id-card", en: "Because the employee ID card contains personal information, report it immediately if it is lost.", ja: "社員証には個人情報が入っているので、なくした場合はすぐに届け出てください。", zh: "員工證含有個人資料，遺失時請立刻通報。" },
  { id: "office-supplies", en: "Before ordering more office supplies, check the storage room so we do not buy duplicates.", ja: "同じ物を重ねて買わないように、事務用品を注文する前に倉庫を確認します。", zh: "訂購辦公用品前先檢查儲藏室，免得重複購買。" },
  { id: "invoice", en: "If the amount on the invoice differs from the quote, contact the supplier before paying it.", ja: "請求書の金額が見積書と違う場合は、支払う前に取引先へ確認してください。", zh: "請款單金額若與報價不同，付款前先聯絡供應商。" },
];
