import type { MainWordComplexExample } from "./types";

export const STREET_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "traffic-light", en: "Even when the street is empty, wait until the traffic light turns green before crossing.", ja: "車がいなくても、信号機が青になるまで待ってから渡ってください。", zh: "即使路上沒有車，也要等紅綠燈變綠再過馬路。" },
  { id: "crosswalk", en: "Because the road is busy, walk to the crosswalk instead of crossing between parked cars.", ja: "交通量が多いので、駐車中の車の間を渡らず横断歩道まで歩いてください。", zh: "馬路車很多，請走到斑馬線，不要從停放車輛之間穿越。" },
  { id: "sidewalk", en: "When the sidewalk is crowded, keep to one side so other people can pass.", ja: "歩道が混んでいるときは、ほかの人が通れるように片側を歩いてください。", zh: "人行道擁擠時請靠一側走，讓其他人能通過。" },
  { id: "street-sign", en: "If the map and the street sign show different names, check which direction you are facing.", ja: "地図と案内標識の名前が違う場合は、自分がどちらを向いているか確認してください。", zh: "地圖和路標顯示不同名稱時，先確認自己面向哪個方向。" },
  { id: "bench", en: "Since my mother was tired from walking, we rested on a bench near the station.", ja: "母が歩き疲れたので、駅の近くのベンチで休みました。", zh: "媽媽走累了，所以我們在車站附近的長椅休息。" },
  { id: "streetlight", en: "The streetlight near our house was broken, so I reported it to the city office.", ja: "家の近くの街灯が切れていたので、市役所へ連絡しました。", zh: "我家附近的路燈壞了，所以我向市公所通報。" },
  { id: "trash-can", en: "If the trash can is full, take your rubbish home instead of leaving it beside the bin.", ja: "ゴミ箱がいっぱいなら、横に置かずゴミを持ち帰ってください。", zh: "垃圾桶滿了就把垃圾帶回家，不要放在旁邊。" },
  { id: "mailbox", en: "Before putting the envelope in the mailbox, check that the address and postage are correct.", ja: "封筒を郵便ポストへ入れる前に、住所と切手が正しいか確認してください。", zh: "把信封投入郵筒前，先確認地址和郵資正確。" },
  { id: "street", en: "Because this street becomes one-way during the morning rush, we take another route to school.", ja: "この通りは朝の混雑時に一方通行になるので、学校へは別の道を使います。", zh: "這條街早晨尖峰時段會變成單行道，所以我們走別條路去學校。" },
  { id: "road", en: "If the road is closed because of snow, follow the detour signs rather than turning around here.", ja: "雪で道路が通行止めなら、ここで引き返さず迂回の標識に従ってください。", zh: "馬路因雪封閉時，請依繞道標誌前進，不要在這裡迴轉。" },
  { id: "intersection", en: "When you reach the large intersection, stay in the right lane because we will turn soon.", ja: "大きな交差点に着いたら、すぐ曲がるので右の車線を走ってください。", zh: "到大十字路口時請走右側車道，因為很快要轉彎。" },
  { id: "traffic-sign", en: "Although the road looks open, the traffic sign says vehicles may not enter after six.", ja: "道は開いているように見えますが、交通標識では六時以降車両進入禁止です。", zh: "道路看起來開放，但交通標誌寫著六點後車輛禁止進入。" },
  { id: "stop-sign", en: "After stopping at the stop sign, look both ways before entering the narrow road.", ja: "一時停止標識で止まったら、左右を確認してから細い道へ入ってください。", zh: "在停車標誌前停下後，左右查看再進入窄路。" },
  { id: "bus-stop", en: "Since the bus stop has moved temporarily, we need to wait in front of the bank today.", ja: "バス停が一時的に移動したので、今日は銀行の前で待つ必要があります。", zh: "公車站暫時移位，今天我們要在銀行前等車。" },
  { id: "station", en: "If you arrive at the station first, wait by the central ticket gate where it is easy to meet.", ja: "先に駅へ着いたら、見つけやすい中央改札のそばで待っていてください。", zh: "如果你先到車站，請在容易會合的中央剪票口旁等。" },
  { id: "subway-station", en: "Because this subway station has several exits, check the exit number before going upstairs.", ja: "この地下鉄の駅には出口が多いので、地上へ出る前に番号を確認してください。", zh: "這座地鐵站有很多出口，上樓前先確認出口編號。" },
  { id: "taxi-stand", en: "When it rains, the line at the taxi stand gets long, so allow extra time.", ja: "雨の日はタクシー乗り場の列が長くなるので、時間に余裕を持ってください。", zh: "下雨時計程車站排隊會變長，請多留一點時間。" },
  { id: "parking-lot", en: "If the parking lot is full, the sign at the entrance shows another one nearby.", ja: "駐車場が満車なら、入口の案内に近くの別の駐車場が表示されています。", zh: "停車場如果滿了，入口標示會顯示附近另一個停車場。" },
  { id: "parking-space", en: "Because this parking space is reserved for deliveries, move the car before the truck arrives.", ja: "この駐車スペースは搬入用なので、トラックが来る前に車を移してください。", zh: "這個停車位供送貨使用，請在貨車抵達前把車移走。" },
  { id: "parking-meter", en: "Before the parking meter expires, return to the car or pay for more time if allowed.", ja: "パーキングメーターの時間が切れる前に車へ戻るか、可能なら時間を追加してください。", zh: "停車收費表時間到以前回到車上，若規定允許就加付時間。" },
  { id: "bike-lane", en: "When turning across a bike lane, check behind you because a bicycle may be approaching.", ja: "自転車専用レーンを横切って曲がるときは、自転車が来ていないか後ろを確認してください。", zh: "轉彎穿過自行車道時要查看後方，因為可能有腳踏車接近。" },
  { id: "lane", en: "Since our exit is coming up, change to the left lane when it is safe.", ja: "もうすぐ出口なので、安全を確認して左の車線へ移ってください。", zh: "出口快到了，確認安全後切換到左側車線。" },
  { id: "pedestrian-bridge", en: "Although the pedestrian bridge has stairs, it is safer than crossing this wide road below.", ja: "歩道橋には階段がありますが、この広い道路を下で渡るより安全です。", zh: "天橋雖然有樓梯，但比直接穿越下面的寬馬路安全。" },
  { id: "underpass", en: "If heavy rain floods the underpass, use the crossing above instead of entering it.", ja: "大雨で地下道が冠水していたら、中へ入らず地上の横断歩道を使ってください。", zh: "大雨使地下道淹水時，不要進入，改走地面斑馬線。" },
  { id: "bridge", en: "Because the bridge is closed for inspection, pedestrians must use the temporary path beside it.", ja: "橋は点検のため通行止めなので、歩行者は横の仮設通路を使います。", zh: "橋梁因檢查封閉，行人必須走旁邊的臨時通道。" },
  { id: "tunnel", en: "Keep a safe distance in the tunnel because sudden braking is harder to see ahead.", ja: "トンネル内では前方の急ブレーキが見えにくいので、十分な車間距離を取ってください。", zh: "隧道內較難看見前車突然煞車，請保持安全距離。" },
  { id: "roundabout", en: "Before entering the roundabout, slow down and give way to vehicles already inside.", ja: "ロータリーへ入る前に速度を落とし、中を走っている車を優先してください。", zh: "進入圓環前先減速，禮讓已在環內的車輛。" },
  { id: "corner", en: "The cafe is just around the corner, so call me if you pass the bank.", ja: "カフェは角を曲がってすぐなので、銀行を通り過ぎたら電話してください。", zh: "咖啡店就在轉角後面，如果你走過銀行就打電話給我。" },
  { id: "alley", en: "Because the alley is poorly lit at night, I use the main street when I walk home alone.", ja: "その路地は夜暗いので、一人で帰るときは大通りを歩きます。", zh: "那條巷子晚上很暗，所以我獨自回家時走大街。" },
  { id: "shop", en: "If the shop does not have your size, the staff can order it from another branch.", ja: "店に合うサイズがなければ、店員が別の店舗から取り寄せてくれます。", zh: "商店沒有你的尺寸時，店員可以從其他分店調貨。" },
  { id: "convenience-store", en: "Since the station cafe was closed, I bought breakfast at the convenience store.", ja: "駅のカフェが閉まっていたので、コンビニで朝ご飯を買いました。", zh: "車站咖啡店沒開，所以我在便利商店買早餐。" },
  { id: "restaurant", en: "Because the restaurant is popular on weekends, book a table before you go.", ja: "週末はそのレストランが混むので、行く前に予約してください。", zh: "那間餐廳週末很熱門，去以前請先訂位。" },
  { id: "cafe", en: "If the cafe is full, we can order our drinks to go and sit in the park.", ja: "カフェが満席なら、飲み物を持ち帰りにして公園で飲めます。", zh: "咖啡店如果客滿，我們可以外帶飲料去公園坐。" },
  { id: "bank", en: "Before going to the bank, check whether the counter is open or only the ATM is available.", ja: "銀行へ行く前に、窓口が開いているかATMだけ使えるのか確認します。", zh: "去銀行前先確認櫃檯是否營業，還是只有提款機可用。" },
  { id: "post-office", en: "If you want the package to arrive tomorrow, ask the post office about express delivery.", ja: "荷物を明日届けたいなら、郵便局で速達について聞いてください。", zh: "如果希望包裹明天抵達，可以到郵局詢問快捷寄送。" },
  { id: "pharmacy", en: "Because this pharmacy keeps my prescription on file, I can collect the refill after work.", ja: "この薬局には処方箋の記録があるので、仕事帰りに追加の薬を受け取れます。", zh: "這家藥局保有我的處方紀錄，所以我下班後可以領補充藥品。" },
  { id: "supermarket", en: "Since the supermarket is crowded after six, I shop before work when I have time.", ja: "スーパーは六時を過ぎると混むので、時間がある日は出勤前に買い物します。", zh: "超市六點後很擁擠，有時間的日子我會上班前去買。" },
  { id: "vending-machine", en: "If the vending machine takes your money without giving a drink, call the number on the front.", ja: "自動販売機にお金を入れても飲み物が出ない場合は、正面の番号へ連絡してください。", zh: "自動販賣機吃錢卻沒出飲料時，請打正面的聯絡電話。" },
  { id: "park", en: "Although the park closes at sunset, the path along the river remains open.", ja: "公園は日没で閉まりますが、川沿いの道はそのあとも通れます。", zh: "公園日落時關閉，但河邊步道仍然開放。" },
  { id: "tree", en: "Because a branch had broken in the wind, we stayed away from the tree and called the city.", ja: "風で枝が折れていたので、木から離れて市役所へ連絡しました。", zh: "樹枝被風吹斷了，所以我們遠離那棵樹並通知市公所。" },
  { id: "flower-bed", en: "The volunteers planted seasonal flowers in the flower bed so the entrance looks welcoming.", ja: "入口が明るく見えるように、ボランティアが花壇へ季節の花を植えました。", zh: "志工在花圃種下當季花卉，讓入口看起來更親切。" },
  { id: "pedestrian", en: "When a pedestrian is waiting at the crossing, slow down and be ready to stop.", ja: "横断歩道で歩行者が待っているときは、速度を落として止まれるようにしてください。", zh: "行人在斑馬線等待時要減速，並準備停車。" },
  { id: "signboard", en: "Since the shop moved upstairs, its signboard now points toward the side entrance.", ja: "店が二階へ移ったので、看板は横の入口を示しています。", zh: "商店搬到二樓，所以招牌現在指向側門。" },
  { id: "billboard", en: "The billboard is being replaced, so the sidewalk below it is temporarily closed.", ja: "広告看板を交換しているため、その下の歩道は一時的に通れません。", zh: "廣告看板正在更換，所以下方人行道暫時封閉。" },
  { id: "fire-hydrant", en: "Leave the area around the fire hydrant clear so firefighters can reach it quickly.", ja: "消防隊がすぐ使えるように、消火栓の周りには物を置かないでください。", zh: "消防栓周圍請保持暢通，讓消防員能迅速使用。" },
  { id: "construction-zone", en: "Because trucks enter the construction zone without warning, follow the guard's directions.", ja: "工事現場にはトラックが急に入ることがあるので、誘導員の指示に従ってください。", zh: "貨車可能突然進入施工區，請遵從引導員指示。" },
  { id: "roadblock", en: "When we reached the barricade, an officer directed us to a side road.", ja: "バリケードまで来ると、警察官が脇道へ案内してくれました。", zh: "我們到達路障時，警察引導我們改走側路。" },
  { id: "traffic-cone", en: "Do not move the traffic cone even if the parking space behind it looks empty.", ja: "奥の駐車スペースが空いて見えても、カラーコーンを動かさないでください。", zh: "即使後面的停車位看起來空著，也不要移動交通錐。" },
  { id: "manhole-cover", en: "After heavy rain, avoid stepping on the manhole cover because it may be loose.", ja: "大雨のあとは緩んでいることがあるので、マンホールの蓋を踏まないでください。", zh: "大雨後人孔蓋可能鬆動，請避免踩上去。" },
  { id: "utility-pole", en: "Because the utility pole was damaged by a car, the street was closed until it was checked.", ja: "電柱が車にぶつけられたため、点検が終わるまで通りは通行止めになりました。", zh: "電線桿被車撞壞，街道在檢查完成前封閉。" },
  { id: "power-lines", en: "If fallen branches are touching the power lines, stay away and call the power company.", ja: "落ちた枝が電線に触れていたら、近づかず電力会社へ連絡してください。", zh: "倒下的樹枝碰到電線時，請遠離並通知電力公司。" },
  { id: "security-camera", en: "The police checked the security camera because it faces the place where the bicycle disappeared.", ja: "自転車がなくなった場所を映しているので、警察が防犯カメラを確認しました。", zh: "監視器正對腳踏車失竊處，所以警方查看了畫面。" },
  { id: "pedestrian-button", en: "After pressing the pedestrian button, wait for the green signal instead of pressing it again.", ja: "歩行者用押しボタンを押したら、何度も押さず青信号を待ってください。", zh: "按下行人按鈕後請等綠燈，不要一直重按。" },
  { id: "street-vendor", en: "Since the food cart accepts cash only, I withdrew money before ordering ramen.", ja: "屋台は現金しか使えないので、ラーメンを注文する前にお金を下ろしました。", zh: "餐車只收現金，所以點拉麵前我先領了錢。" },
  { id: "vendor", en: "If you buy several items from the market stall, the vendor may put them in one bag.", ja: "露店でいくつか買うと、店の人が一つの袋にまとめてくれることがあります。", zh: "如果在市場攤位買好幾樣，攤販可能會裝在同一個袋子裡。" },
  { id: "newsstand", en: "Although the newsstand is small, it also sells transit cards and bottled drinks.", ja: "その新聞売店は小さいですが、交通カードや飲み物も売っています。", zh: "那間報攤雖小，也販售交通卡和瓶裝飲料。" },
];
