import type {
  MainWordComplexExample,
  MainWordSimpleExampleOverride,
} from "./types";

export const TRANSPORTATION_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "car", en: "Because parking near the station is expensive, I leave the car at home on weekdays.", ja: "駅の近くは駐車料金が高いので、平日は車を家に置いていきます。", zh: "車站附近停車很貴，所以平日我把汽車留在家裡。" },
  { id: "bus", en: "If the last bus has already left, we will need to walk from the station.", ja: "最終バスがもう出ていたら、駅から歩いて帰る必要があります。", zh: "末班公車如果已經開走，我們就得從車站走回去。" },
  { id: "bicycle", en: "Before riding my bicycle at night, I check that both lights are working.", ja: "夜に自転車へ乗る前に、前後のライトが点くか確認します。", zh: "晚上騎腳踏車前，我會檢查前後車燈是否正常。" },
  { id: "motorcycle", en: "Since the road was icy, he left his motorcycle at home and took the train.", ja: "道路が凍っていたので、彼はバイクを家に置いて電車で行きました。", zh: "道路結冰，所以他把機車留在家裡，改搭火車。" },
  { id: "train", en: "When the train is delayed, the station app usually shows which platform to use.", ja: "電車が遅れているときは、駅のアプリで使うホームが表示されることが多いです。", zh: "火車誤點時，車站應用程式通常會顯示要使用哪個月臺。" },
  { id: "airplane", en: "Because the airplane leaves early, we will stay near the airport the night before.", ja: "飛行機の出発が早いので、前の晩は空港の近くに泊まります。", zh: "飛機很早起飛，所以我們前一晚住在機場附近。" },
  { id: "boat", en: "If the wind becomes stronger, the boat tour may return to the harbor early.", ja: "風が強くなった場合は、ボートツアーが早めに港へ戻ることがあります。", zh: "風變強時，小船行程可能會提早返回港口。" },
  { id: "taxi", en: "Since we have several heavy suitcases, taking a taxi will be easier than changing trains.", ja: "重いスーツケースがいくつもあるので、電車を乗り換えるよりタクシーのほうが楽です。", zh: "我們有好幾個重行李箱，搭計程車會比轉乘火車輕鬆。" },
  { id: "subway", en: "Although the subway is crowded in the morning, it is still faster than driving downtown.", ja: "朝の地下鉄は混んでいますが、中心部へは車より早く着きます。", zh: "早晨地鐵雖然擁擠，去市中心還是比開車快。" },
  { id: "school-bus", en: "If my daughter misses the school bus, I have to drive her to school before work.", ja: "娘がスクールバスに乗り遅れると、出勤前に学校まで送らなければなりません。", zh: "女兒如果錯過校車，我上班前就得開車送她去學校。" },
  { id: "coach", en: "Because the coach ride takes four hours, it stops once so passengers can take a break.", ja: "観光バスは四時間走るので、乗客が休憩できるよう途中で一度止まります。", zh: "遊覽車車程四小時，中途會停一次讓乘客休息。" },
  { id: "minibus", en: "When the hotel minibus is full, it makes another trip to the station twenty minutes later.", ja: "ホテルのマイクロバスが満席になると、二十分後にもう一度駅へ向かいます。", zh: "飯店小巴客滿時，二十分鐘後會再跑一趟車站。" },
  { id: "truck", en: "Since the truck is too tall for this bridge, the driver must use the road around it.", ja: "トラックはこの橋を通るには高すぎるので、運転手は迂回路を使わなければなりません。", zh: "貨車太高無法通過這座橋，司機必須繞道。" },
  { id: "van", en: "We rented a van because five people and all their luggage would not fit in a small car.", ja: "五人と全員分の荷物が小さい車に収まらないので、バンを借りました。", zh: "五個人和所有行李塞不進小車，所以我們租了廂型車。" },
  { id: "ambulance", en: "When the ambulance approaches with its siren on, move aside and let it pass.", ja: "サイレンを鳴らした救急車が近づいたら、道を空けて通してください。", zh: "救護車鳴笛接近時，請靠邊讓它通過。" },
  { id: "police-car", en: "Because a police car was stopped ahead, drivers slowed down and changed lanes carefully.", ja: "前方にパトカーが止まっていたので、運転手は速度を落として慎重に車線を変えました。", zh: "前方停著警車，駕駛都減速並小心換道。" },
  { id: "fire-truck", en: "As the fire truck left the station, all the cars stopped to give it a clear path.", ja: "消防車が消防署を出ると、道を空けるためにすべての車が止まりました。", zh: "消防車離開消防局時，所有車輛都停下來讓出通道。" },
  { id: "garbage-truck", en: "Since the garbage truck comes early on Tuesdays, put the bags outside the night before.", ja: "火曜日はゴミ収集車が早く来るので、前の晩に袋を出しておいてください。", zh: "垃圾車星期二很早來，請前一晚把垃圾袋放出去。" },
  { id: "tow-truck", en: "Because the car would not start, we called a tow truck to take it to the repair shop.", ja: "車のエンジンがかからなかったので、レッカー車を呼んで修理工場まで運んでもらいました。", zh: "汽車發不動，所以我們叫拖吊車把它送到修車廠。" },
  { id: "camper-van", en: "Before sleeping in the camper van, we opened the roof vent to let fresh air inside.", ja: "キャンピングカーで寝る前に、新しい空気が入るよう天井の換気口を開けました。", zh: "在露營車裡睡覺前，我們打開車頂通風口讓新鮮空氣進來。" },
  { id: "sports-car", en: "Although the sports car is fast, its low body makes steep parking ramps difficult.", ja: "スポーツカーは速いですが、車体が低いため急な駐車場の坂を上りにくいです。", zh: "跑車雖然很快，但車身低，很難駛上陡峭的停車場斜坡。" },
  { id: "electric-car", en: "If we charge the electric car overnight, it has enough power for tomorrow's trip.", ja: "夜のうちに電気自動車を充電すれば、明日の移動に十分な電力がたまります。", zh: "如果整晚為電動車充電，電量就足夠明天出門。" },
  { id: "electric-scooter", en: "Before renting an electric scooter, check where local rules allow you to ride it.", ja: "電動キックボードを借りる前に、地域のルールで走れる場所を確認してください。", zh: "租電動滑板車前，先確認當地規定允許在哪裡騎。" },
  { id: "scooter", en: "Because the sidewalk was crowded, the child carried his scooter until he reached the park.", ja: "歩道が混んでいたので、子どもは公園に着くまでキックボードを持って歩きました。", zh: "人行道很擁擠，所以孩子把滑板車提到公園才騎。" },
  { id: "skateboard", en: "If you practice on a skateboard near other people, wear protection and keep your speed low.", ja: "人の近くでスケートボードを練習するなら、防具を着けて速度を落としてください。", zh: "在人群附近練滑板時，要戴護具並降低速度。" },
  { id: "roller-skates", en: "Since the path was wet, we waited for it to dry before using the roller skates.", ja: "道がぬれていたので、乾くまで待ってからローラースケートを使いました。", zh: "路面是濕的，所以我們等乾了才穿溜冰鞋。" },
  { id: "tram", en: "When the tram shares the road with cars, look carefully before crossing its tracks.", ja: "路面電車が車と同じ道路を走る場所では、線路を渡る前によく確認してください。", zh: "路面電車和汽車共用道路時，穿越軌道前要仔細查看。" },
  { id: "light-rail", en: "Because the light rail runs every ten minutes, we do not need to check the timetable closely.", ja: "ライトレールは十分おきに来るので、時刻表を細かく確認する必要はありません。", zh: "輕軌每十分鐘一班，所以不必仔細查時刻表。" },
  { id: "high-speed-train", en: "If we take the high-speed train, we can arrive before noon without flying.", ja: "新幹線に乗れば、飛行機を使わなくても昼前に着けます。", zh: "如果搭高鐵，不用坐飛機也能在中午前抵達。" },
  { id: "monorail", en: "Since the monorail connects directly to the airport, we avoided carrying bags up station stairs.", ja: "モノレールは空港へ直通するので、駅の階段で荷物を運ばずに済みました。", zh: "單軌電車直達機場，我們不用扛行李走車站樓梯。" },
  { id: "cable-car", en: "When the cable car is crowded, wait for the next one rather than blocking the doors.", ja: "ケーブルカーが混んでいるときは、ドアをふさがず次の便を待ってください。", zh: "纜車擁擠時請等下一班，不要堵住車門。" },
  { id: "gondola-lift", en: "If strong winds stop the gondola lift, visitors must return down the mountain by bus.", ja: "強風でゴンドラリフトが止まると、利用者はバスで山を下りなければなりません。", zh: "強風使吊艙纜車停駛時，遊客必須搭巴士下山。" },
  { id: "helicopter", en: "Because the mountain road was blocked, a helicopter delivered supplies to the village.", ja: "山道がふさがれていたので、ヘリコプターが村へ物資を運びました。", zh: "山路被封，所以直升機把物資送到村莊。" },
  { id: "hot-air-balloon", en: "Although we booked a hot air balloon ride, it was canceled because the wind was too strong.", ja: "熱気球を予約していましたが、風が強すぎたため中止になりました。", zh: "我們雖然預訂了熱氣球行程，但風太強所以取消。" },
  { id: "airship", en: "When the airship appeared above the stadium, everyone looked up to see the advertisement.", ja: "飛行船がスタジアムの上に現れると、広告を見るためにみんなが空を見上げました。", zh: "飛船出現在體育場上空時，大家都抬頭看廣告。" },
  { id: "rocket", en: "Because the rocket launch was delayed by weather, we checked the new launch time on the news.", ja: "天候でロケットの打ち上げが延期されたので、ニュースで新しい打ち上げ時刻を確認しました。", zh: "火箭發射因天氣延期，所以我們從新聞確認了新的發射時間。" },
  { id: "ferry", en: "If the bridge traffic is heavy, taking the ferry across the bay may be faster.", ja: "橋が渋滞しているなら、湾を渡るフェリーのほうが早いかもしれません。", zh: "橋上塞車時，搭渡輪過海灣可能更快。" },
  { id: "cruise-ship", en: "Before returning to the cruise ship, passengers must pass security at the port.", ja: "クルーズ船へ戻る前に、乗客は港で保安検査を受けなければなりません。", zh: "回到遊輪前，乘客必須在港口通過安檢。" },
  { id: "sailboat", en: "Since there was almost no wind, the sailboat returned to the harbor using its motor.", ja: "風がほとんどなかったので、ヨットはエンジンを使って港へ戻りました。", zh: "幾乎沒有風，所以帆船用引擎回到港口。" },
  { id: "speedboat", en: "Because the speedboat moves quickly, everyone must put on a life jacket before boarding.", ja: "スピードボートは速く走るので、乗る前に全員が救命胴衣を着けます。", zh: "快艇速度很快，所以所有人上船前都要穿救生衣。" },
  { id: "canoe", en: "If the canoe tips over, stay with it because it is easier for rescuers to see.", ja: "カヌーが転覆したら、救助する人から見つけやすいので船のそばにいてください。", zh: "獨木舟翻覆時留在船旁，救援人員比較容易看見。" },
  { id: "kayak", en: "Before taking the kayak onto the lake, we checked that the drain plug was closed.", ja: "カヤックを湖へ出す前に、水抜き栓が閉まっているか確認しました。", zh: "把皮艇推進湖裡前，我們檢查排水塞是否關好。" },
  { id: "submarine", en: "Although the submarine at the museum no longer sails, visitors can walk through its cabins.", ja: "博物館の潜水艦はもう航行しませんが、見学者は船内を歩けます。", zh: "博物館裡的潛水艇已不航行，但遊客可以走進艙內參觀。" },
  { id: "mrt", en: "If you use the MRT during rush hour, stand away from the doors until people get off.", ja: "ラッシュ時にMRTを使うなら、乗客が降りるまでドアの前を空けてください。", zh: "尖峰時段搭捷運時，等乘客下車前請讓開車門。" },
  { id: "rickshaw", en: "Before riding the rickshaw, we confirmed the route and price with the driver.", ja: "人力車に乗る前に、車夫とコースと料金を確認しました。", zh: "搭人力車前，我們先和車伕確認路線和價格。" },
  { id: "tricycle", en: "Because the child is still learning to balance, she practices on a tricycle in the park.", ja: "子どもはまだバランスの練習中なので、公園で三輪車に乗っています。", zh: "孩子還在學平衡，所以在公園騎三輪車練習。" },
];

export const TRANSPORTATION_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  { id: "school-bus", en: "The school bus picks up the children at eight.", ja: "スクールバスは八時に子どもたちを迎えに来ます。", zh: "校車八點來接孩子。" },
  { id: "coach", en: "We took a coach to the hot spring.", ja: "観光バスで温泉へ行きました。", zh: "我們搭遊覽車去溫泉。" },
  { id: "minibus", en: "The hotel minibus goes to the station.", ja: "ホテルのマイクロバスは駅まで行きます。", zh: "飯店小巴開往車站。" },
  { id: "truck", en: "A truck delivered our new table.", ja: "トラックが新しいテーブルを届けました。", zh: "貨車送來我們的新桌子。" },
  { id: "van", en: "We loaded the boxes into the van.", ja: "箱をバンに積みました。", zh: "我們把箱子搬上廂型車。" },
  { id: "ambulance", en: "Someone called an ambulance for the injured man.", ja: "けがをした人のために救急車を呼びました。", zh: "有人為受傷的男子叫了救護車。" },
  { id: "police-car", en: "A police car stopped beside the accident.", ja: "事故現場のそばにパトカーが止まりました。", zh: "一輛警車停在事故現場旁。" },
  { id: "fire-truck", en: "The fire truck arrived with its siren on.", ja: "消防車がサイレンを鳴らして到着しました。", zh: "消防車鳴著警笛抵達。" },
  { id: "garbage-truck", en: "The garbage truck comes every Tuesday.", ja: "ゴミ収集車は毎週火曜日に来ます。", zh: "垃圾車每週二來。" },
  { id: "tow-truck", en: "A tow truck carried the broken car away.", ja: "レッカー車が故障した車を運びました。", zh: "拖吊車把故障的汽車載走。" },
  { id: "camper-van", en: "We slept in the camper van by the lake.", ja: "湖のそばでキャンピングカーに泊まりました。", zh: "我們睡在湖邊的露營車裡。" },
  { id: "sports-car", en: "A red sports car passed us.", ja: "赤いスポーツカーが私たちを追い越しました。", zh: "一輛紅色跑車超過我們。" },
  { id: "electric-car", en: "I charge the electric car at home.", ja: "家で電気自動車を充電します。", zh: "我在家為電動車充電。" },
  { id: "electric-scooter", en: "She rented an electric scooter near the station.", ja: "彼女は駅の近くで電動キックボードを借りました。", zh: "她在車站附近租了電動滑板車。" },
  { id: "scooter", en: "The child rides a scooter in the park.", ja: "子どもは公園でキックボードに乗ります。", zh: "孩子在公園騎滑板車。" },
  { id: "skateboard", en: "He practices on his skateboard after school.", ja: "彼は放課後スケートボードを練習します。", zh: "他放學後練滑板。" },
  { id: "roller-skates", en: "She put on her roller skates.", ja: "彼女はローラースケートを履きました。", zh: "她穿上溜冰鞋。" },
  { id: "tram", en: "The tram stops in front of the museum.", ja: "路面電車は博物館の前に止まります。", zh: "路面電車停在博物館前。" },
  { id: "light-rail", en: "We took the light rail downtown.", ja: "ライトレールで中心部へ行きました。", zh: "我們搭輕軌去市中心。" },
  { id: "high-speed-train", en: "The high-speed train leaves at nine.", ja: "新幹線は九時に出発します。", zh: "高鐵九點出發。" },
  { id: "monorail", en: "The monorail goes to the airport.", ja: "モノレールは空港まで行きます。", zh: "單軌電車開往機場。" },
  { id: "cable-car", en: "We rode the cable car up the mountain.", ja: "ケーブルカーで山を登りました。", zh: "我們搭纜車上山。" },
  { id: "gondola-lift", en: "The gondola lift carries skiers uphill.", ja: "ゴンドラリフトがスキー客を山の上へ運びます。", zh: "吊艙纜車把滑雪客送上山。" },
  { id: "helicopter", en: "A helicopter flew over the hospital.", ja: "ヘリコプターが病院の上を飛びました。", zh: "一架直升機飛過醫院上空。" },
  { id: "hot-air-balloon", en: "The hot air balloon rose slowly.", ja: "熱気球がゆっくり上がりました。", zh: "熱氣球緩緩升起。" },
  { id: "airship", en: "An airship flew above the stadium.", ja: "飛行船がスタジアムの上を飛びました。", zh: "一艘飛船飛過體育場上空。" },
  { id: "rocket", en: "We watched the rocket launch on TV.", ja: "テレビでロケットの打ち上げを見ました。", zh: "我們在電視上看火箭發射。" },
  { id: "ferry", en: "The ferry carries cars across the bay.", ja: "フェリーが車を湾の向こうへ運びます。", zh: "渡輪載著汽車橫越海灣。" },
  { id: "cruise-ship", en: "The cruise ship entered the harbor.", ja: "クルーズ船が港に入りました。", zh: "遊輪駛入港口。" },
  { id: "sailboat", en: "A white sailboat crossed the lake.", ja: "白いヨットが湖を渡りました。", zh: "一艘白色帆船越過湖面。" },
  { id: "speedboat", en: "The speedboat left the harbor quickly.", ja: "スピードボートが港を勢いよく出ました。", zh: "快艇迅速駛離港口。" },
  { id: "canoe", en: "We paddled the canoe down the river.", ja: "カヌーをこいで川を下りました。", zh: "我們划獨木舟順流而下。" },
  { id: "kayak", en: "She rented a kayak at the lake.", ja: "彼女は湖でカヤックを借りました。", zh: "她在湖邊租了一艘皮艇。" },
  { id: "submarine", en: "We saw a submarine at the museum.", ja: "博物館で潜水艦を見ました。", zh: "我們在博物館看到潛水艇。" },
  { id: "mrt", en: "I take the MRT to work.", ja: "MRTで会社へ行きます。", zh: "我搭捷運上班。" },
  { id: "rickshaw", en: "We toured the old town by rickshaw.", ja: "人力車で古い町を観光しました。", zh: "我們搭人力車遊覽老街。" },
  { id: "tricycle", en: "My son rides his tricycle in the yard.", ja: "息子は庭で三輪車に乗ります。", zh: "我兒子在院子裡騎三輪車。" },
];

/** Exact transportation pair deployed before the 2026-08 semantic audit. */
export const TRANSPORTATION_PREVIOUS_SIMPLE_OVERRIDES: MainWordSimpleExampleOverride[] = [
  { id: "coach", en: "We took a coach to the hot spring.", ja: "観光バスで温泉へ行きました。", zh: "我們搭長途巴士去溫泉。" },
  { id: "tram", en: "The tram stops in front of the museum.", ja: "路面電車は博物館の前に止まります。", zh: "電車停在博物館前。" },
];

/** Exact transportation complex examples deployed before the 2026-08 semantic audit. */
export const TRANSPORTATION_PREVIOUS_COMPLEX_EXAMPLES: MainWordComplexExample[] = [
  { id: "coach", en: "Because the coach ride takes four hours, it stops once so passengers can take a break.", ja: "観光バスは四時間走るので、乗客が休憩できるよう途中で一度止まります。", zh: "長途巴士車程四小時，中途會停一次讓乘客休息。" },
  { id: "van", en: "We rented a van because five people and all their luggage would not fit in a small car.", ja: "五人分の荷物が小さい車に入らないので、バンを借りました。", zh: "五個人和所有行李塞不進小車，所以我們租了廂型車。" },
  { id: "sports-car", en: "Although the sports car is fast, its low body makes steep parking ramps difficult.", ja: "スポーツカーは速いですが、車体が低いため急な駐車場の坂では注意が必要です。", zh: "跑車雖然很快，但車身低，遇到陡峭停車場斜坡很不方便。" },
  { id: "tram", en: "When the tram shares the road with cars, look carefully before crossing its tracks.", ja: "路面電車が車と同じ道路を走る場所では、線路を渡る前によく確認してください。", zh: "電車和汽車共用道路時，穿越軌道前要仔細查看。" },
  { id: "rocket", en: "Because the rocket launch was delayed by weather, we watched the new time on the news.", ja: "天候でロケットの打ち上げが延期されたので、ニュースで新しい時刻を確認しました。", zh: "火箭發射因天氣延期，所以我們在新聞確認新時間。" },
  { id: "rickshaw", en: "Before riding the rickshaw, we agreed on the route and price with the driver.", ja: "人力車に乗る前に、車夫とコースと料金を確認しました。", zh: "搭人力車前，我們先和車伕確認路線和價格。" },
];
